### ISSUE TITLE
Build ARM raspberry pi version

### ISSUE THREAD

**Issue by gagachang** [litespeedtech/lsquic#100]
Hello,

I built the x86_64 version and tested the library successfully yesterday.
And today I want to build the ARM version and test the library on raspberry pi 3.

For cross-compile problem, do I need to change some settings or just simply modify the CMake files?
Are there any details I need to pay attention to with the ARM version?

Any suggestions would be appreciated, thank you all.

**Comment by dtikhonov** [comment]
I never tried a cross-platform compilation.  I simply compiled on Raspberry Pi directly.  (FWIW, Raspberry 1 works as well).

If you figure out how to cross-compile, we'd consider a PR.

**Comment by gagachang** [comment]
OK, I will try to compile library on Pi directly.
If I have any ideas, I will also try my best about cross-compiling.
Thanks for your reply!
