### ISSUE TITLE
cubic is transfer faster than bbr in bad network? and any plan to support bbr2?

### ISSUE THREAD

**Issue by initlifeinc** [litespeedtech/lsquic#103]
It seems use bbr1 is not quick enough to transfer in a bad network. and i try to change bbr to cubic, it seems cubic is stable than bbr in bad network and even quick than bbr, is it any problems in bbr?  i found that you have already change the default setting to use cubic in new release version,  what's the actual problem you meet to change it?

and one more question, do you have some plans to support bbr2( it seems google have already publish a new version bbr).

**Comment by dtikhonov** [comment]
We found that BBRv1 was better in some circumstances than Cubic, but not in others; Cubic is more consistent.  That is why the default was changed back to Cubic.

We plan to support BBRv2 once it's finalized.  It's in the [Alpha](https://github.com/google/bbr/tree/v2alpha) stage now.

**Comment by initlifeinc** [comment]
i try to send 200KB data to quic server in a bad network(20Mbps bindwidth， but 50% out packet loss, 0% in packet loss) , it cost nearly 10 seconds( if in a good network, it can transfer very fast). 

i find server will reply ack frame in about tens of milliseconds with some frame range. but cwnd size of client will decrease to 5840 very fast. is it any problems to calculate cwnd if use bbr ? 

you can check the following file to check the ack frame log and cwnd log.

[ackframe.log](https://github.com/litespeedtech/lsquic/files/4154431/ackframe.log)
[cwnd.log](https://github.com/litespeedtech/lsquic/files/4154432/cwnd.log)

and one more question about bytes_in_flight and sc_n_in_flight_all
https://github.com/litespeedtech/lsquic/blob/f2a7fa84cd2ec2c206f3fc339a52bf2c0e31e019/src/liblsquic/lsquic_send_ctl.c#L675

![image](https://user-images.githubusercontent.com/10239225/73761983-89322a00-47aa-11ea-905a-d3459cd93a58.png)

i found the second parameter name in "bbr_app_limited (struct lsquic_bbr *bbr, uint64_t bytes_in_flight)", is bytes_in_flight, but sc_n_in_flight_all is passed to lsquic_bbr_sent function. so whether it is a mistake to use ctl->sc_n_in_flight_all as the third parameter in cci_sent.

**Comment by initlifeinc** [comment]
@dtikhonov do you have any suggestions?

**Comment by dtikhonov** [comment]
50% loss is rather extreme.  I don't think we've tested with loss quite that high.  I'll put this onto my _TODO_ list and try to reproduce the behavior you reported above.

As for `bbr_app_limited()`, I think you've spotted a real bug.  Thank you!

**Comment by dtikhonov** [comment]
> As for `bbr_app_limited()`, I think you've spotted a real bug.

This has been addressed in the just-released v2.10.5.

**Comment by initlifeinc** [comment]
reat， i still need to improve the performance to upload file in such a bad network. we test some other app to upload by gquic, it seems it can upload the same file in 3 seconds. we hope we could have some deep contact to discuss about performance in a bad network.

I have already build a demo on iOS platform and use openssl 1.1.1 to send file to a quic-go server. Later I will commit a MR after i adjust some codes
