### ISSUE TITLE
BUG: double free

### ISSUE THREAD

**Issue by cang-mang** [litespeedtech/lsquic#110]
In file lsquic_packet_out.c
In function lsquic_packet_out_destroy
We have:
`if (packet_out->po_bwp_state)`
`    lsquic_malo_put(packet_out->po_bwp_state);`
`lsquic_mm_put_packet_out(&enpub->enp_mm, packet_out);`
It frees packet_out->po_bwp_state but not set it to NULL, and then call lsquic_mm_put_packet_out.

In file lsquic_mm.c
In function lsquic_mm_put_packet_out
We still have:
`if (packet_out->po_bwp_state)`
`    lsquic_malo_put(packet_out->po_bwp_state);`
In lsquic_mm_put_packet_out it will free packet_out->po_bwp_state again.

That is double free.

**Comment by dtikhonov** [comment]
Thank you for the bug report.  This is indeed a double-free, but because `po_bwp_state` is allocated using the _malo_ allocator, this is benign.

It will be fixed in the next release.

**Comment by litespeedtech** [comment]
Fixed in release 2.12.0 -- closing.
