### ISSUE TITLE
How is early-data taken in Q046?

### ISSUE THREAD

**Issue by cang-mang** [litespeedtech/lsquic#116]
The early-data is STREAM frame to create a new stream and post application-data, client side.

Is the early-data taken by some tag or extension in ClientHello?

Or is the early-data taken by a special packet using non-forward-secure encryption key?

**Comment by dtikhonov** [comment]
Early data does not work in Q046 in lsquic (or in any other version, for that matter). It's been on our to-do list for some time, but we haven't gotten around to it yet.

**Comment by PethrusG** [comment]
Good to know that it's disabled by default in all versions! 
I have been looking through the code base to figure out how to enable or disable it but now I know for sure it is disabled by default. Just added a printout in http_client_on_hsk_done() in http_client.c to log explicitly when 0-RTT is NOT enabled and not only when it IS enabled.

By the way, you have really created a very readable, well-structured and overall user-friendly implementation of QUIC. I'm currently using it for my Master's Thesis. Glad I found it!

**Comment by dtikhonov** [comment]
Thanks -- we're glad you like it (star it, star it)!  Good luck with your thesis!

**Comment by PethrusG** [comment]
Hi again!
I saw that the following was written in the commit message of release 2.14.6:
- [BUGFIX] Fix amplification mitigation in 0-RTT case.

**Does this mean that 0-RTT is now working since that release onwards? Or in what release did it start working again?**

**Comment by dtikhonov** [comment]
That item in the changelog refers to the logic around limiting the size of server response per the [Transport Draft, Section 8.1](https://tools.ietf.org/html/draft-ietf-quic-transport-28#section-8.1):

```

   Prior to validating the client address, servers MUST NOT send more
   than three times as many bytes as the number of bytes they have
   received.  This limits the magnitude of any amplification attack that
   can be mounted using spoofed source addresses.  For the purposes of
   avoiding amplification prior to address validation, servers MUST
   count all of the payload bytes received in datagrams that are
   uniquely attributed to a single connection.  This includes datagrams
   that contain packets that are successfully processed and datagrams
   that contain packets that are all discarded.
```

There is still no 0-RTT support in the client.

**Comment by PethrusG** [comment]
Thanks for quickly responding.

Are there any plans of implementing 0-RTT within the nearest future?

**Comment by dtikhonov** [comment]
No, it's not in the cards for now.

**Comment by litespeedtech** [comment]
We probably wont do anything about it as HTTP/3 is coming, and gQUIC is on the way out.

**Comment by YuShengwei-95** [comment]
Any new progress on this issue? I tested and found that in the latest code, both gQUIC and iQUIC can establish a 0-RTT connection, but the actual sending of the request must wait until the SHLO is received, which will cause the 0-RTT feature to not actually take effect.
