### ISSUE TITLE
handshake failed

### ISSUE THREAD

**Issue by qchfu2006** [litespeedtech/lsquic#117]
When I used "echo_server" and "echo_client", it is error!  The "echo_server" side says "handshake failed", and the log is  ：
15:00:43.598 [WARN] Not a single service specified.  Use -c option.
15:00:43.598 [DEBUG] tokgen: TOKGEN1 does not exist: generate
15:00:43.598 [INFO] tokgen: inserted TOKGEN1 of size 110
15:00:43.598 [DEBUG] tokgen: initialized
15:00:43.598 [INFO] prq: initialized queue of size 10000
15:00:43.598 [INFO] purga: create purgatory, min life 30000000 usec
15:00:43.598 [INFO] engine: instantiated engine
15:00:43.598 [INFO] socket buffer size: 212992 bytes; max # packets is set to 6
15:00:43.598 [DEBUG] local address: 127.0.0.1:12345
15:00:43.598 [DEBUG] entering event loop
15:00:58.007 [DEBUG] purga: 682DF42A1F99129FAA6A589BE23B7950 not found
15:00:58.007 [DEBUG] engine: grew heaps to 4 elements
15:00:58.007 [DEBUG] engine: client-supplied version FF00001B is supported
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] mini-conn: recv SCID from client 682DF42A1F99129FAA6A589BE23B7950
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] mini-conn: recv DCID from client 3F7E00E667929E29
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] mini-conn: generated SCID DA58084B24461D6C at index 1, switching to it
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: client handshake secret: 47A3A98B65FCD7E1C2D89A211EC8F1F133C3DFCB0BB0E6D4F9082922BC3E2837
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: server handshake secret: B786AE585A7E6AC35576D76930D31026DEB7010B0951E9533700EF0718F8B67D
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] mini-conn: created mini connection object 0x1dcc400; max packet size=1252
15:00:58.007 [DEBUG] engine: incref conn 3F7E00E667929E29, 'H' -> 'HT'
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] mini-conn: connection to 127.0.0.1:12345 from 127.0.0.1:54406
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: strip header protection using mask 9B0F026831
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] event: decrypted packet 0
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] event: packet in: 0, type: Initial, size: 1200; ecn: 0, spin: 0; path: 0
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] event: CRYPTO frame in: level 0; offset 0; size 226
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] mini-conn: Got CRYPTO frame for enc level #0
15:00:58.007 [DEBUG] tokgen: generated stateless reset token DB52E9A3F487D1882E7772294AB9766B for CID DA58084B24461D6C
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: generated transport parameters buffer of 63 bytes
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: initialized server enc session
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] mini-conn: creating stream on level #0
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: on_new_stream called on level 0
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] mini-conn: dispatch read events on level #0
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: provided 226 bytes of 0-level data to SSL
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: 
0000  01 00 00 DE 03 03 9E 02  F3 84 10 9E 03 AB EA 7A  |...............z|
0010  89 8C 80 AC 94 11 4B 6D  E0 89 55 2A AA A7 EA 27  |......Km..U*...'|
0020  B8 23 FA 4F 56 ED 20 A1  78 B7 6B 69 CA FD 66 8B  |.#.OV. .x.ki..f.|
0030  E4 CA A7 6B C2 20 D9 AB  84 57 E5 DB F3 6B 8F 61  |...k. ...W...k.a|
0040  1C 59 C0 5C 0B 30 1A 00  06 13 01 13 02 13 03 01  |.Y.\.0..........|
0050  00 00 8F 00 0A 00 08 00  06 00 1D 00 17 00 18 00  |................|
0060  0D 00 14 00 12 04 03 08  04 04 01 05 03 08 05 05  |................|
0070  01 08 06 06 01 02 01 00  33 00 26 00 24 00 1D 00  |........3.&.$...|
0080  20 60 27 C8 0B 84 90 05  AD ED 07 9A EE 8B E9 9F  | `'.............|
0090  50 50 2B 9D F2 6A 51 D2  93 07 E0 9E BE C2 5A 43  |PP+..jQ.......ZC|
00A0  32 00 2D 00 02 01 01 00  2B 00 03 02 03 04 FF A5  |2.-.....+.......|
00B0  00 30 01 04 80 00 75 30  03 02 45 5A 04 04 80 F0  |.0....u0..EZ....|
00C0  00 00 05 04 80 60 00 00  07 04 80 00 80 00 08 02  |.....`..........|
00D0  40 64 09 02 40 64 0E 01  08 50 57 01 01 80 00 71  |@d..@d...PW....q|
00E0  57 00                                             |W...............|

15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] mini-conn: read 226 bytes at offset 226 on enc level 0
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: cert lookup: server name is not set
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: could not look up cert for <no SNI>
15:00:58.007 [INFO] [QUIC:3F7E00E667929E29] handshake: got alert 80
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] mini-conn: got TLS alert 80
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: handshake: error:00000001:invalid library (0):OPENSSL_internal:unknown library
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: handshake failed
15:00:58.007 [INFO] [QUIC:3F7E00E667929E29] mini-conn: handshake failed
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: enc level clear after on_read: stop
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: Exit shake_stream
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: have peer transport parameters (48 bytes)
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] handshake: enable sending and receiving QL bits
15:00:58.007 [DEBUG] [QUIC:3F7E00E667929E29] event: PADDING frame in of 919 bytes

Please help me！  Thanks！

**Comment by dtikhonov** [comment]
On the server, you should specify at least one certificate using the `-c` command-line option.  (That's what the warning on the first line is about).
