### ISSUE TITLE
crash by assertion "!(conn->cn_flags & flag)" failed

### ISSUE THREAD

**Issue by recnac-itna** [litespeedtech/lsquic#120]
When I made some performance test on Android platform, I encounter the following error:

```
2020-03-30 20:47:37.610 4593-4833/com.example.counterapp2 A/libc: /root/lsquic/src/liblsquic/lsquic_engine.c:1657: void engine_incref_conn(lsquic_conn_t *, enum lsquic_conn_flags): assertion "!(conn->cn_flags & flag)" failed
2020-03-30 20:47:37.610 4593-4794/com.example.counterapp2 A/libc: /root/lsquic/src/liblsquic/lsquic_engine.c:1673: lsquic_conn_t *engine_decref_conn(lsquic_engine_t *, lsquic_conn_t *, enum lsquic_conn_flags): assertion "conn->cn_flags & flags" failed
2020-03-30 20:47:37.611 4593-4794/com.example.counterapp2 A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 4794 (Thread-2), pid 4593 (ple.counterapp2)
```

What I did is sending 10K data every 30ms. This error will occur about 1 minute later.
Can you help me out? Thanks a lot.

**Comment by dtikhonov** [comment]
Could you provide a backtrace?

**Comment by recnac-itna** [comment]
```
Traceback:
   File "prog.c", line 474, in prog_timer_handler
      prog_process_conns(prog);
   File "prog.c", line 447, in prog_process_conns
      lsquic_engine_process_conns(prog->prog_engine);
   File "lsquic_engine.c", line 1835, in lsquic_engine_process_conns
      conn = engine_decref_conn(engine, conn, LSCONN_ATTQ);
   File "lsquic_engine.c", line 1673, in engine_decref_conn
      assert(conn->cn_flags & flags);
assertion "conn->cn_flags & flags" failed
```
or
```
Traceback:
   File "prog.c", line 474, in prog_timer_handler
      prog_process_conns(prog);
   File "prog.c", line 447, in prog_process_conns
      lsquic_engine_process_conns(prog->prog_engine);
   File "lsquic_engine.c", line 1839, in lsquic_engine_process_conns
      engine_incref_conn(conn, LSCONN_TICKABLE);
   File "lsquic_engine.c", line 1657, in engine_incref_conn
      assert(!(conn->cn_flags & flag));
assertion "!(conn->cn_flags & flag)" failed
```
I write my test program based on `echo_server` and `echo_client`. Like I said above, I will send 10k byte[] data every 33ms.
`echo_server` always crash by this fatal error in a minute.

**Comment by recnac-itna** [comment]
I print the the value of `conn->cn_flags` when assertion failed:
when failed in `engine_decref_conn`:  `conn->cn_flags`=110000000000010001000111‬
when failed in `engine_incref_conn`: `conn->cn_flags`=110010000001010001000100‬
Sometimes these two assertions will occur at the same time. I wonder maybe it is caused by multi-threads?

So I want to confirm whether I use `lsquic` correctly. In Android, I use JNI to call native C code.
1. I start a thread to launch the server like the logic of `main` in `echo_server`. 
2. I use a timer in another thread to call `stream_write` every 30ms. The following is the implementation of `stream_write`:
```
lsquic_stream_ctx_t *cur_ctx;  // used to save the context
void stream_write(char *buf, size_t len)
{
    memcpy(cur_ctx->buf, buf, len);
    cur_ctx->buf_off = len;
    lsquic_stream_wantwrite(cur_ctx->stream, 1);
}
```
I copy data to `lsquic_stream_ctx.buf` and call `lsquic_stream_wantwrite`, but with char array copy here. Before that, I tried call `lsquic_stream_write` directly but failed.

**Comment by recnac-itna** [comment]
I have done more tests, and I found that this error is related to the send frequency:
1. when I expand the send interval to 100ms, this error will no longer appear.
2. when I keep the send interval to 30ms, but decrease the packet size to 3k, this error will still occur with lower probability.

**Comment by dtikhonov** [comment]
> Sometimes these two assertions will occur at the same time. I wonder maybe it is caused by multi-threads?

I am sure this is the problem.  The library does not handle threading internally.  You need either to write external lock logic yourself or to only use a library instance in a single thread.

**Comment by recnac-itna** [comment]
But `lsquic_engine_process_conns` is only called in the `libevent` timer of the main thread. In another thread, I only call `lsquic_stream_wantwrite(cur_ctx->stream, 1)`. I didn't find any data race of `conn->cn_flags`.

**Comment by dtikhonov** [comment]
Here is the call sequence:

- lsquic_stream_wantwrite
- maybe_conn_to_tickable_if_writeable
- lsquic_engine_add_conn_to_tickable
- engine_incref_conn

It is clear that the two threads are updating the same data.

Bottom line: either add locking to your code or only call into a single engine instance from a single thread.

**Comment by recnac-itna** [comment]
Thanks. I got it. 
I prefer the second choice: only call into a single engine instance from a single thread.
Based on `echo_server`, the thread maintains `event_base_loop`. I don't know how to call `lsquic_stream_wantwrite` in a single thread when it is triggered by outside conditions (from android java layer). I cannot use `event_add` in this way. Can you please give me some advice?

**Comment by dtikhonov** [comment]
As long as you have communication between threads, you will need some sort of locking.  If you must use threads, I don't see how one can do without locks in this case.

**Comment by recnac-itna** [comment]
After I add lock to the code blocks which may cause data race, this assertion never shows again. Thanks for your help.

**Comment by dtikhonov** [comment]
You're welcome!
