### ISSUE TITLE
How to use server push features in version Q043?

### ISSUE THREAD

**Issue by minhkstn** [litespeedtech/lsquic#121]
Hi,
I would like to use server push feature. I tried to request 2 files with 100Kbytes for each by using `-p /file-100K?push=2` like the following command line:
`./http_client -H 127.0.0.1 -s 127.0.0.1:1234 -p /file-100K?push=2 -t -L debug 2>client_m.out`
`./http_server -c 127.0.0.1,cert.pem,key.pem -s 127.0.0.1:1234 -o support_push=1 -L debug 2>server_m.out`
But the server returned this
`Segmentation fault (core dumped)`

I guess the path `-p /file-100K?push=2` at the client is wrong. What is the right request in this case?
Thanks

**Comment by dtikhonov** [comment]
The push argument is the path of the file to be pushed.  For example, `-p /file-100K?push=/file-1234`.

**Comment by minhkstn** [comment]
Thanks. However, it comes to other bugs.

1. When QUIC version is FF00001B
**Server**
`./http_server -c 127.0.0.1,cert.pem,key.pem -s 127.0.0.1:1234 -o support_push=1 -L debug 2>server_m.out`
**Client**
`./http_client -H 127.0.0.1 -s 127.0.0.1:1234 -p /file-100K?push=/file-1234 -t -L debug 2>client_m.out`
**Server log**

> 00:41:43.410 [DEBUG] pushing promise for /file-1234 
> 00:41:43.410 [DEBUG] [QUIC:CD98B65961B345CE] conn: cannot push using stream 0

2. When QUIC version is Q043
**Server**
`./http_server -c 127.0.0.1,cert.pem,key.pem -s 127.0.0.1:1234 -o support_push=1 -o version=Q043 -L debug 2>server_m.out`
**Client**
`./http_client -H 127.0.0.1 -s 127.0.0.1:1234 -p /file-50K?push=/file-100K -o version=Q043 -t -L debug 2>client_m.out`
And the server still has this error `Segmentation fault (core dumped)`. Server log ends at line:
 `00:57:42.310 [DEBUG] pushing promise for /file-100K`.
More detail at Server log:

> 00:57:42.310 [INFO] found handler for GET /file-50K?push=/file-100K  
> 00:57:42.310 [DEBUG] [QUIC:446B0A7BA50066AB-5] stream: shutdown; how: 0  
> 00:57:42.310 [DEBUG] [QUIC:446B0A7BA50066AB] spi: read-new: evict stream 5  
> 00:57:42.310 [DEBUG] [QUIC:446B0A7BA50066AB] spi: read-new: priority 240 now has no elements  
> 00:57:42.310 [DEBUG] [QUIC:446B0A7BA50066AB] pacer: lsquic_pacer_can_schedule: 1  
> 00:57:42.310 [DEBUG] [QUIC:446B0A7BA50066AB] sendctl: lsquic_send_ctl_can_send: n_out: 4171 (unacked_all: 4171); cwnd: 46720
> 00:57:42.310 [DEBUG] [QUIC:446B0A7BA50066AB] pacer: lsquic_pacer_can_schedule: 1
> 00:57:42.310 [DEBUG] [QUIC:446B0A7BA50066AB] spi: write-high: find_and_set_lowest_priority: prio 0 -> 240
> 00:57:42.310 [DEBUG] [QUIC:446B0A7BA50066AB] spi: write-high: lsquic_spi_first: return stream 5, priority 240
> 00:57:42.310 [DEBUG] [QUIC:446B0A7BA50066AB] sendctl: lsquic_send_ctl_can_send: n_out: 4171 (unacked_all: 4171); cwnd: 46720
> 00:57:42.310 [DEBUG] [QUIC:446B0A7BA50066AB] pacer: lsquic_pacer_can_schedule: 1
> 00:57:42.310 [DEBUG] pushing promise for /file-100K

How can I deal with this problem? I would like to use version Q043.
Thanks

**Comment by dtikhonov** [comment]
1. IETF QUIC

Support for server push has not been implemented in lsquic _client_.  Thus, it sends such transport parameters as to make it illegal for the server to push.  This is the reason behind the "conn: cannot push using stream 0" log message.

You can change `#define CLIENT_PUSH_SUPPORT 0` from 0 to 1 in lsquic_full_conn_ietf.c.  This will change the client's transport parameters and allow the server to push.  The client will refuse the push and you will be able to see it in the client log.

2. Google QUIC

I haven't been able to reproduce the crash: the push "just works" for me.  Could you provide a backtrace?

**Comment by minhkstn** [comment]
Thank you for your time.
I didn't pull the latest source code. I just updated your code and the push works in Google QUIC.
The version of source code that I incur this issue is as follows

> Author: Dmitri Tikhonov <dtikhonov@litespeedtech.com>
> Date:   Fri Mar 13 11:24:36 2020 -0400
> 
>     Release 2.13.2
>     
>     - [BUGFIX] Use of new lsxpack_header API's hsi_prepare_decode().
> 
> diff --git a/CHANGELOG b/CHANGELOG
> index 06ad692..2e3e4b1 100644
