### ISSUE TITLE
lsquic compile with mingw

### ISSUE THREAD

**Issue by coder-bihao** [litespeedtech/lsquic#122]
Hi~
Backgroud :
I want to use the lsquic library, but my own project is compiled with mingw ,so recently I've been working on lsquic compilation with mingw, and there are a lot of problems.
After I generated the compile instructions on Linux(make VERBOSE=1), I replaced gcc with mingw-gcc, and changed some macro definitions and codes, eg:
1.CMSG_SPACE --->WSA_CMSG_SPACE
2.struct cmsghdr *cmsg   ---> LPWSACMSGHDR cmsg
3.msg.lpBuffers      = specs[n].iov   --->  WSABUF *lpbuffer = (WSABUF*)malloc(sizeof(WSABUF));
                                                                 lpbuffer->buf = (char*)(specs[n].iov->iov_base);
                                                                 lpbuffer->len = (u_long)(specs[n].iov->iov_len);
                                                                 msg.lpBuffers      = lpbuffer;
   this is because LPWSABUF and iovec are defined differently
   
![image](https://user-images.githubusercontent.com/49231365/78653755-2b2ed980-78f6-11ea-85b9-d067cd0da114.png)

Now, I have build the project success, but when I connect the echo_client to the echo_server(echo_client compiled with mingw, echo_server compiled with gcc), I get an error when call the function pfnWSARecvMsg(sport->fd, &msg, &nread, NULL, NULL) in file test_common.c : **socket error WSAGetLastError: 10035**   and return ROP_ERROR which cause the read_handler's while loop to terminate.
And echo_client can send the data to echo_server, and the echo_server can send data back to the client all the time. 

And here are my questions:
1.Is ROP_ERROR  a  normal logic? If not, how can I fix this problem?
2.Does lsquic now support mingw compilation by not changing the code?
   I'm afraid that changing the code will cause unexpected problems.
3.Can I use lsquic in my Mingw project by compiling lsquic to a dynamic library on windows using vc tool chain?(The way mentioned in the BUILD-WINDOWS.md) 
   I'm worried about the different compiler toolchains.

**Comment by coder-bihao** [comment]
Thank you very much and look forward to your reply~

**Comment by dtikhonov** [comment]
Hello -- thank you for trying out lsquic!

lsquic's Windows support is broken.  When the library was called lsquic-client and its version was 1.x, Windows support worked fine.  Then we added server support to the library and released lsquic 2.x, but Windows support was lost.  We haven't had the time to fix the Windows build of lsquic.

To answer your questions:
1. I don't know why the call to `pfnWSARecvMsg` fails.
2. AFAIK, we never tried compiling lsquic using mingw.  We may need changes (such as those you highlighted above) to support it.
3. I don't know.

It would be nice if you forked this repo on GitHub, committed your changes so far on a branch, and referenced the branch in this issue.  This way, when we do get around to fixing the Windows build, we can use your code.

**Comment by coder-bihao** [comment]
Thanks a lot~
There is still a question, I see the code in test/test_common.c : 
     enum rop { ROP_OK, ROP_NOROOM, ROP_ERROR, };
And ROP_OK、ROP_NOROOM can not break the read_hanler's while loop, so is ROP_ERROR a normal logic? 
![image](https://user-images.githubusercontent.com/49231365/78678511-a060d580-791b-11ea-8774-39ec11b00b45.png)

**Comment by dtikhonov** [comment]
I don't understand the question, could you please restate it?

The inner loop reads until the read status is not `ROP_OK`.

The outer loop is exited when the read status is not `ROP_NOROOM`.  This status means that there is no room in the buffer to read in another packet from the socket.  In other words, if reading stopped because the buffer is full, process packets that have been read in and continue, as there may be more packets waiting to be read from the socket.
