### ISSUE TITLE
Questions about prog_timer_handler 

### ISSUE THREAD

**Issue by coder-bihao** [litespeedtech/lsquic#126]
HI~
I have some questions about the test/prog.c.
1.I change the timeout variable in prog_process_conns function to 10 s, but it not work and prog_process_conns still be called in less than 10s，how's that happen?
![image](https://user-images.githubusercontent.com/49231365/79563985-64c6c800-80e0-11ea-9569-763f141b1337.png)

2.what is the true meaning of the diff in function lsquic_engine_earliest_adv_tick?

**Comment by coder-bihao** [comment]
Thank you very much and look forward to your reply~

**Comment by coder-bihao** [comment]
Diff > prog->prog_settings.es_clock_granularity, When will it happen?

**Comment by dtikhonov** [comment]
1. `prog_process_conns()` is also called from `read_handler()`.

2. The API is documented in lsquic.h as well as [on the web](https://lsquic.readthedocs.io/en/latest/apiref.html#receiving-packets):

```c
/**
 * Returns true if there are connections to be processed, false otherwise.
 * If true, `diff' is set to the difference between the earliest advisory
 * tick time and now.  If the former is in the past, the value of `diff'
 * is negative.
 */
int
lsquic_engine_earliest_adv_tick (lsquic_engine_t *engine, int *diff);
```

3. Re: es_clock_granularity:  What will _what_ happen?
