### ISSUE TITLE
http_client does not work with OpenBSD.

### ISSUE THREAD

**Issue by ledeuns** [litespeedtech/lsquic#127]
Hi, I built lsquic on OpenBSD (6.7-beta, current with diff from https://framagit.org/ledeuns/openbsd/-/raw/master/lsquic.diff)  but it does not work.

When I launch "./http_client -L debug -s www.google.com -p /", I get "out of room in packets_in" (same problem with option -4 and I tested with multiple servers, google.com, litespeedtech.com)

I checked the code but could not find any obvious issue. Can someone give a pointer to fix this please ?

Thank you in advance,

Logfile :
> 14:59:32.683 [DEBUG] host: www.google.com; port: 443
> 14:59:32.750 [DEBUG] tokgen: TOKGEN1 does not exist: generate
> 14:59:32.751 [INFO] tokgen: inserted TOKGEN1 of size 110
> 14:59:32.751 [DEBUG] tokgen: initialized
> 14:59:32.751 [INFO] engine: instantiated engine
> 14:59:32.751 [INFO] socket buffer size: 41600 bytes; max # packets is set to 0
> 14:59:32.752 [DEBUG] engine: grew heaps to 4 elements
> 14:59:32.752 [DEBUG] conn: generated and assigned SCID EECACF0199C735DE
> 14:59:32.752 [DEBUG] [QUIC:] rechist: instantiated received packet history
> 14:59:32.752 [DEBUG] [QUIC:] rechist: instantiated received packet history
> 14:59:32.752 [DEBUG] [QUIC:] rechist: instantiated received packet history
> 14:59:32.752 [DEBUG] [QUIC:] cubic: lsquic_cubic_init(cubic, $conn)
> 14:59:32.752 [INFO] [QUIC:] cubic: initialized
> 14:59:32.752 [DEBUG] [QUIC:] cfcw: recv_off changed: read_off: 0; recv_off: 15728640
> 14:59:32.752 [DEBUG] [QUIC:] conn: spin bit randomly disabled; random spin bit value is 0
> 14:59:32.752 [DEBUG] [QUIC:EECACF0199C735DE] handshake: created client, DCID: D4CDE846BE2BDA94
> 14:59:32.752 [DEBUG] [QUIC:EECACF0199C735DE] handshake: client handshake secret: D79BC7853D4F19E168F1EC5465577B5F53F44
> 393D8F6B7FD5330DB7E400B6796
> 14:59:32.752 [DEBUG] [QUIC:EECACF0199C735DE] handshake: server handshake secret: 16BA81205F7A4879398ABB8086814E302D45B
> C8B39EE7908504A9E3E10873900
> 14:59:32.753 [DEBUG] [QUIC:EECACF0199C735DE-18446744073709551615] di: initialized
> 14:59:32.753 [DEBUG] [QUIC:EECACF0199C735DE-18446744073709551615] sfcw: recv_off changed: read_off: 0; recv_off: 16384
> 14:59:32.753 [DEBUG] [QUIC:EECACF0199C735DE-18446744073709551615] stream: created crypto stream
> 14:59:32.753 [DEBUG] [QUIC:EECACF0199C735DE-18446744073709551615] stream: calling on_new_stream
> 14:59:32.753 [DEBUG] [QUIC:EECACF0199C735DE] handshake: Create new SSL_CTX
> 14:59:32.889 [DEBUG] [QUIC:EECACF0199C735DE] handshake: generated transport parameters buffer of 43 bytes
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] handshake: initialized client enc session
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] handshake: handshake stream created successfully
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] conn: negotiating version FF00001B
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] conn: logging using client SCID
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] event: connection created
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] qlog: [15271142099,"CONNECTIVITY","NEW_CONNECTION","LINE",{"ip_version":"
> 6","srcip":"::","dstip":"2a00:1450:4001:81d::2004","srcport":"23273","dstport":"443"}]
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] event: version negotiation: proposed version FF00001B
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] qlog: [15271142110,"CONNECTIVITY","VERNEG","LINE",{"proposed_version":"FF
> 00001B"}]
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] conn: record path 0: (:::23273 - 2a00:1450:4001:81d::2004:443)
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] conn: record new path ID 0
> 14:59:32.890 [DEBUG] engine: incref conn EECACF0199C735DE, 'H' -> 'HT'
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] conn: delayed stream creation.  Backlog size: 1
> 14:59:32.890 [DEBUG] engine: decref conn EECACF0199C735DE, 'HT' -> 'H'
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] pacer: lsquic_pacer_can_schedule: 1
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE-18446744073709551615] stream: buffered 512 bytes; 512 bytes are now in buf
> fer
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] handshake: wrote 512 bytes to stream at encryption level 0
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE-18446744073709551615] stream: will flush up to offset 512
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] sendctl: lsquic_send_ctl_can_send: n_out: 0 (unacked_all: 0); cwnd: 46720
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] pacer: lsquic_pacer_can_schedule: 1
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] sendctl: created packet 0
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] event: created packet 0; flags: version=1, nonce=0, conn_id=1
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] pacer: lsquic_pacer_packet_scheduled: replenish tokens: 10
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] pacer: lsquic_pacer_packet_scheduled: tokens: 9
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] event: generated CRYPTO frame: offset: 0, size: 512
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE-18446744073709551615] stream: flushed to or past required offset 512
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] handshake: retry read
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] handshake: enc level clear after on_write: want read
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] handshake: Exit shake_stream
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] conn: sit-0 streams: max count: 0; created streams: 0
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] conn: created 0 delayed streams
> 14:59:32.890 [DEBUG] engine: incref conn EECACF0199C735DE, 'H' -> 'HO'
> 14:59:32.890 [DEBUG] engine: incref conn EECACF0199C735DE, 'HO' -> 'HOK'
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] sendctl: cum_size: 559; limit: 1200
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] sendctl: Added 641 bytes of PADDING to packet 0
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] handshake: apply header protection using mask D4F3D251A7
> 14:59:32.890 [DEBUG] engine: batched packet 0 for connection EECACF0199C735DE
> 14:59:32.890 [DEBUG] engine: batched all outgoing packets for full conn EECACF0199C735DE
> 14:59:32.890 [DEBUG] engine: packets out returned 1 (out of 1)
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] event: sent packet 0, type Initial, crypto: clear, size 1200, frame types
> : PADDING CRYPTO, ecn: 0, spin: 0; kp: 0, path: 0, flags: 1147658
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] sendctl: packet 0 has been sent (frame types: PADDING CRYPTO)
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] sendctl: set retx alarm to 15271292520, which is 150000 usec from now, mo
> de RETX_MODE_HANDSHAKE
> 14:59:32.890 [DEBUG] engine: decref conn EECACF0199C735DE, 'HOK' -> 'HK'  
> 14:59:32.890 [DEBUG] engine: send_packets_out: sent 1 packet
> 14:59:32.890 [DEBUG] engine: decref conn EECACF0199C735DE, 'HK' -> 'H'
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE-18446744073709551615] di: get_frame: no frame at read offset 0
> 14:59:32.890 [DEBUG] [QUIC:EECACF0199C735DE] conn: not tickable
> 14:59:32.890 [DEBUG] engine: incref conn EECACF0199C735DE, 'H' -> 'HA'
> 14:59:32.890 [DEBUG] engine: next advisory tick is 149864 usec away: conn EECACF0199C735DE: RETX_INIT
> 14:59:32.890 [DEBUG] entering event loop
> 14:59:32.921 [DEBUG] out of room in packets_in
> 14:59:32.921 [DEBUG] out of room in packets_in
> 14:59:32.921 [DEBUG] out of room in packets_in
> 14:59:32.921 [DEBUG] out of room in packets_in
> 14:59:32.921 [DEBUG] out of room in packets_in
> [...]

**Comment by dtikhonov** [comment]
This is the key log message:

> 14:59:32.751 [INFO] socket buffer size: 41600 bytes; max # packets is set to 0

The corresponding code is

```c
    socklen_t opt_len;
    int recvsz;

    opt_len = sizeof(recvsz);
    if (0 != getsockopt(fd, SOL_SOCKET, SO_RCVBUF, (void*)&recvsz, &opt_len))
    {
        LSQ_ERROR("getsockopt failed: %s", strerror(errno));
        return NULL;
    }

    n_alloc = (unsigned) recvsz / MAX_PACKET_SZ * 2;
    LSQ_INFO("socket buffer size: %d bytes; max # packets is set to %u",
        recvsz, n_alloc);
```

Because `MAX_PACKET_SZ` is 0xFFFF, the maximum number of packets is calculated to be zero...  Admittedly, this is not the best logic in the world.

To fix this, you can just change `MAX_PACKET_SZ` to some other value.

**Comment by ledeuns** [comment]
Nice catch! If I set MAX_PACKET_SZ to 1500, it works :)

Thank you very much Dmitri.

**Comment by dtikhonov** [comment]
I am glad to hear it works -- I will add OpenBSD to the list of supported platforms.  (After deciding on what the proper fix should be...)

**Comment by dtikhonov** [comment]
Oh, and I missed that diff above!  Thanks.  If you want to open a PR, we always like that.  If not, no bid deal: I'll merge the diff myself.

**Comment by ledeuns** [comment]
The above diff is not enough, OpenBSD does not have STAILQ_*.
I did not know how to add it to this diff so I added STAILQ_* manually to sys/queue.h on my system.

**Comment by dtikhonov** [comment]
Oh. There is a sys/queue.h under wincompat directory that gets included for Windows build. You could do something similar for OpenBSD.
