### ISSUE TITLE
BUG: lsquic crashes in multi-thread using

### ISSUE THREAD

**Issue by cang-mang** [litespeedtech/lsquic#128]
In file lsquic_crt_compress.c
We have:
`static lsquic_str_t *s_ccsbuf;`
This pointer is not protected by any mutex. So if we use lsquic in multi-thread programs, it will crash while calling `get_common_certs_hash` in more than one thread.

**Comment by dtikhonov** [comment]
Good catch!

**Comment by cang-mang** [comment]
The logger system also needs to be modified. Because for one message, lsquic calls logger callback function more than one time. In multi-thread using, it is terrible.

**Comment by jazune** [comment]
@cang-mang Did do fixed thess problems about multi-thread？

**Comment by dtikhonov** [comment]
> Because for one message, lsquic calls logger callback function more than one time.

@cang-mang, I just looked at [the code](https://github.com/litespeedtech/lsquic/blob/v2.20.0/src/liblsquic/lsquic_logger.c#L284) -- this is not the case.  The callback is called once per log message.

Or did you mean something else?

**Comment by cang-mang** [comment]
> @cang-mang Did do fixed thess problems about multi-thread？

Yes, I have fixed. I am still using version 1.21.2, and I fixed in this version.

**Comment by dtikhonov** [comment]
1.21.2 is quite old!  Have you considered moving on to 2.x, @cang-mang?  If so, would you mind testing out branch `202009251152-thread-safety`?

**Comment by cang-mang** [comment]
> > Because for one message, lsquic calls logger callback function more than one time.
> 
> @cang-mang, I just looked at [the code](https://github.com/litespeedtech/lsquic/blob/v2.20.0/src/liblsquic/lsquic_logger.c#L284) -- this is not the case. The callback is called once per log message.
> 
> Or did you mean something else?

The latest version is OK. Now I am using version 1.21.2, it has the problem.

**Comment by cang-mang** [comment]
> 1.21.2 is quite old! Have you considered moving on to 2.x, @cang-mang? If so, would you mind testing out branch `202009251152-thread-safety`?

We have the plan to move to 2.x before 2021-06-30.

**Comment by litespeedtech** [comment]
Fixed -- closing.
