### ISSUE TITLE
Q: Where to get the document of Google-QUIC standard?

### ISSUE THREAD

**Issue by cang-mang** [litespeedtech/lsquic#130]
Not IETF-QUIC standard.

I want to know the details of Q046 or Q050. Where can I get the document?

**Comment by dtikhonov** [comment]
There is no documentation: you'll have to read the source code -- either lsquic or Chromium.

**Comment by dtikhonov** [comment]
I take it back: there is also this:

https://tools.ietf.org/html/draft-hamilton-quic-transport-protocol-01
