### ISSUE TITLE
Help on running test/echo server & client examples

### ISSUE THREAD

**Issue by RBEI-Srinivas** [litespeedtech/lsquic#131]
Help on running echo server & client on same linux box

Hi, 
I am exploring QUIC & lsquic.  Compiled the libraries & examples; but struggling to get the echo_server, echo_client to example the data. 
Need help on the commandline parameters.
1. generate the key & cert files form openssl
2. : executed the server as ==> $ sudo ./echo_server -c localhost,./certificate.crt,./privateKey.key
     server listens ..... [ but not sure if this is really in a state to accept connection ]
help says that if -s not given , " 0.0.0.0:12345 address is default". 
3. now running a client as $./echo_client -s localhost
18:21:21.552 [NOTICE] Connection closed
$
gives error. 
What am I missing here?

**Comment by dtikhonov** [comment]
Try running the client as

```
./echo_client -H localhost -s 127.0.0.1:12345
```

You can use `-L` and `-l` options to print log messages, e.g. `-L debug`.

**Comment by RBEI-Srinivas** [comment]
Thanks a lot. it works now.

I couldn't understand -H, -s options fully. Any documentation, pls?

**Comment by dtikhonov** [comment]
Besides the output of `-h`, there is also EXAMPLES.txt.

The library API is described here:

https://lsquic.readthedocs.io/en/latest/
