### ISSUE TITLE
removing dependency on libevent

### ISSUE THREAD

**Issue by nyrahul** [litespeedtech/lsquic#133]
#132 added support for Android and it disabled tests compilation so as to remove the dependency on libevent.

However, a subsequent commit reduced the scope for tests only towards unit tests using the macros LSQUIC_TESTS=OFF .. however other example codes such as echo_client/server, http_client/server, md5_client/server also depend on libevent.

On Android, libevent is not included by default and thus the CMake fails (due to libevent dependency). I was hoping that LSQUIC_TESTS=OFF could encompass even echo_client/server and other sample codes such that the Android platform liblsquic.a could be produced without using libevent at all.

**Comment by dtikhonov** [comment]
There is now also LSQUIC_BIN=OFF which you can use to disable compilation of the example binaries.  Specifying both -DLSQUIC_TESTS=OFF and -DLSQUIC_BIN=OFF should compile just 

The reason for the split is that the unit tests do not use libevent.  One can imaging a scenario where one would want to build tests, but not the example programs.

**Comment by nyrahul** [comment]
Using LSQUIC_BIN=OFF and LSQUIC_TESTS=OFF works perfectly fine. Sorry, my bad.

Just for ref, the command I used is:
`# cmake -DLSQUIC_BIN=OFF -DLSQUIC_TESTS=OFF -DBORINGSSL_DIR=../boringssl -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a .`

Additionally, you have to compile your app code with `-fsanitize=address` if you are linking with boringssl/lsquic compiled in debug mode.
NDK versions tested with r19b & r21b.

**Comment by dtikhonov** [comment]
With regard to `-fsanitize=address`, is that because lsquic's cmake tacks it on by default?

```cmake
    IF(CMAKE_C_COMPILER MATCHES "clang" AND
                        NOT "$ENV{TRAVIS}" MATCHES "^true$" AND
                        NOT "$ENV{EXTRA_CFLAGS}" MATCHES "-fsanitize")
        SET(MY_CMAKE_FLAGS "${MY_CMAKE_FLAGS} -fsanitize=address")
        SET(LIBS ${LIBS} -fsanitize=address)
    ENDIF()
```

If that's a problem, you could specify `-fno-sanitize-address` in `EXTRA_CFLAGS`.

**Comment by nyrahul** [comment]
> With regard to `-fsanitize=address`, is that because lsquic's cmake tacks it on by default?
> 
> ```cmake
>     IF(CMAKE_C_COMPILER MATCHES "clang" AND
>                         NOT "$ENV{TRAVIS}" MATCHES "^true$" AND
>                         NOT "$ENV{EXTRA_CFLAGS}" MATCHES "-fsanitize")
>         SET(MY_CMAKE_FLAGS "${MY_CMAKE_FLAGS} -fsanitize=address")
>         SET(LIBS ${LIBS} -fsanitize=address)
>     ENDIF()
> ```
> 
> If that's a problem, you could specify `-fno-sanitize-address` in `EXTRA_CFLAGS`.

Yep, looks like `-fsanitize=address` appears only for clang (which is what I am using for Android cross-compilation). If I use `-fno-sanitize=address` compilation/linking works fine without sanitizer.

`#EXTRA_CFLAGS=-fno-sanitize=address cmake -DLSQUIC_BIN=OFF -DLSQUIC_TESTS=OFF -DBORINGSSL_DIR=../boringssl -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a .` 

Another point I would like to mention is that currently lsquic expects that the boringssl build folder is the same as the boringssl base folder. For me, it would have helped to have build folder separately.

| Current | Expected |
|------------|--------------|
| `cd boringssl`<br>`cmake . && make`<br>`BORINGSSL=$PWD`<br>`cd $LSQUIC_DIR`<br>`cmake -DBORINGSSL_DIR=$BORINGSSL . && make` | `cd boringssl`<br>`mkdir build && cd build`<br>`cmake .. && make`<br>`BORINGSSL=$PWD`<br>`cd $LSQUIC_DIR`<br>`cmake -DBORINGSSL_DIR=$BORINGSSL . && make` |

Usually, the build folder could be separated out for all other projects using cmake. lsquic CMakeLists.txt makes path assumptions relative to boringssl base folder (and not build folder).
If build folders could be kept separate then I can build for linux/android platform using the same boringssl codebase. Currently, I cant.

**Comment by dtikhonov** [comment]
Internally, we always use the Clang Address Sanitizer for debug builds.  I suppose it's not necessary to force it onto others.  I will probably just remove it.

An alternative to `BORINGSSL_DIR` is the pair of `BORINGSSL_INCLUDE` and `BORINGSSL_LIB`.  I think you can achieve what you need by specifying `BORINGSSL_INCLUDE` in addition to `BORINGSSL_DIR`.

**Comment by nyrahul** [comment]
> Internally, we always use the Clang Address Sanitizer for debug builds. I suppose it's not necessary to force it onto others. I will probably just remove it.
> 
> An alternative to `BORINGSSL_DIR` is the pair of `BORINGSSL_INCLUDE` and `BORINGSSL_LIB`. I think you can achieve what you need by specifying `BORINGSSL_INCLUDE` in addition to `BORINGSSL_DIR`.

This almost worked, except for a small fix. Please check #134.

**Comment by gongjiancheng123** [comment]
@dtikhonov I also want to use lsquic without libevent, can you give a simple example use lsquic without libevent?

**Comment by dtikhonov** [comment]
@gongjiancheng123, see my [lsquic tutorial](https://github.com/dtikhonov/lsquic-tutorial) project: it uses libev instead of libevent.

**Comment by dtikhonov** [comment]
I've forgotten about this issue.  I just tested this, and a library (either static or shared) can be compiled without libevent at all, by specifying `-DLSQUIC_BIN=0 -DLSQUIC_TESTS=0` arguments to `cmake`.

**Comment by litespeedtech** [comment]
Fixed -- closing.
