### ISSUE TITLE
Building with Docker got a error message

### ISSUE THREAD

**Issue by lsg941010** [litespeedtech/lsquic#138]
Hi Dear developers,
I tried to use the command to build with docker,  but I think I might get something wrong.
The error message:
`Step 9/10 : RUN cd /src/lsquic &&     cmake -DBORINGSSL_DIR=/src/boringssl . &&     make
 ---> Running in e6df8795f205
CMake Error: The current CMakeCache.txt directory /src/lsquic/CMakeCache.txt is different than the directory /Users/nini/Development/lsquic/boringssl/lsquic where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt`

`sudo docker run -it --rm lsquic http_client -s www.google.com  -p / -o version=Q046
Password:
Unable to find image 'lsquic:latest' locally`
Thanks a lot!

**Comment by lsg941010** [comment]
Additional logs on these
```
src/liblsquic/CMakeFiles/lsquic.dir/build.make:475: recipe for target 'src/liblsquic/CMakeFiles/lsquic.dir/lsquic_enc_sess_ietf.c.o' failed
make[2]: *** [src/liblsquic/CMakeFiles/lsquic.dir/lsquic_enc_sess_ietf.c.o] Error 1
CMakeFiles/Makefile2:343: recipe for target 'src/liblsquic/CMakeFiles/lsquic.dir/all' failed
make[1]: *** [src/liblsquic/CMakeFiles/lsquic.dir/all] Error 2
make: *** [all] Error 2
Makefile:94: recipe for target 'all' failed
The command '/bin/sh -c cd /src/lsquic &&     cmake -DBORINGSSL_DIR=/src/boringssl . &&     make' returned a non-zero code: 2
```

**Comment by lsg941010** [comment]
Similar issue as in #17 . Closing

**Comment by dtikhonov** [comment]
Did the steps in #17 resolve your issue, @lsg941010, or is the Docker build still broken?

We don't use Docker builds much, so it's possible it's gotten out of date.
