### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by ptrd** [litespeedtech/lsquic#140]
The docker build fails on compiling lsquic_enc_sess_ietf.c:
`/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c: In function 'iquic_esfi_init_server':
/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c:1255:10: error: implicit declaration of function 'SSL_set_quic_early_data_context' [-Werror=implicit-function-declaration]
     if (!SSL_set_quic_early_data_context(enc_sess->esi_ssl,
          ^
/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c: At top level:
/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c:2903:5: error: unknown field 'set_read_secret' specified in initializer
     .set_read_secret        = cry_sm_set_read_secret,
     ^
/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c:2903:31: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     .set_read_secret        = cry_sm_set_read_secret,
                               ^
/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c:2903:31: note: (near initialization for 'cry_quic_method.set_encryption_secrets')
/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c:2904:5: error: unknown field 'set_write_secret' specified in initializer
     .set_write_secret       = cry_sm_set_write_secret,
     ^
/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c:2904:31: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     .set_write_secret       = cry_sm_set_write_secret,
                               ^
/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c:2904:31: note: (near initialization for 'cry_quic_method.add_handshake_data')
/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c:2905:31: error: initialized field overwritten [-Werror=override-init]
     .add_handshake_data     = cry_sm_write_message,
                               ^
/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c:2905:31: note: (near initialization for 'cry_quic_method.add_handshake_data')
cc1: error: unrecognized command line option '-Wno-implicit-fallthrough' [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [src/liblsquic/CMakeFiles/lsquic.dir/lsquic_enc_sess_ietf.c.o] Error 1`

Running docker on macos (although i think that doesn't matter)

**Comment by dtikhonov** [comment]
Oh, I see: Dockerfile is out of date.  The version of BoringSSL to use is 251b5169fd44345f455438312ec4e18ae07fd58c.  Thanks for the bug report!
