### ISSUE TITLE
Is there a plan to support QUIC datagrams?

### ISSUE THREAD

**Issue by JonasVautherin** [litespeedtech/lsquic#143]
I was looking at the [HTTP3 datagrams draft](https://tools.ietf.org/id/draft-schinazi-quic-h3-datagram-01.html), and was wondering if there was a plan to integrate it in lsquic at some point?

Mainly out of curiosity :innocent:.

**Comment by dtikhonov** [comment]
We were going to do it at one point, but then some higher-priority items came up.  We'd still like to do it, but *when* this will be done is not known.

Of course, we always welcome PRs! 🙂   If you'd like to give it a shot, I can give an outline of what would need to be done.

**Comment by JonasVautherin** [comment]
Thanks a lot! I'll first try to get used to the library, I'm not yet completely sure how to use the reliable HTTP3 streams :see_no_evil:.

**Comment by dtikhonov** [comment]
Take your time!

You may find these useful:
https://github.com/dtikhonov/talks/blob/20200227-netdev/netdev-0x14/lsquic-slides.md
https://github.com/dtikhonov/lsquic-tutorial

**Comment by dtikhonov** [comment]
Datagram support will be released next week.  Stay tuned.

**Comment by dtikhonov** [comment]
Support for datagrams have been added in version 2.20.0 of lsquic.  The new functions are documented in the [API Reference](https://lsquic.readthedocs.io/en/v2.20.0/apiref.html#datagrams).  There are new example programs `duck_server` and `duck_client` that use _DATAGRAM_ frames.

**Comment by JonasVautherin** [comment]
Awesome!
