### ISSUE TITLE
How is client migration managed?

### ISSUE THREAD

**Issue by ConfortiLuca** [litespeedtech/lsquic#144]
I am working on using QUIC in a cloud environment where migrations occurred frequently.
I have been running some tests using your implementation where the client, given as example in the library, is connected to the public server:
http3-test.litespeedtech.com:4433
The client runs in a Mac OS and it has been modified in order to perform a cycle of a number of the same HTTP GET requests and a sleep phase between each of them. The connection to the server is closed after the last HTTP request.
The migration of the client is performed switching the access point to which the laptop is connected from the normal adsl wifi used inside the house to a wifi provided by a mobile device using hotspot. The laptop, and so the client, changes the public address and the migration is handled by the two endpoints.

I print the frames and the information inside them in every datagram that the client sends/receives in order to check how the two endpoints handle the migration and I find out that the client receives three different path challenge frames in three different datagrams for the same path (same path ID) but with different challenges inside each of them, for each of them it responses with a path response frame. 
Another thing that happens is that the client changes the source ID.

I read the draft and find out that the server can send multiple path challenge in order to avoid problems derived from the possibility of packet loss; but with the same path challenge and the client has to reply only to the first one it receives. 
There is no section that says something about multiple path challenge frames (and so multiple path validation) for the same path during a migration. 
Instead the change of the source ID of the client is conformed with the section 9.5 of the draft for privacy reason. 
My question is why the client receives these three frames and not just one. Thanks very much.

**Comment by dtikhonov** [comment]
> the client has to reply only to the first one it receives.

This is incorrect.  The client (or server -- either endpoint) MUST respond to a path challenge.  In [Section 8.4](https://tools.ietf.org/html/draft-ietf-quic-transport-29#section-8.4):

```
   On receiving a PATH_CHALLENGE frame, an endpoint MUST respond
   immediately by echoing the data contained in the PATH_CHALLENGE frame
   in a PATH_RESPONSE frame.
```

When lsquic detects a new path, it sends a path challenge.  Path challenges do not follow a normal packet loss logic.  This is because the path is new and we don't know anything about it.  A path challenge is sent until response is received using exponential backoff: 25ms, 50ms, 100ms, and so on.  The code is here:

https://github.com/litespeedtech/lsquic/blob/v2.19.4/src/liblsquic/lsquic_full_conn_ietf.c#L4172L4173

**Comment by ConfortiLuca** [comment]
Thanks a lot for the explanation. I get now what I misunderstood from the draft. 

> A path challenge is sent until response is received using exponential backoff: 25ms, 50ms, 100ms, and so on. 

So if I understand correctly, in my case, the client receives three different path challenge frames because when the server detects a new path it sends the first path challenge frame; then, before the server processes the path response frame in reply to its first path challenge, the timer fires two different times and so each time the server sends a new path challenge frame for the same path. 
When the server processes the path response frame in reply to its first path challenge it unsets the timer and so no other path challenge frames are going to be sent. 
The client instead immediately replies to each path challenge frame received echoing the data contained.

And I guess this behavior is the one explained in the last paragraph of the [Section 9.4](https://tools.ietf.org/html/draft-ietf-quic-transport-29#section-9.4)
> ```
>    An endpoint might set a separate timer when a PATH_CHALLENGE is sent, 
>    which is cancelled if the corresponding PATH_RESPONSE is received.  
>    If the timer fires before the PATH_RESPONSE is received, the endpoint might send a new
>    PATH_CHALLENGE, and restart the timer for a longer period of time.
> ```

**Comment by dtikhonov** [comment]
Yes, this is exactly right.
