### ISSUE TITLE
Build error on linux ubuntu platform. 

### ISSUE THREAD

**Issue by yc1997427** [litespeedtech/lsquic#147]
Hi, 

When I run the command : cmake -DBORINGSSL_DIR=$BORINGSSL . 
to build lsquic, 

-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type: Debug
-- Performing Test HAS_NO_IMPLICIT_FALLTHROUGH
-- Performing Test HAS_NO_IMPLICIT_FALLTHROUGH - Success
-- AddressSanitizer is OFF
-- Compiler flags:   -DLSQUIC_DEBUG_NEXT_ADV_TICK=1 -Wall -Wextra -Wno-unused-parameter -fno-omit-frame-pointer -Wno-implicit-fallthrough -Wno-missing-field-initializers -O0 -g3 -Werror 
-- Found Perl: /usr/bin/perl (found version "5.26.2") 
CMake Error at CMakeLists.txt:138 (MESSAGE):
  BoringSSL headers not found

-- Configuring incomplete, errors occurred!
See also "/root/yuecheng/QUIC-measurement-kit/extern/boringssl/lsquic/CMakeFiles/CMakeOutput.log".

**Comment by dtikhonov** [comment]
Did you clone the BoringSSL repo (or got the sources otherwise), compile it, and set `BORINGSSL` to the correct value?

**Comment by yc1997427** [comment]
Hi, thank you very much for you help, really appreciate! Yes, I followed the instructions step by step. I saw your message in our quic repo, https://github.com/Winters123/QUIC-measurement-kit/issues/4. I'm currently in charge of the project, that's why I'm building lsquic and test it.

**Comment by dtikhonov** [comment]
As far as I can tell, the build instructions are correct.  You can always check the [travis file](https://github.com/litespeedtech/lsquic/blob/master/.travis.yml), which results in a [successful build on a Ubuntu system](https://travis-ci.org/github/litespeedtech/lsquic/jobs/721487521).

**Comment by yc1997427** [comment]
Thanks, have sucessfully built.

**Comment by dtikhonov** [comment]
Great!  Let me know if you have any other questions.

Regarding the statistics, I have recently realized that `http_client` already has statistics built-in.  Check out the `-t` option.  For example:

```
[dmitri@okhta lsquic]$ ./http_client -s www.facebook.com -p / -t - -K
overall statistics as calculated by ./http_client:
time for connect: n: 1; min: 17.23 ms; max: 17.23 ms; mean: 17.23 ms; sd: 0.00 ms
time for request: n: 1; min: 41.59 ms; max: 41.59 ms; mean: 41.59 ms; sd: 0.00 ms
time to 1st byte: n: 1; min: 94.98 ms; max: 94.98 ms; mean: 94.98 ms; sd: 0.00 ms
downloaded 160960 application bytes in 0.159 seconds
6.30 reqs/sec; 1014158 bytes/sec
read handler count 123
[dmitri@okhta lsquic]$ 
```

**Comment by yc1997427** [comment]
Thanks. Indeed, the statistics is printed out. I think there might be some problems with our servers. I run the same command, but got:
 ./http_client -s www.facebook.com -p / -t - -K
overall statistics as calculated by ./http_client:
time for connect: n: 0; min: 0.00 ms; max: 0.00 ms; mean: 0.00 ms; sd: 0.00 ms
time for request: n: 0; min: 0.00 ms; max: 0.00 ms; mean: 0.00 ms; sd: 0.00 ms
time to 1st byte: n: 0; min: 0.00 ms; max: 0.00 ms; mean: 0.00 ms; sd: 0.00 ms
downloaded 0 application bytes in 10.002 seconds
0.00 reqs/sec; 0 bytes/sec
read handler count 0

I'm currently debugging the problem.

**Comment by dtikhonov** [comment]
Try dropping `-K` (discard) and adding `-L debug`

**Comment by yc1997427** [comment]
Hi,

Sorry to bother. I've looked at the debug output, every step of lsquic works well, the problem seems lies at connection creation or stream creation: since it reports 0 conn, 0 delayed stream created. I attached the terminal output. But it won't be a big problem, since our experiment will run on 2 local servers, both server side and client side are deployed at one server, the other server will run tlem to reorder, delay packets. I'll check the doc now see if there are options support local testing. If not, I'll modify the codes. 

[Terminal Saved Output.txt](https://github.com/litespeedtech/lsquic/files/5147129/Terminal.Saved.Output.txt)

**Comment by dtikhonov** [comment]
Hmm, you get no packets back and the handshake times out in 10 seconds.  I am guessing something is going on with your network, then?  www.facebook.com should respond to ID-29. Can you access other IETF or Google QUIC servers using lsquic or other clients?

(Also, `-t` takes an argument)

**Comment by yc1997427** [comment]
I agree, might be our network's problem. Accessing google also not working, I know google only opens quic protocol with a limited amount of IP addresses. Not sure if that's also the case with Facebook. Our experiement will run at a closed experiment, won't need to access to external network, so this is not an issue. I'll start to modify the codes of http_client and server to make them run on closed enviroment, or re-write new ones.

**Comment by dtikhonov** [comment]
> I know google only opens quic protocol with a limited amount of IP addresses.

That's not correct.  QUIC is widely used by Chrome.

**Comment by yc1997427** [comment]
Indeed. I think some IPs request via QUIC but will be forced to switched to TCP...case like that happened to us before.

**Comment by yc1997427** [comment]
And I have to say thank you for this great repo, codes are very well written, it also has a very helpful doc and tutorial. I wish more repos will be done like yours. Thanks a lot.

**Comment by dtikhonov** [comment]
You are very welcome! :slightly_smiling_face:
