### ISSUE TITLE
gitignore is missing a tonne of stuff

### ISSUE THREAD

**Issue by AeroNotix** [litespeedtech/lsquic#149]
It's not a huge issue but I am wondering why the .gitignore is not ignoring the build output such as all the test binaries, etc.

If there's a reason you want them outside of gitignore, but not in the repo - I'd be interested to hear.

**Comment by dtikhonov** [comment]
I glanced at the "gitignore" man page, but I can't say I understand its purpose.  `git` does not do anything with files one hasn't added via `git add`.  So it already does the right thing, no?

**Comment by AeroNotix** [comment]
Well, it's just tidy if we ignore things never intended to be added to the repository. When you build/test the repository there are a lot of files which clutter the git status output. Having those files ignored explicitly make it easier to develop in the repository and also make it impossible to accidentally commit something unintended.

**Comment by dtikhonov** [comment]
Oh, it's for `git status`!  I never use `git status`, I get by with `git diff`.

One can't accidentally commit a file he hasn't added, so I don't see how it's a problem.
