### ISSUE TITLE
Minimal example without libevent

### ISSUE THREAD

**Issue by AeroNotix** [litespeedtech/lsquic#150]
Hi,

Is there any example code which does not use libevent? I'm not wanting to include that library and am attempting to wrap lsquic from other languages where mechanisms could be handled more simply compared to libevent.

**Comment by AeroNotix** [comment]
Is it simply enough to call `lsquic_engine_process_conns` in a separate thread over and over for example, making use of `lsquic_engine_earliest_adv_tick` along the way?

**Comment by dtikhonov** [comment]
Have a look at [lsquic-tutorial](https://github.com/dtikhonov/lsquic-tutorial).  That one uses libev.

As for simply calling `lsquic_engine_process_conns()` is a loop: yeah, it will work.  You won't get the performance you would if you called it at correct times, but it should function.

If you use the library from different threads, you have to do your own locking.

**Comment by AeroNotix** [comment]
Is there documentation on what exactly needs to be locked, or is it just every invocation of every function which uses a particular engine needs locking around that call?

**Comment by dtikhonov** [comment]
There are also [slides](https://github.com/dtikhonov/talks/tree/master/netdev-0x14) to go with the tutorial.

I believe you'd have to have a lock per engine and lock on each call.

**Comment by AeroNotix** [comment]
Thanks! The attempt I am trying to do is bind this for use with various languages, all private projects so far but hoping to open source once they get usable. Starting with Lisp.

**Comment by dtikhonov** [comment]
That's quite an undertaking!  And using Lisp, no less.  Good luck: we'll be interested to learn of your progress.

There is already a [Crystal binding](https://github.com/iv-org/lsquic.cr) for lsquic.
