### ISSUE TITLE
congestion algorithm in quic

### ISSUE THREAD

**Issue by joho-lab** [litespeedtech/lsquic#151]
is it support a hybla congestion algorithm

and how I can modify to support it

**Comment by dtikhonov** [comment]
No, lsquic does not support Hybla.

To add support for it, you have to write a new congestion controller.  The congestion controller interface is defined in file `lsquic_cong_ctl.h`.  The controller's methods are used by the send controller: see file `lsquic_send_ctl.c`.

Currently, two congestion controllers are implemented: Cubic and BBR.  Use them as an example.

**Comment by joho-lab** [comment]
> 
> 
> No, lsquic does not support Hybla.
> 
> To add support for it, you have to write a new congestion controller. The congestion controller interface is defined in file `lsquic_cong_ctl.h`. The controller's methods are used by the send controller: see file `lsquic_send_ctl.c`.
> 
> Currently, two congestion controllers are implemented: Cubic and BBR. Use them as an example.

Thanks for response, it was helpful :) 

but do you know how I can integrate the lsquic packages after modification with OpenLiteSpeed V 1.6.15

**Comment by dtikhonov** [comment]
You would follows the OLS build procedure, it should be somewhere on https://openlitespeed.org

**Comment by joho-lab** [comment]
> 
> 
> You would follows the OLS build procedure, it should be somewhere on https://openlitespeed.org

I meant openlitespeed already has a lsquic with older version, how can I upload a newer version of lsquic in existing openlitespeed 
if I changed the location of shm file in server congiguration > tunning > quic to the newer shm , will it work?

**Comment by litespeedtech** [comment]
You need to rebuild OLS binary from source code, with you updated lsquic lib. Changing configuration wont work.
You can try using https://github.com/litespeedtech/openlitespeed/blob/master/build.sh 
Once you successfully build the stock one, they you update lsquic sub module with your own  modified copy.
