### ISSUE TITLE
Can not get ECT(0), ECT(1) and CE counter value

### ISSUE THREAD

**Issue by Blandine11** [litespeedtech/lsquic#154]
I use the client and server implemented in the tutorial (https://github.com/Blandine11/lsquic-tutorial) on lsquic to test the support of ECN in lsquic.
I enabled the use of ECN in options (-o ecn=1; I added this in tut.c program). I launch the client in a machine and  the server in another one.
On the link between client and server machines, I created congestion and my router is able to mark ECN in IP packet headers.
I launch wireshark 3.2.5 on the server side and I used filter to catch only QUIC's ECN-CE marked packets. 
In wireshark, I get QUIC's ECN-CE marked packets.
In the function  ``lsquic_send_ctl_got_ack`` located at ``src/liblsquic/lsquic_send_ctl.c`` file, I try to print the sum of ECT(0) + ECT(1) + CE ``(const uint64_t sum = acki->ecn_counts[ECN_ECT0]
                           + acki->ecn_counts[ECN_ECT1]
                           + acki->ecn_counts[ECN_CE];``
     ``printf("sum = %"PRIu64, sum);``
But unfortunately the value is 0 after runing the client and server programs.
I also try to print CE number in ack frame (``acki->ecn_counts[ECN_CE]``) or and in ce_counter ( ``ctl->sc_ecn_ce_cnt[pns]``) but the result is also 0.
Can you help me to understand and show me how can I do to have the value of ECN-CE, ECT(0), ECT(1) counters , please ?

Regards

**Comment by dtikhonov** [comment]
First, let's verify that the ACK frame you receive contains ECN counters (there are two types of ACK frames).  You should enable the "event" log level (e.g. `-l event=debug`), it will print ACK frames sent and received.

**Comment by Blandine11** [comment]
I used -l event=debug at client and server side.
At client side I have thise output : 
`` sent packet 0, type Initial, crypto: clear, size 1200, frame types: PADDING CRYPTO, ecn: 2, spin: 0; kp: 0, path: 0, flags: 99082``
``packet in: 0, type: Initial, size: 137; ecn: 0, spin: 0; path: 0``
It seems that received ACK frame does not contains ECN  counters.

**Comment by dtikhonov** [comment]
Look at the server log: does `packet 0` have ECN markings?

**Comment by Blandine11** [comment]
At the server side I have this : 
``packet in: 0, type: Initial, size: 1200; ecn: 0, spin: 0; path: 0``
``sent packet 0, type Initial, crypto: clear, size 137, frame types: CRYPTO, ecn: 2, spin: 0; kp: 0, path: 0, flags: 98831``

**Comment by dtikhonov** [comment]
OK.  We see that the client sent the ECN marking (`ecn: 2`), but when received on the server, the marking was absent (`ecn: 0`).  This means that something between the two endpoints [bleaches](https://tools.ietf.org/html/rfc8087#section-3.5) ECN values.

**Comment by Blandine11** [comment]
I agree with you but when I use wireshark to catch the ECN-ECT(0) at the server side I get some packets ``(from client to server)`` that have ecn:2 value.
It seems that it is lsquic code that can't get the ECN counters blocks fields values in ACK_ECN frames. 
Wireshark print packets with ECN marked that crossed all  equipments between two endpoints.
What do you think ?

**Comment by dtikhonov** [comment]
It's possible.  What's the server OS?

**Comment by Blandine11** [comment]
The OS for client and server are ``ubuntu 16.04 with kernel 4.15.0-112-generic``

**Comment by dtikhonov** [comment]
Should work.  Could you please try running both client and server on a local interface and see whether ECN works?

**Comment by Blandine11** [comment]
I run both in the some machine  but the result remains the same.

**Comment by dtikhonov** [comment]
And you pass `-o ecn=1` on both client and server?

**Comment by Blandine11** [comment]
Le mar. 8 sept. 2020 à 18:01, Dmitri Tikhonov <notifications@github.com> a
écrit :

**Comment by dtikhonov** [comment]
I can reproduce it.  There is a problem -- somewhere -- with the way the tutorial program reads in the ECN value.

**Comment by Blandine11** [comment]
OK. So how can I do to solve the problem?
Can you help me, please ?

**Comment by dtikhonov** [comment]
I fixed the tutorial program -- it was [just an omission](https://github.com/dtikhonov/lsquic-tutorial/commit/683b5401bcef27998c1f436205501bb74a85e938).

Note that you need to use `-p 1` option for ECN to work.

**Comment by Blandine11** [comment]
Thank you !

I tried it and it works !!
I have another question which is, what is the function or the part of the code that manage (reduce)
 the congestion windows when ECN-CE marked ACK_ECN is received by the sender ?

**Comment by dtikhonov** [comment]
It's [here](https://github.com/litespeedtech/lsquic/blob/v2.19.10/src/liblsquic/lsquic_send_ctl.c#L1240):

```c
            if (acki->ecn_counts[ECN_CE] > ctl->sc_ecn_ce_cnt[pns])
            {
                ctl->sc_ecn_ce_cnt[pns] = acki->ecn_counts[ECN_CE];
                if (losses_detected)
                    /* It's either-or.  From [draft-ietf-quic-recovery-29],
                     * Section 7.4:
                     " When a loss or ECN-CE marking is detected [...]
                     */
                    LSQ_DEBUG("ECN-CE marking detected, but loss event already "
                        "accounted for");
                else
                {
                    LSQ_DEBUG("ECN-CE marking detected, issue loss event");
                    send_ctl_loss_event(ctl);
                }
            }
```
