### ISSUE TITLE
How I can make a connection from client

### ISSUE THREAD

**Issue by joho-lab** [litespeedtech/lsquic#155]
Dear,

I try to excute this command:
![First issue](https://user-images.githubusercontent.com/70840991/92487403-dfaa8f80-f1f5-11ea-87d2-cf9c36110a44.png)

but I didn't have any response

I excute it with debug:
![second issue](https://user-images.githubusercontent.com/70840991/92487521-010b7b80-f1f6-11ea-90fc-2f3befb0a9bf.png)

Could you help me please?

**Comment by dtikhonov** [comment]
Is there a QUIC server running at 127.0.0.53:443?

**Comment by dtikhonov** [comment]
Why don't you try this first:

```
./http_client -s www.google.com -p /
```

And, if that works, add more options as you see fit.

**Comment by joho-lab** [comment]
> 
> 
> Why don't you try this first:
> 
> ```
> ./http_client -s www.google.com -p /
> ```
> 
> And, if that works, add more options as you see fit.

I try it but there wasn't any response (no handshake)

**Comment by joho-lab** [comment]
> 
> 
> Is there a QUIC server running at 127.0.0.53:443?

it's google IP address

I got it from nslookup command

**Comment by dtikhonov** [comment]
127.0.0.x is a loopback address...

**Comment by joho-lab** [comment]
I am connecting to internet thru an ethernet cable:
![interfaces issue](https://user-images.githubusercontent.com/70840991/92562555-d580a380-f27e-11ea-8548-416857bbd5a2.png)

Here I am trying to connect with and without identifying ethernet port:
![issue four](https://user-images.githubusercontent.com/70840991/92562641-f943e980-f27e-11ea-8e56-d18668e5f86d.png)
![issue three](https://user-images.githubusercontent.com/70840991/92562647-fb0dad00-f27e-11ea-8f16-9082a2fdd770.png)

**Comment by dtikhonov** [comment]
It has to be something with your network.

The `-s 192.168.1.5` still seems wrong.  That's an internal IP address.
