### ISSUE TITLE
wireshark fail to decrypt message, reporting checksum erro (lsquic-v2.19.10, wireshark-v3.3.0)

### ISSUE THREAD

**Issue by yyu4** [litespeedtech/lsquic#156]
Hi,

I run the v2.19.10 lsquic and analyze by wireshark v3.3.0rc0-1957. By configuring the "TLS pre-master-log file" option to the xxxx.keys file generated by lsquic, some messages can be parsed by other failed with warning of "decryption (checktag) failed: checksum error". 

what is missing in my configuration?

thanks in advance,
-Yi
![Capture](https://user-images.githubusercontent.com/53734352/92546250-b2f18900-f284-11ea-8e9b-24831bdc3349.JPG)

**Comment by dtikhonov** [comment]
Are both endpoints lsquic?  In that case, try turning off the QL loss bits on the command line: `-o ql_bits=0`.

**Comment by yyu4** [comment]
Great, it works. It looks I need to dig into it to know more about lsquic.

Thanks for your timely response and help,
-Yi

**Comment by dtikhonov** [comment]
Great, I am glad it worked.  The QL loss bits is an extension that modifies some of the encryption properties of the QUIC transport layer -- and wireshark does not support that extension.
