### ISSUE TITLE
About using lsquic client with OLS server

### ISSUE THREAD

**Issue by joho-lab** [litespeedtech/lsquic#157]
Dear,

I would ask you if the senario below is possible when using lsquic client:
![Diagram](https://user-images.githubusercontent.com/70840991/92582330-7da36600-f299-11ea-9f75-af659f605a04.jpg)

I want to call vistual host in client that already have been created in OLS server

**Comment by dtikhonov** [comment]
Do you mean, you want to connect to OLS using `http_client`?  Yes, that's possible.
