### ISSUE TITLE
How I can switch from cubic to bbr + Wireshark capture

### ISSUE THREAD

**Issue by joho-lab** [litespeedtech/lsquic#158]
Dear,

I would ask you foe the way to switch from cubic to bbr?

and from where I can open the .key in Wireshark that has the capture logs

**Comment by dtikhonov** [comment]
Please read the output of the help screen (`-h`) to answer the first question.

Read the Wireshark documentation (or use a web search) to answer the second.

**Comment by joho-lab** [comment]
> Please read the output of the help screen (`-h`) to answer the first question.
> 
> Read the Wireshark documentation (or use a web search) to answer the second.

I couldn’t find any information about congestion control in ./client_http -h

And thanks for response

**Comment by dtikhonov** [comment]
I apologize, I forgot it's not in the help screen.  The information you're looking for is in the docs instead, see

https://lsquic.readthedocs.io/en/v2.19.10/apiref.html#c.lsquic_engine_settings.es_cc_algo

**Comment by dtikhonov** [comment]
On the command line, you can `-o cc_algo=$your_preference`

**Comment by joho-lab** [comment]
Thank you very much
