### ISSUE TITLE
Stream-specific context

### ISSUE THREAD

**Issue by AeroNotix** [litespeedtech/lsquic#159]
Hi,

Couple of questions about the API and how to use it. Maybe I am a little confused.

When creating a new stream, if you want context associated with a particular stream you must call `lsquic_conn_set_ctx`, then call, `lsquic_conn_make_stream`.

What I don't understand is, if you globally set the context once - how are you supposed to interleave stream creation? E.g. I want to be able to call the API from multiple threads (with necessary locks). Is this just not supported or am I understanding incorrectly? I want to use the stream_ctx to encode a web request (headers, path, body, etc) but yet it seems I need to set the context, then create a new stream, then process_conns sequentially. Is that how it's supposed to work?

**Comment by dtikhonov** [comment]
To associate context with a particular stream, return it from the "on new stream" callback.

`lsquic_conn_make_stream()` will cause "on new stream" callback to be called at an appropriate point.  (Usually, soon.)

`lsquic_conn_set_ctx()` sets context associated with a connection.  An alternative is to return the new per-connection context from the "on new connection" callback.

This is described [in the docs](https://lsquic.readthedocs.io/en/v2.19.10/apiref.html#stream-callback-interface).  If you think they could use some more clarity, suggestions are welcome!

**Comment by AeroNotix** [comment]
Right I understand that it sets the context for a connection - but it's a workaround for not being able to control the context for a specific stream directly.

Imagine an API where I want to have a http3 client, but wrapping lsquic in such a way where I have functions such as `http3:post`, `http3:get` etc. Each of those calls would eventually want to create its own stream. Each of those calls has its own state. With the current API what I would need to do is either set the context for the connection, overriding the global connection state - meaning the individual higher-level API calls would need to be serialized to the point where I know their underlying `on_new_stream` callbacks have at least been triggered. 

An alternative is to have some safe access to state within the connection object - meaning I need to modify something inside the connection state to have a "queue" of pending requests from the higher level API. Each `on_new_stream` call would take a pending request from the connection context.

These seem like non-ideal workarounds for the lack of the ability to create a new stream with specific state.

E.g. a function such as `lsquic_conn_make_stream_with_context(conn, (void*) ctx)`. This way when the stream's `on_new_stream` callback is fired, the new state is already there and no modification of the connection's context was needed.

**Comment by dtikhonov** [comment]
Yes, of course the trade-off is about who is managing these contexts while stream creation is pending.  lsquic lets the caller do that.  This is how `lsquic_conn_make_stream()` [is implemented](https://github.com/litespeedtech/lsquic/blob/v2.19.10/src/liblsquic/lsquic_full_conn_ietf.c#L7671L7694):

```c
static void
ietf_full_conn_ci_make_stream (struct lsquic_conn *lconn)
{
    struct ietf_full_conn *const conn = (struct ietf_full_conn *) lconn;

    if (handshake_done_or_doing_sess_resume(conn)
        && ietf_full_conn_ci_n_avail_streams(lconn) > 0)
    {
        if (0 != create_bidi_stream_out(conn))
            ABORT_ERROR("could not create new stream: %s", strerror(errno));
    }
    else if (either_side_going_away(conn))
    {
        (void) conn->ifc_enpub->enp_stream_if->on_new_stream(
                                    conn->ifc_enpub->enp_stream_if_ctx, NULL);
        LSQ_DEBUG("going away: no streams will be initiated");
    }
    else
    {
        ++conn->ifc_n_delayed_streams;
        LSQ_DEBUG("delayed stream creation.  Backlog size: %u",
                                                conn->ifc_n_delayed_streams);
    }
}
```

You can see that the queue is nothing more than a counter: `ifc_n_delayed_streams`.

It should be easy to write ta wrapper around `lsquic_conn_make_stream()` to do what you want: save contexts on a queue, which will then be used by `on_new_stream()` to get the next stream context.

**Comment by AeroNotix** [comment]
OK, well that's where I was going to end up if it's not directly supported. That said, do you see value in being able to create a new stream _and_ set the context for it in one call?

**Comment by dtikhonov** [comment]
It would be nice to create the stream and assign the context all in one call, of course.  The question is what happens when creating a stream is not possible.  If lsquic were to manage these contexts, it would have to create its own queue.  Then, what if connection is aborted (or engine is shut down) -- what happens?  Does it mean the caller has to specify a function to free the contexts as well?  You can see how it gets complicated quickly.

The way it's done currently strikes a good balance between flexibility and efficiency.  If the user manages the contexts, he can make all the decisions about how to manage them.

One thing that could perhaps be done differently (looking back) is having this function return a status value to tell which of the three branches above was taken.  As of now, one has to call `lsquic_conn_n_pending_streams()` to find out.

**Comment by AeroNotix** [comment]
I do appreciate what you say about lsquic managing those contexts. That said, it leads to a lot of duplication in client code. I can't imagine wanting to create multiple streams all with the same context. I'm struggling to find a use-case outside of a QUIC connection which is only intended for a single stream, each stream inherently always will want to perform a different request - and therefore needs it's own context.

It seems that if lsquic managed that queue internally, creating a new stream for each one, lsquic would have to require a new callback `lsquic_free_stream_ctx(void*)` or something along those lines, called for each stream context that needs freeing.

**Comment by dtikhonov** [comment]
I don't see how this leads to "a lot of duplication in client code."  What is duplicated?  All that is required is a wrapper function to manage contexts.

Yes, each stream will want its own context -- the responsibility for managing them is up to the user, not the library.  It's one or the other, that code would have to be *somewhere*.  It simply seems cleaner to have the user code do it.

**Comment by AeroNotix** [comment]
OK, I see where you stand on this and that's totally fine with me :+1:
