### ISSUE TITLE
Windows build should use getopt from vcpkg

### ISSUE THREAD

**Issue by amoldeshpande** [litespeedtech/lsquic#160]
I just discovered that this is available.  The only wrinkle is that it only supports dynamic linking, so the default vcpkg triple will have to be changed to x64-windows instead of x64-windows-static.

Might need a bit of testing, but IMO it would be worthwhile to get rid of the old getopt in `wincompat`

**Comment by dtikhonov** [comment]
Thanks for the information.  Indeed, it's better not to ship our own getopt!  We'll take a PR... :slightly_smiling_face:

**Comment by TYoung86** [comment]
The note on the vcpkg for getopt says static linking to it is a violation of the LGPL.

Would the project prefer to keep it's own getopt or just shared link the tests/usages?

It doesn't really affect liblsquic.

**Comment by TYoungSL** [comment]
@litespeedtech good to close since #350 is merged.
