### ISSUE TITLE
Feature: ability to generate custom CIDs

### ISSUE THREAD

**Issue by dtikhonov** [litespeedtech/lsquic#161]
We've been told that it would be nice to be able to generate custom CIDs in order to be able to steer traffic.  Here is how to add something like this to lsquic:

## 1. Add callback to the engine API struct

Add callback to generate CIDs to `struct lsquic_engine_api`:

```c
    void  (*ea_generate_cid)(lsquic_conn_t *, unsigned char *buf, size_t sz);
```

The function can be `void` because it should not fail.  In the worst case, let the user code just fill the buffer with random data.

The first argument is the connection object.  This allows to make decisions based on the connection properties or to get at connection context.

## 2. Copy the callback to the engine "public" struct

Callbacks are normally copied to `struct lsquic_engine_public` when engine in initialized.

## 3. Update places in the code where CIDs are generated

CIDs are generated by calling `lsquic_generate_cid()`.  There are a few places in the code where this function is called.  Note that the custom function should only be called for

1. IETF connections, as in gQUIC, the server does not control the connection ID; and
2. SCID, or Source CIDS -- that's what the peer will place in the packets it sends.

The calls will end up looking something like this:

```c
    if (enpub->enp_settings.es_scid_len)
    {
        if (enpub->enp_generate_cid)
        {
            enpub->enp_generate_cid(&conn->ifc_conn, cce->cce_cid.idbuf, enpub->enp_settings.es_scid_len);
            cce->cce_cid.len = enpub->enp_settings.es_scid_len
        }
        else
            lsquic_generate_cid(&cce->cce_cid, enpub->enp_settings.es_scid_len);
    }
```

Or one can make a wrapper around it.

## 4. Control peer address validation by DCID in mini conn

The spec allows to mark peer address as validated if there are at least 64 bits of entropy in CIDs provided to the peer:

```c
    if (!(conn->imc_flags & IMC_ADDR_VALIDATED))
        imico_maybe_validate_by_dcid(conn, &packet_in->pi_dcid);
```

To adhere to spec, this should be disabled if the custom CIDs contain less entropy than that.  One way to do it is to disable this when a custom CID generator is specified.  A more flexible approach would be to add a setting to `struct lsquic_engine_settings`.

**Comment by dtikhonov** [comment]
cc @victorstewart

**Comment by litespeedtech** [comment]
Merged -- closing the issue.
