### ISSUE TITLE
seems bug in http_client with -n option

### ISSUE THREAD

**Issue by jazune** [litespeedtech/lsquic#162]
[ERROR] engine: cannot have more than one connection on the same port

**Comment by dtikhonov** [comment]
Disable versions Q046 and Q050:

https://github.com/litespeedtech/lsquic/blob/master/include/lsquic.h#L118

In these versions of gQUIC, the server never includes the CID in the packet and so the client cannot distinguish different connections if they are on the same socket.  Now, this is not a problem *for the library itself*, but `http_client` only opens one socket.

**Comment by dtikhonov** [comment]
(You can specify the list of supported versions on the command line, e.g. `-o version=h3-27 -o version=h3-29`)

**Comment by jazune** [comment]
get it
