### ISSUE TITLE
any possibilities of automatic ssl  letsencrypt, and used as a reverse proxy to customized address and port e.g.127.0.0.1:80 

### ISSUE THREAD

**Issue by gitmko0** [litespeedtech/lsquic#163]
any possibilities of automatic ssl  letsencrypt, and used as a reverse proxy to customized address and port e.g.127.0.0.1:8081 etc?

**Comment by dtikhonov** [comment]
Sure -- but you'd have to write it, as it's not the job of the library to do it.
