### ISSUE TITLE
lsquic build error

### ISSUE THREAD

**Issue by prchander** [litespeedtech/lsquic#166]
Hello, I was trying to install lsquic but I am facing an error at the following command "cmake -DBORINGSSL_DIR=$BORINGSSL ."
What does it mean when it said variables are set to "NOTFOUND". 
![image](https://user-images.githubusercontent.com/54725951/94072422-da7f4000-fdb2-11ea-8c62-aea779bcd02e.png)

Thank you

**Comment by dtikhonov** [comment]
Did you compile BoringSSL and set the `BORINGSSL` environment variable to the correct value?

**Comment by prchander** [comment]
I used this command to set the environment variable. BORINGSSL_DIR=$PWD/boringssl

**Comment by dtikhonov** [comment]
I am not sure where you go wrong, but you probably do _somewhere_. You can try following the steps in [travis.yml](../blob/master/.travis.yml) because it certainly [works](https://travis-ci.org/github/litespeedtech/lsquic/jobs/729665398).

**Comment by prchander** [comment]
Thank you for your feedback and I got it working. I have another question. Is it possible to run the example client and server on 2 VM's instead of docker containers?

**Comment by dtikhonov** [comment]
Yes, it's possible.  You can also use just one VM: both client and server can coexist on a single machine.

**Comment by prchander** [comment]
For this test, I would like to use two VM's and is an example server an client code available somewhere so I can build from there? Just something basic so I can see how things flow?

**Comment by dtikhonov** [comment]
Sure.  Just follow the build instructions.

**Comment by prchander** [comment]
I see information on building scripts but is there any documentation for echo server and client?

**Comment by dtikhonov** [comment]
There is the online help via the `-h` command-line option...  All sample programs use share a subset of basic flags.  The echo programs should be easy to figure out how to run.
