### ISSUE TITLE
can lsquic support multi-thread?

### ISSUE THREAD

**Issue by jazune** [litespeedtech/lsquic#167]
It seems that lsquic_hash is not thread safe. I got a crash in insert_compress_certs with more than one threads

**Comment by dtikhonov** [comment]
That's true.  This has been reported in #128.

**Comment by jazune** [comment]
Do you plan to support multi-thread ?  It seems not just one problems in multi-thread。

**Comment by dtikhonov** [comment]
Well, we obviously do not use this in a multi-threaded environment, so we did not pay close attention to it.  If it's not too much trouble, we can fix some trouble spots.

Also, "multi-thread support" means different things to different people.  To me, it means being able to use two instances of lsquic engine in two different threads without them stepping on each other's toes.

Besides the compressed certs, what other pro

**Comment by dtikhonov** [comment]
@jazune, I made a few fixes -- I believe the library is now thread-safe.  Could you please give it a shot?  The changes are on the `202009251152-thread-safety` branch.

**Comment by jazune** [comment]
> @jazune, I made a few fixes -- I believe the library is now thread-safe. Could you please give it a shot? The changes are on the `202009251152-thread-safety` branch.
Great ! I will have a try.
It seems all global variables have the rrisk in multi thread.
Maybe these global variables can set to thread_local

**Comment by dtikhonov** [comment]
Our preference would be to avoid thread-related code in the library if we can avoid it.  Hopefully, just getting rid of global variables (as I've done on this branch) will do the trick.

**Comment by jazune** [comment]
I got a strange question on both the master branch and the thread-safe branch.
With multi thread, In the lsquic_attq.c, I got a crash. But with one thread, it will not crash.
the reason why program crashed is that the content of q->aq_heap[11] was set. (every time is q->aq_heap[11])
If I change the first n from 8 to 1024 or more bigger, program will not crash. This means If not do realloc, It will not crash.
But q->aq_heap is the threads' own variable, so it's very strange.

**Comment by litespeedtech** [comment]
Fixed -- closing.

**Comment by jazune** [comment]
@dtikhonov when will this branch merge to master?

**Comment by dtikhonov** [comment]
It's on master -- the fix is in release 2.20.0.

**Comment by jazune** [comment]
Why are some variables in lsquic uninitialized? You take them all as initial zero. Won't there be any problems here? Of course，it has nothing to do with this subject.

**Comment by dtikhonov** [comment]
Give me an example.

**Comment by jazune** [comment]
static lsquic_server_config_t s_server_config;

**Comment by dtikhonov** [comment]
That's old code now: use latest master.
