### ISSUE TITLE
server delivery size 

### ISSUE THREAD

**Issue by yc1997427** [litespeedtech/lsquic#168]
Hi,

May I ask if -w option is the correct argument to specify the size of data which server deliver to client? I tried it, but seems not working. I run both server and client locally on the same machine. 

Here is the server side output: 
./http_server -s 127.0.0.1:4334  -p / -o version=Q050 -w 10000

23:41:02.784 [NOTICE] Document root is not set: start in Interop Mode
23:41:02.784 [WARN] Not a single service specified.  Use -c option.
23:41:05.745 [WARN] mini-conn: enc hist IKObjJ; User-Agent: lsquic/2.19.7
23:41:05.745 [WARN] [QUIC:281BACA7C1BC696E] mini-conn: destroyed.  Diagnostics: conn flags: 0x420008, mc flags: 0xD0, received: 1, sent: 0, lost: 0, deferred: 0, still-deferred: 0, dropped: 0, in-flight: FFFFFFFFFFFFFFFF, acked: 0, error_code: 0x0, ticks: 1, pack size: 1370, lifetime: 859 usec

**Comment by dtikhonov** [comment]
`-w` is used to test a specific mode of operation: writing to stream outside of the "on write" callback.  This is an advanced usage pattern and is not recommended unless one knows what he is doing.

In the log output above, the warnings are about certificates: not a single certificate is specified.  Without certificates, the server won't be able to create QUIC connections.

**Comment by yc1997427** [comment]
Hi, thank you very much for you reply. All I wanted to do is to specify how large the data server send back to client, like sending 50mb data to client.  I tried to find a parameter to speficy the size, but seems it's not there. 

I tried to use -c to specify the certificate, but got error, and not sure if the domain name is necessary, since all I need is to send data(50mb block) alone. 
 ./http_server -s 127.0.0.1:4334  -p / -o version=Q050 -c www.example.com,/tmp/cert.pem,/tmp/key.pkcs8
12:05:03.952 [ERROR] SSL_CTX_use_certificate_chain_file failed: /tmp/cert.pem

**Comment by dtikhonov** [comment]
The `-p /` flag is used by the client, not the server.  When server is run in the "interop" mode (without `-r`), the client can fetch any size payload by specifying path like this: `-p /2M`.  This will fetch 2-megabyte payload.

You need the domain name for `-c`, otherwise SNI won't work.

**Comment by yc1997427** [comment]
Hi, thanks for your reply. And sorry for late reply, I have been working on something else. The problem I'm having with is that I can't run http-server, always got the error:

./http_server -c www.example.com,fullchain.pem,privkey.pem -s 0.0.0.0:4433 
02:44:13.535 [ERROR] SSL_CTX_use_certificate_chain_file failed: fullchain.pem

Struggling to solve this

**Comment by dtikhonov** [comment]
That means that BoringSSL does not like your certificate for some reason.

**Comment by yc1997427** [comment]
I see, may I ask is there anything I can do to solve this.
