### ISSUE TITLE
Unreliable Datagram Extension to QUIC

### ISSUE THREAD

**Issue by mickel8** [litespeedtech/lsquic#170]
Hi,
did you guys think about adding support for Unreliable Datagram Extension to QUIC specified [here](https://tools.ietf.org/html/draft-ietf-quic-datagram-00)?

If no, are implementations of the above extension welcome?

**Comment by dtikhonov** [comment]
Datagrams are supported:

https://lsquic.readthedocs.io/en/v2.21.0/apiref.html#apiref-datagrams

See [duck_server.c](../blob/master/bin/duck_server.c) and [duck_client.c](../blob/master/bin/duck_client.c) for working examples.

P.S. I am sorry you volunteered too late for this one! :slightly_smiling_face:   If you'd like to add another feature or extension, we'd love to have another contributor!  (If you're looking for ideas, I can give you a couple...)

**Comment by mickel8** [comment]
Ohh, I didn't see it but that's great it is already implemented!

 >P.S. I am sorry you volunteered too late for this one! slightly_smiling_face If you'd like to add another feature or extension, we'd love to have another contributor! (If you're looking for ideas, I can give you a couple...)

Yeah, sure. Actually I am looking for something I can implement :slightly_smiling_face:

**Comment by dtikhonov** [comment]
Here are some large outstanding projects on our TODO list (not in a particular order):

- BBRv2
- HTTP/3 [client support for push promises](https://github.com/litespeedtech/lsquic/blob/master/src/liblsquic/lsquic_full_conn_ietf.c#L91L96)
- Updating [qlog](https://github.com/quiclog/internet-drafts) support to the latest version
- QUIC (and HTTP/3) client support for zero-RTT
- [OpenSSL support](https://github.com/litespeedtech/lsquic/search?q=openssl&type=issues)

If none of these float your boat, there are several interesting QUIC extensions that have been proposed, see [here](https://datatracker.ietf.org/wg/quic/documents/) under section _Related Internet-Drafts_.  (Note that lsquic already implements a few of these; please refer to [our documentation](https://lsquic.readthedocs.io/en/v2.21.0/index.html#features)).

If you want to do something smaller to start with, the code is full of comments with "FIXME", "TODO", or "XXX" markings.  As of today, there are about 90 of these.  You can pick one of them and fix it.

**Comment by mickel8** [comment]
Thanks a lot! 

SSH/QUIC seems to be very interesting and I will probably try to implement it. As far as I know it will not require any changes in QUIC implementation but I will try to use the combination of `LSQUIC` and `OpenSSH`.

**Comment by dtikhonov** [comment]
This sounds very interesting -- and challenging.  Let us know if how it goes!

**Comment by mickel8** [comment]
Hi @dtikhonov,
I have created very basic and limited wrapper over lsquic for usage in elixir. It's available [here](https://github.com/mickel8/ex_quic). It's nothing special but it can communicate with `echo_server` provided with lsquic :smiley:

**Comment by dtikhonov** [comment]
Excellent!
