### ISSUE TITLE
lsquic certificate size 

### ISSUE THREAD

**Issue by prchander** [litespeedtech/lsquic#173]
Hello, this is a question, not an issue. I am able to make successful connections with rsa2048 but with a higher bitesize, I am not able to establish a connection. Is there a size limit defined in lsquic? and if so where is it located?

Thank you

**Comment by dtikhonov** [comment]
Thank you for the bug report!  I have reproduced the issue.  It affects gQUIC versions only; IETF QUIC versions are fine.

**Comment by prchander** [comment]
Thank you for your reply. So how do I use IETF QUIC? I can specify version = Q050 for google QUIC but I do not see the syntax for IETF versions.

**Comment by dtikhonov** [comment]
In `http_client` (I assume you mean `http_client`), you can do `-o version=h3-31` (for example).  Also, if you omit the option altogether, the engine will pick the highest version -- which is also "h3-31".

**Comment by prchander** [comment]
Awesome, so what about using open quantum safe boringssl (https://github.com/open-quantum-safe/boringssl). I was trying to transfer a post-quantum algorithm cert but I get the error "[ERROR] SSL_CTX_use_PrivateKey_file failed". Am I generating the key and cert wrong or is it a transfer size limit?

**Comment by dtikhonov** [comment]
The certificate size bug will be fixed in the next release.

The `SSL_CTX_use_PrivateKey_file` failure is in BoringSSL, it's likely not related to anything lsquic is doing.

**Comment by litespeedtech** [comment]
Fixed in 2.22.0 -- closing.
