### ISSUE TITLE
Connection aborted by TLS handshake failure

### ISSUE THREAD

**Issue by AllenLi65536** [litespeedtech/lsquic#177]
I just updated from 2.19.10 to 2.22.1.

My connection got aborted with TLS handshake failure.
I also tried the example http_client but has the same problem.
The following is from the DEBUG log

8:40:10.217 [DEBUG] [QUIC:5E566CDD0EA78EE2] conn: about to process QUIC_FRAME_CONNECTION_CLOSE frame
08:40:10.217 [DEBUG] [QUIC:5E566CDD0EA78EE2] event: CONNECTION_CLOSE frame in: error code 10, reason: 28:TLS handshake failure (ENCRYPTION_INITIAL) 120: no application protocol
08:40:10.217 [INFO] [QUIC:5E566CDD0EA78EE2] conn: Received CONNECTION_CLOSE frame (transport-level code: 10; reason: 28:TLS handshake failure (ENCRYPTION_INITIAL) 120: no application protocol)
08:40:10.217 [DEBUG] [QUIC:5E566CDD0EA78EE2] qlog: [2535798014,"TRANSPORT","PACKET_RX","LINE",{"raw":"c7ff00001d085e566cdd0ea78ee2080f7e5bc15a3560070040658245db4563...","header":{"type":"Initial","payload_length":"111","packet_number":"1"},"frames":[{"frame_type":"ACK"},{"frame_type":"CONNECTION_CLOSE"}]}]

**Comment by dtikhonov** [comment]
The problem is likely that version ID-31 is now used by default -- as opposed to ID-29 in version 2.19.x.  You can specify version [programmatically](https://lsquic.readthedocs.io/en/latest/tutorial.html#specifying-quic-version) or on the command line (`http_client -o version=h3-29 ...`).

**Comment by AllenLi65536** [comment]
Thanks! Now it works!
