### ISSUE TITLE
memory leak in shi_insert

### ISSUE THREAD

**Issue by jazune** [litespeedtech/lsquic#178]
void *scfg_key = strdup(SERVER_SCFG_KEY);
    shi->shi_insert(shi_ctx, scfg_key, SERVER_SCFG_KEY_SIZE,
            s_server_config.lsc_scfg, server_config_sz, t + settings->es_sttl);

    ret = shi->shi_lookup(shi_ctx, scfg_key, SERVER_SCFG_KEY_SIZE,
                          &scfg_ptr, &real_len);

It seems memory leak in scfg_key, scfg_key is a duplicate string, but will not be released.
As an api, scfg_key should not be released in application code. If  application code released it in shi_insert function， it will crashed in shi_lookup because shi_lookup will use it later.
The same is ture in lsquic_tokgen.c

@dtikhonov

**Comment by dtikhonov** [comment]
The shared hash interface is somewhat unusual -- and perhaps it could be documented better, but there is no leak.  The ownership of the second argument to `shi_insert()` is transferred to the `shi` implementation; it is to be freed when the element is deleted.

A sample implementation of this is in [lsquic_stock_shi.c](https://github.com/litespeedtech/lsquic/blob/v2.23.3/src/liblsquic/lsquic_stock_shi.c).  It is tested in [test_shi.c](https://github.com/litespeedtech/lsquic/blob/v2.23.3/tests/test_shi.c).  You can see that there is no leak.
