### ISSUE TITLE
API for setting different SSL configuration on the client side.

### ISSUE THREAD

**Issue by sumasrao** [litespeedtech/lsquic#181]
Hi, 

Is there a way to set a different SSL configuration for the lsquic client? The client SSL CTX is initialized in lsquic_enc_sess_ietf.c -> init_client(). On the server side the callbacks enable us to set different SSL CTX.

Also, Does BoringSSL allow configuring specific ciphers? The lsquic client always sends the default list of 3 ciphers and the lsquic server picks TLS_AES_128_GCM_SHA256. I am trying to see if there is a way to set a different cipher.

Thanks.

**Comment by dtikhonov** [comment]
1. No, there is no way at the moment to pass a different SSL_CTX via a callback for the client.  We'd consider a PR that does it.
1. I do not think it does.  Check out `ssl_write_client_cipher_list()` in _ssl/handshake_client.cc_

**Comment by sumasrao** [comment]
Ok Thanks. I will look into the implementation for the client API.
