### ISSUE TITLE
Enquiring for the GCC version required for building the project

### ISSUE THREAD

**Issue by Shilpa-Rani** [litespeedtech/lsquic#182]
We have been trying to build the boringssl project to build lsquic. 
Is there any particular version of GCC that is required for the same?
(The current GCC version is gcc (GCC) 4.8.5 20150623 and we are using a CentOS platform(Red Hat 4.8.5-39))

-- Checking for module 'libunwind-generic'
--   No package 'libunwind-generic' found
libunwind not found. Disabling unwind tests.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/shilpar2/redis-shilpa/boringssl
[  1%] Built target crypto_test_data
[  1%] Built target boringssl_gtest
[  1%] Built target global_target
[  2%] Built target test_support_lib
[ 10%] Built target fipsmodule
[ 63%] Built target crypto
[ 63%] Built target boringssl_gtest_main
[ 63%] Building CXX object crypto/CMakeFiles/crypto_test.dir/trust_token/trust_token_test.cc.o
/home/shilpar2/redis-shilpa/boringssl/crypto/trust_token/trust_token_test.cc: In constructor ‘bssl::{anonymous}::TrustTokenProtocolTestBase::TrustTokenProtocolTestBase(const TRUST_TOKEN_METHOD*)’:
/home/shilpar2/redis-shilpa/boringssl/crypto/trust_token/trust_token_test.cc:138:7: error: declaration of ‘method’ shadows a member of 'this' [-Werror=shadow]
       : method_(method) {}
       ^
/home/shilpar2/redis-shilpa/boringssl/crypto/trust_token/trust_token_test.cc: In member function ‘virtual void bssl::{anonymous}::TrustTokenMetadataTest_TruncatedProof_Test::TestBody()’:
/home/shilpar2/redis-shilpa/boringssl/crypto/trust_token/trust_token_test.cc:616:12: error: declaration of ‘public_metadata’ shadows a member of 'this' [-Werror=shadow]
   uint32_t public_metadata;
            ^
/home/shilpar2/redis-shilpa/boringssl/crypto/trust_token/trust_token_test.cc: In member function ‘virtual void bssl::{anonymous}::TrustTokenMetadataTest_ExcessDataProof_Test::TestBody()’:
/home/shilpar2/redis-shilpa/boringssl/crypto/trust_token/trust_token_test.cc:676:12: error: declaration of ‘public_metadata’ shadows a member of 'this' [-Werror=shadow]
   uint32_t public_metadata;
            ^
cc1plus: all warnings being treated as errors
make[2]: *** [crypto/CMakeFiles/crypto_test.dir/trust_token/trust_token_test.cc.o] Error 1
make[1]: *** [crypto/CMakeFiles/crypto_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by dtikhonov** [comment]
You may need a newer version of gcc.  BoringSSL likely uses some new C++ features that gcc 4.8.5 does not support.
