### ISSUE TITLE
Instructions in documentation for packet decoding in Wireshark 

### ISSUE THREAD

**Issue by mickel8** [litespeedtech/lsquic#185]
Hi,
what do you think about providing more information about how to set up packet decoding in Wireshark in [Key logging and Wireshark](https://lsquic.readthedocs.io/en/latest/tutorial.html#key-logging-and-wireshark) section in documentation? 

I am testing examples and I had to remove `QUIC` prefix in file containing key logs and set this file in TLS (Pre)-Master-Secret log in Wireshark. There is also a nice table with infomration which version of Wireshark supports which QUIC draft. ([link](https://github.com/quicwg/base-drafts/wiki/Tools#wireshark)) 
It would be really nice to include the above in documentation. If you think it's a good idea I can make a PR.

**Comment by dtikhonov** [comment]
Thanks for pointing it out, we'll fix the example programs.

Where would you recommend we place the documentation?  (Also, we take PRs!)

**Comment by litespeedtech** [comment]
Fixed in 2.24.0 -- closing.
