### ISSUE TITLE
No packet header encryption

### ISSUE THREAD

**Issue by simonasmulevicius** [litespeedtech/lsquic#190]
Good morning, 

I am doing a research project about the QUIC offloading in hardware.
For this reason, I would like to be able to see packet numbers (in hardware).
However, I know that multiple implementations of QUIC usually encrypt packet headers.
Hence, I wonder if this implementation of QUIC has an API to turn off packet header encryption mechanism.

Kind regards, 
Simonas

**Comment by dtikhonov** [comment]
Hello Simonas.  No, no such API (or functionality) exists in lsquic.
