### ISSUE TITLE
chromium quic_client visit lsquic http_server: Bad original_connection_id

### ISSUE THREAD

**Issue by jazune** [litespeedtech/lsquic#191]
I use chromium quic_client to visit lsquic http_server with h3-27, and I got the result:
 IETF_QUIC_PROTOCOL_VIOLATION Bad original_connection_id: did not receive RETRY but received fc161c9ba10f3a05

I found that lsquic server will send quic_transport_parameter  original_connection_id during the handshake no mater whether the handshake sent retry packet，and  this cause  chromium client report error。

It seems that the h3-27 do not limit to this, but chrome has a large market share，will lsquic be compatible with it ？

**Comment by dtikhonov** [comment]
This may be a bug in Chromium.  What version of the Chromium code are you using -- what is the Git revision ID of the Google quiche library?

AFAIK, Chrome will use h3-29 until HTTP/3 RFC is finalized, at which point it will become simply h3.  h3-27 is now pretty old.

**Comment by jazune** [comment]
quiche version is 7f483b5e.

**Comment by dtikhonov** [comment]
That's from May -- this is now quite old.  I tested quic_client with version ed30357616a74eb59b1f99d7bfad9a28f699a6b3 (October 15) and h3-27 works fine.
