### ISSUE TITLE
Migrate connections between engines

### ISSUE THREAD

**Issue by jazune** [litespeedtech/lsquic#192]
Is there any method to migrate connections context info between engines for multi-process program or multi-thread program？
I'm curious how litespeed do it with lsquic since litespeed web server is a multi-process program。

**Comment by dtikhonov** [comment]
We do it using [shared memory](https://lsquic.readthedocs.io/en/latest/apiref.html#c.lsquic_shared_hash_if).  You can check out [OpenLiteSpeed](https://openlitespeed.org/) to see the details.  (Note that connections are not actually migrated between processes.)

**Comment by jazune** [comment]
Thank you very much for you reply !
