### ISSUE TITLE
Any possibility to automatically use letsencrypt for wildcard domain name detection?

### ISSUE THREAD

**Issue by gitmko0** [litespeedtech/lsquic#193]
Any possibility to automatically use letsencrypt for wildcard domain name detection?

Instead of typing in example.com, it automatically just provide quic for whatever domain name using letsencrypt certbot.

Any examples?

**Comment by dtikhonov** [comment]
You asked for something similar in issue #163.  I am not sure what your request means exactly (I would, of course, be glad to find out more), but from the first glance, it seems to be outside of the scope of the library.
