### ISSUE TITLE
Use liblsquic.so in own program

### ISSUE THREAD

**Issue by robmang** [litespeedtech/lsquic#194]
Hi, thanks for this quic implementation and for the great documentation!

I've have successfully built lsquic on ubuntu as a shared lib (and examples), following the instructions, using cmake.
Now I'm trying to build the example programs on my own (using makefiles) using the shared lib generated from the build: liblsquic.so.

Everything has gone smoothly, including linking the third party libraries as shared libs, except for, I get undefined references of the functions appearing in lsquic_hash.h.

However, when I run: nm -gDC liblsquic.so | grep lsquic_hash_create", for example, I can see the symbols in the shared lib: 
000000000009ba9a T lsquic_hash_create
000000000009b963 T lsquic_hash_create_ext

I was just wondering if you ever use lsquic as a shared lib or if it has been tested?

Thanks for your time.

Regards,

Roberto.

**Comment by robmang** [comment]
Okay so I noticed that lsquic_hash.h was missing:

#ifdef __cplusplus
extern "C" {
#endif

...


#ifdef __cplusplus
}
#endif

I rebuilt the shared library after editing lsquic_hash.h and now I am able to compile duck_server with the shared library.

**Comment by dtikhonov** [comment]
Oh, I see.  It's not part of lsquic API proper -- that's probably why.  You can make a PR if you'd like.
