### ISSUE TITLE
handshake: handshake: error:00000001:invalid library (0):OPENSSL_internal:unknown library

### ISSUE THREAD

**Issue by mickel8** [litespeedtech/lsquic#195]
Hi,
I know this is so dummy question and I am sure it's my fault but I can't manage to solve it. I am trying to write simple client and server. Client will send message and server will print it out. My problem is that I cannot perform handshake and I can't get why. 

The client log output is
```
michal@michal-Latitude-E5450:~/Repos/mt/lsquic-demo$ ./client
Logger initialized
13:47:42.119 [DEBUG] tokgen: TOKGEN2 does not exist: generate
13:47:42.119 [INFO] tokgen: inserted TOKGEN2 of size 110
13:47:42.119 [DEBUG] tokgen: initialized
13:47:42.119 [INFO] engine: instantiated engine
13:47:42.119 [DEBUG] engine: grew heaps to 4 elements
13:47:42.119 [DEBUG] conn: generated and assigned SCID 03D6EB9FCDF5BFD1
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] bw-sampler: init
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] bbr: initialized
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] cubic: lsquic_cubic_init(cubic, $conn)
13:47:42.119 [INFO] [QUIC:03D6EB9FCDF5BFD1] cubic: initialized
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] adaptive-cc: initialized
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] cfcw: recv_off changed: read_off: 0; recv_off: 15728640
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] handshake: created client, DCID: D6C808483EFC4A171C864BFD17DDCAF009
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] handshake: Create new SSL_CTX
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] handshake: generated transport parameters buffer of 55 bytes
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] handshake: max_idle_timeout: 30000; init_max_data: 15728640; init_max_stream_data_bidi_local: 6291456; init_max_stream_data_bidi_remote: 0; init_max_stream_data_uni: 32768; init_max_streams_bidi: 100; init_max_streams_uni: 100; ack_delay_exponent: 3; max_ack_delay: 25; active_connection_id_limit: 8; timestamps: 2; loss_bits: 1; initial_source_connection_id: 03D6EB9FCDF5BFD1
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1-18446744073709551615] di: initialized
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1-18446744073709551615] sfcw: recv_off changed: read_off: 0; recv_off: 16384
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1-18446744073709551615] stream: created crypto stream
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1-18446744073709551615] stream: calling on_new_stream
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] sendctl: send_ctl_can_send: n_out: 0 (unacked_all: 0); cwnd: 46720
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] pacer: lsquic_pacer_can_schedule: 1
13:47:42.119 [DEBUG] engine: incref conn 03D6EB9FCDF5BFD1, '' -> 'T'
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] handshake: handshake stream created successfully
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] conn: negotiating version FF000020
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] conn: logging using client SCID
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] event: connection created
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] qlog: [10569977527,"CONNECTIVITY","NEW_CONNECTION","LINE",{"ip_version":"4","srcip":"127.0.0.1","dstip":"127.0.0.1","srcport":"6555","dstport":"7777"}]
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] event: version negotiation: proposed version FF000020
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] qlog: [10569977539,"CONNECTIVITY","VERNEG","LINE",{"proposed_version":"FF000020"}]
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] conn: record path 0: (127.0.0.1:6555 - 127.0.0.1:7777)
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] conn: spin bit enabled on path 0
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] conn: record new path ID 0
On new connection
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] conn: delayed stream creation.  Backlog size: 1
13:47:42.119 [DEBUG] engine: decref conn 03D6EB9FCDF5BFD1, 'HT' -> 'H'
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] pacer: lsquic_pacer_can_schedule: 1
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] sendctl: pacer blocked: 0, in_flight_all: 0
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] handshake: handshake: error:00000001:invalid library (0):OPENSSL_internal:unknown library
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] handshake: handshake failed
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] conn: handshake failed
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] handshake: enc level clear after on_write: stop
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] handshake: Exit shake_stream
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] sendctl: app-limited
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] conn: sit-0 streams: max count: 0; created streams: 0
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] conn: created 0 delayed streams
13:47:42.119 [DEBUG] engine: incref conn 03D6EB9FCDF5BFD1, 'H' -> 'CH'
13:47:42.119 [DEBUG] engine: decref conn 03D6EB9FCDF5BFD1, 'CH' -> 'C'
13:47:42.119 [DEBUG] engine: decref conn 03D6EB9FCDF5BFD1, 'C' -> ''
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] handshake: crypto stream level 0 is closed
13:47:42.119 [DEBUG] [QUIC:03D6EB9FCDF5BFD1-18446744073709551615] sfcw: read_off goes from 0 to 0
13:47:42.120 [DEBUG] [QUIC:03D6EB9FCDF5BFD1-18446744073709551615] stream: destroyed stream
13:47:42.120 [DEBUG] [QUIC:03D6EB9FCDF5BFD1-18446744073709551615] stream: history: [CN320L]
13:47:42.120 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] pacer: scheduled calls: 0
13:47:42.120 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] bw-sampler: cleanup
13:47:42.120 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] bbr: cleanup
13:47:42.120 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] adaptive-cc: cleanup
13:47:42.120 [NOTICE] [QUIC:03D6EB9FCDF5BFD1] sendctl: stats: n_total_sent: 0; n_resent: 0; n_delayed: 0
On connection close
errbuf: 
conn status: LSCONN_ST_HSK_FAILURE
13:47:42.120 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] handshake: iquic_esfi_destroy
13:47:42.120 [DEBUG] [QUIC:03D6EB9FCDF5BFD1] event: full connection destroyed
```

What I am worried about is  `handshake: handshake: error:00000001:invalid library (0):OPENSSL_internal:unknown library`. I am not sure if I am linking library in a proper way. I have also tried to init ssl library with `CRYPTO_library_init` or `OPENSSL_library_init` or something similar but it doesn't help. Also AFAIK this is not needed or at least it should be needed in my case. 

Logs from server are: 
```
Logger initialized
13:47:32.389 [DEBUG] tokgen: TOKGEN2 does not exist: generate
13:47:32.389 [INFO] tokgen: inserted TOKGEN2 of size 110
13:47:32.389 [DEBUG] tokgen: initialized
13:47:32.389 [DEBUG] handshake: generated QUIC server context of 38 bytes for version FF00001B
13:47:32.389 [DEBUG] handshake: max_idle_timeout: 30000; init_max_data: 1572864; init_max_stream_data_bidi_local: 0; init_max_stream_data_bidi_remote: 1048576; init_max_stream_data_uni: 12288; init_max_streams_bidi: 100; init_max_streams_uni: 3; active_connection_id_limit: 8; timestamps: 2
13:47:32.389 [DEBUG] handshake: generated QUIC server context of 38 bytes for version FF00001C
13:47:32.389 [DEBUG] handshake: max_idle_timeout: 30000; init_max_data: 1572864; init_max_stream_data_bidi_local: 0; init_max_stream_data_bidi_remote: 1048576; init_max_stream_data_uni: 12288; init_max_streams_bidi: 100; init_max_streams_uni: 3; active_connection_id_limit: 8; timestamps: 2
13:47:32.389 [INFO] prq: initialized queue of size 10000
13:47:32.389 [INFO] purga: create purgatory, min life 30000000 usec
13:47:32.389 [INFO] engine: instantiated engine
```

It looks like it doesn't event receive anything.

My code is available here https://github.com/qssh-mt/lsquic-demo

I know it isn't complete but I just wanted to test handshake. After this I will try to implement the rest.

I would be so grateful if you could look at it.

**Comment by dtikhonov** [comment]
Yes, it looks like the handshake code fails immediately.  You may indeed be doing something wrong with the library.  I'd use a debugger to see what the library thinks the actual problem is.  (You'd want to recompile BoringSSL with debug symbols.)

I looked at your code *briefly* -- it looks OK.  The example programs bundled with lsquic distribution can be a bit overwhelming.  There are simpler examples you may use for comparison here: https://github.com/dtikhonov/lsquic-tutorial

**Comment by mickel8** [comment]
Thanks a lot I will check it out. Just wanted to make sure it's my fault. Btw. your tutorial and slides look awesome

**Comment by dtikhonov** [comment]
And there is a YouTube video to go with it as well: https://www.youtube.com/watch?v=kDwyGNsQXds

**Comment by mickel8** [comment]
Oh nice, I think it would be nice to link these materials in docs as some sort of Extras or something similar. I have made a small PR (#197) if think it's valuable.

**Comment by mickel8** [comment]
Hi, I have once again stucked in this problem. I have built lsquic and boringssl as shared libraries and the handshake is not able to succeed. Logs are the same as above. 

After some debugging it turned out that the problem is in ALPN in this line: 

https://github.com/google/boringssl/blob/3d8b8c3df27cc780a49607be6a27f2c518f5c082/ssl/t1_lib.cc#L1429

Here is some output from gdb
```c
Thread 2 "client" hit Breakpoint 1, bssl::ext_alpn_add_clienthello (
    hs=0x7fadcc0dff58, out=0x7fadd0e24240)
    at /home/michal/Repos/ex_quic/third_party/boringssl/src/ssl/t1_lib.cc:1427
1427	static bool ext_alpn_add_clienthello(SSL_HANDSHAKE *hs, CBB *out) {
(gdb) n
1428	  SSL *const ssl = hs->ssl;
(gdb) n
1429	  if (hs->config->alpn_client_proto_list.empty() && ssl->quic_method) {
(gdb) n
1431	    OPENSSL_PUT_ERROR(SSL, SSL_R_MISSING_ALPN);
(gdb) n
1432	    return false;
(gdb) 
```


I couldn't find anything in API that will allow me to resolve this problem. I mean there is one callback in engine connected with ALPN but it's optional. 

All tests after building lsquic are passing. 

I am passing `N_LSQVER` as version in `lsquic_connect` but I suppose it's not important, is it?

**Comment by mickel8** [comment]
Some more info.

Setting `.ea_alpn` resolved this problem but the new one appeared. Now my serwer is responsing with CRYPTO_ERROR frame in initial packet. Error code is 376 - `no_appliaction_protocol` from TLS. 

My client sends ClientHello in initial packet with TLS version set to 1.2. I have explicitly set minimal version of server TLS version to 1.2 but it still doesn't work both for QUIC ID-29 and ID-32

**Comment by dtikhonov** [comment]
You aren't using supported version of BoringSSL.  Try with the version listed in the README (or .travis.yml) and see whether that work.

**Comment by mickel8** [comment]
Thanks, now I am using version from travis (`b117a3a0b`) and it still doesn't work. There is still problem with TLS version. Changing QUIC version to ID-27/28/29 also didn't help. I am trying to debug this but  I am running out of ideas. 

Btw. with version `b117a3a0b` of boringssl I still have to set `ea_alpn` and I am not sure if this is desired behaviour.

**Comment by dtikhonov** [comment]
You should not need to use `ea_alpn` if you are using the engine in HTTP mode, so I presume that you are not.  There are two clients in the distribution that set `ea_alpn` (and work, to the best of my knowledge): echo_client.c and md5_client.c.  My advise would be to see how they are implemented and model your own client on them.

**Comment by wangfuyu** [comment]
> You should not need to use `ea_alpn` if you are using the engine in HTTP mode, so I presume that you are not. There are two clients in the distribution that set `ea_alpn` (and work, to the best of my knowledge): echo_client.c and md5_client.c. My advise would be to see how they are implemented and model your own client on them.

I use echo_client to send h3-27 request to a LSENG_SERVER(not LSENG_HTTP_SERVER), and it display the same problem.
![image](https://user-images.githubusercontent.com/12257285/105440903-67270580-5ca2-11eb-9cd4-96fad1e6673e.png)

**Comment by dtikhonov** [comment]
Do you use a shared lsquic library as well, @wangfuyu?  I just tested my setup: echo client and server work.  (I used statically linked programs, though).

Re: Q043: yeah, gQUIC uses a different encryption scheme.

**Comment by wangfuyu** [comment]
> Do you use a shared lsquic library as well, @wangfuyu? I just tested my setup: echo client and server work. (I used statically linked programs, though).
> 
> Re: Q043: yeah, gQUIC uses a different encryption scheme.

Lastest lsquic version, echo_server call an internal api to add alpn and client set ea_alpn, so it can work. But I use version 2.23 have not these code, so it cannot work.

![image](https://user-images.githubusercontent.com/12257285/105461600-6dc87380-5cc8-11eb-9936-66e9bd296229.png)

![image](https://user-images.githubusercontent.com/12257285/105461573-64d7a200-5cc8-11eb-99ab-42d05247e1ef.png)

I have a question: If I run a LSENG_SERVER, how can I make IQUIC work? I can't not found api to add alpn? (add_alpn is not a api in lsquic.h)

**Comment by mickel8** [comment]
I have tested echo client and server with boringssl and lsquic built as shared libraries and they work for me.

My own server and client still have some problems but I almost know why.
I didn't set alpn in engine_api - this was the first thing.
I didn't set callback for alpn for SSL context (I mean `SSL_CTX_set_alpn_select_cb`).
And it seems that I should also set `ea_get_ssl_ctx` for client but I am not sure. I thought it's only needed for server side.
Anyway it's my fault.

**Comment by dtikhonov** [comment]
`ea_get_ssl_ctx` is optional for client (at least for now).

**Comment by litespeedtech** [comment]
> Anyway it's my fault.

Closing.
