### ISSUE TITLE
wrong address copy in ietf_mini_conn_ci_record_addrs and mini_conn_ci_record_addrs

### ISSUE THREAD

**Issue by jazune** [litespeedtech/lsquic#196]
There is something wrong if  source and dest addresses are different sa_family .

**Comment by dtikhonov** [comment]
Probably.  What happens: does the program crash?

Of course, it's one of those things that should "never happen:"  How can peer and local addresses be of different families if they are collected from the same socket?

**Comment by jazune** [comment]
It's possible in some case, this cause the request suspend.

**Comment by dtikhonov** [comment]
I would like to learn more about your use case.  The expected usage is that both local and peer addresses are collected from the same socket and passed to the engine via `lsquic_engine_packet_in()` call.

**Comment by litespeedtech** [comment]
Closed due to lack of response from reporter
