### ISSUE TITLE
lsquic's log show write successful and process_conns has been called but data were drop in the end

### ISSUE THREAD

**Issue by wangfuyu** [litespeedtech/lsquic#199]
![image](https://user-images.githubusercontent.com/12257285/100516610-0dcdb900-31c0-11eb-92b2-816704766019.png)

I'm integrating lsquic into my app,  lsquic's log show lsquic_stream_write successfully and lsquic_engine_process_conns has been called, but data were drop in the end(net idle timeout --> lsquic_engine_process_conns). Has anyone encountered the same problem?   Thanks for your attention!

1. Log key words: lsquic_stream_write  wfy_quic_send_data
[stream_lsquic.log](https://github.com/litespeedtech/lsquic/files/5610649/stream_lsquic.log)

2. tcpdum packets:   quic client: 9.134.127.251 <==Q043==> lsquic proxy server:9.134.118.64  <==TCP==> upstream tcp server:9.134.127.251
[stream_lsquic.tar.gz](https://github.com/litespeedtech/lsquic/files/5610667/stream_lsquic.tar.gz)

NOTES: 
1. This problem only be found if I call lsquic_init_global with LSENG_SERVER.
2. LSENG_HTTP_SERVER has not this problem.
3. lsquic library version: 2.20.0

**Comment by wangfuyu** [comment]
![image](https://user-images.githubusercontent.com/12257285/100517859-de6f7a00-31c8-11eb-80f5-cf0256de3efc.png)

931Bytes were drop after net idle timeout, why it can not be process correctly in the last process conns?

**Comment by dtikhonov** [comment]
The problem here is that you are not [flushing the data](https://lsquic.readthedocs.io/en/latest/tutorial.html?highlight=flush#using-streams):

```
[DEBUG] [QUIC:2A7517AEBD9A3E87-5] stream: buffered 931 bytes; 931 bytes are now in buffer
```

The connection eventually times out because there is nothing to write.  Call either `lsquic_stream_flush()` or `lsquic_stream_shutdown()` or `lsquic_stream_close()` after writing the data.

**Comment by dtikhonov** [comment]
Thinking about this bug report made me realize that if the connection indeed times out (or otherwise closed) while not all stream data is acknowledged after the stream is closed, there is indeed no way for the user to determine that.  This should be the subject of a separate bug.

**Comment by wangfuyu** [comment]
> The problem here is that you are not [flushing the data](https://lsquic.readthedocs.io/en/latest/tutorial.html?highlight=flush#using-streams):
> 
> ```
> [DEBUG] [QUIC:2A7517AEBD9A3E87-5] stream: buffered 931 bytes; 931 bytes are now in buffer
> ```
> 
> The connection eventually times out because there is nothing to write. Call either `lsquic_stream_flush()` or `lsquic_stream_shutdown()` or `lsquic_stream_close()` after writing the data.

I got another problem after I call lsquic_stream_flush in my LSENG_HTTP_SERVER program:
lsquic_stream_write--->lsquic_stream_flush--->lsquic_stream_close, but data not be sent out(packet_out not be called in time), until 15s later on_close.   

log: 2020/12/09 20:11:50 call lsquic_stream_close ---> 2020/12/09 20:12:05 calling on_close

![image](https://user-images.githubusercontent.com/12257285/101631472-55293480-3a5f-11eb-9c70-32c6b59d51ca.png)
![image](https://user-images.githubusercontent.com/12257285/101631509-696d3180-3a5f-11eb-9db6-5c7adccedf96.png)
![image](https://user-images.githubusercontent.com/12257285/101631618-96214900-3a5f-11eb-8761-86abcc2483cd.png)

key_words: lsquic_stream_write  lsquic_stream_close 
[lsquic_error2.log](https://github.com/litespeedtech/lsquic/files/5665907/lsquic_error2.log)

**Comment by dtikhonov** [comment]
You're obviously doing something wrong: 15 seconds is a very long time.  Do you call `lsquic_engine_process_connections()` when needed?  You should consider modeling your program on one of the programs in lsquic distro or in [lsquic-tutorial](https://github.com/dtikhonov/lsquic-tutorial) and make incremental modifications.

**Comment by wangfuyu** [comment]
> distro

I has call lsquic_engine_process_conns and set timer with adv_tick time.
![image](https://user-images.githubusercontent.com/12257285/101737049-4abe7780-3aff-11eb-87a0-91f8201fc811.png)

**Comment by dtikhonov** [comment]
Is this the full log?  There should have been a call to send out packets (at least the packet with stream 5 frame in it), as `lsquic_engine_process_conns()` should have called it.

**Comment by wangfuyu** [comment]
> Is this the full log? There should have been a call to send out packets (at least the packet with stream 5 frame in it), as `lsquic_engine_process_conns()` should have called it.

Sorry, 15s delayed is my programming bug, I use multi engine in my program, but I use the wrong engine while process conns after lsquic_stream_write.

BTW, after I correct my program, I do not need to call lsquic_stream_flush and LSENG_SERVER can work normally.
