### ISSUE TITLE
Detect when not all data has been delivered

### ISSUE THREAD

**Issue by dtikhonov** [litespeedtech/lsquic#200]
There is no way for the user to know when all data sent on a stream has been ACKed by peer.  I think this is a bug in the API.  (See somewhat related issue #199).

As of 2.24.5, `on_close()`  may be called before all data is ACKed.  One way to solve this is to wait to call `on_close()` until either all data is ACKed or connection is destroyed.  In addition, we can add a call like `lsquic_stream_is_all_data_acked()` which could be called from `on_close()`.

**Comment by litespeedtech** [comment]
This has been addressed in release v2.25.0 (see 7f96c7c7f32a3bf2f2c1958fc80836c03b95d90d) -- closing.
