### ISSUE TITLE
Does connection migration only support in ietf conn?

### ISSUE THREAD

**Issue by tk1061178** [litespeedtech/lsquic#206]
Hi, I have found that connection migration is controlled by es_allow_migration.

  /**
     * Allow peer to migrate connection.
     *
     * The default is @ref LSQUIC_DF_ALLOW_MIGRATION
     */
    int             es_allow_migration;

And following this param, I have found that connection migration is only support in lsquic_full_conn_ietf.

So, would you plan to support it in gquic?

**Comment by dtikhonov** [comment]
Connection migration is not supported by the Google QUIC (gQUIC) protocol.  This protocol is expected to be obsoleted by HTTP/3, so no major further development will occur on it.
