### ISSUE TITLE
What is the default QUIC version 

### ISSUE THREAD

**Issue by prchander** [litespeedtech/lsquic#210]
Hello, I was running the http_client script "./http_client -H www.example.com -s 0.0.0.0:4433 -p /". I just want to know what the default QUIC version is because I am able to toggle between the different Google QUIC versions but I am not switch between the different IETF versions. 

Also what is the command for the IETF versions? version=ID-32?

**Comment by dtikhonov** [comment]
The default version is the latest non-experimental version (see the header file).

To select h3-29, use `-o version=h3-29`

**Comment by prchander** [comment]
Thank you for the quick reply. That worked but I have a follow up question. When using Google QUIC, the client side is in a connected loop and the server displays this 
21:12:33.000 [NOTICE] Document root is not set: start in Interop Mode
21:12:38.634 [WARN] mini-conn: enc hist IKObj; User-Agent: lsquic/2.26.1
21:12:38.634 [WARN] [QUIC:A01ECB088B45DAA3] mini-conn: destroyed.  Diagnostics: conn flags: 0x420008, mc flags: 0xD0, incoming-history (trunc: 0) ����U, received: 1, sent: 0, lost: 0, deferred: 0, still-deferred: 0, dropped: 0, in-flight: FFFFFFFFFFFFFFFF, acked: 0, error_code: 0x0, ticks: 1, pack size: 1370, lifetime: 578 usec, version: Q050, mc hist: CSKHe

Is there a way to disable the loop?

**Comment by dtikhonov** [comment]
I cannot reproduce this.  How do you run the client?  (And what do you mean by the "connected loop?")

**Comment by prchander** [comment]
Here is the example I ran: 
With success:
After starting the server, it says:
09:37:04.575 [NOTICE] Document root is not set: start in Interop Mode
Client:
Script: ./http_client -H www.example.com -s 0.0.0.0:4433 -p / -o version=h3-29
and returns 
HTTP/1.1 200 OK
server: lsquic/2.26.1
content-type: text/html
content-length: 940

<html>
   <head>
       <title>LiteSpeed IETF QUIC Server Index Page</title>
   </head>
   <body>
       <h1>LiteSpeed IETF QUIC Server Index Page</h1>
       <p>Hello!  Welcome to the interop.  Available services:
       <ul>
           <li><b>POST to /cgi-bin/md5sum.cgi</b>.  This will return
                   MD5 checksum of the request body.
           <li><b>GET /123K</b> or <b>GET /file-123K</b>.  This will return
                   requested number of payload in the form of repeating text
                   by Jerome K. Jerome.  The size specification must match
                   (\d+)[KMG]? and the total size request must not exceed
                   2 gigabytes.  Then, you will get back that many bytes
                   of the <a
                       href=http://www.gutenberg.org/cache/epub/849/pg849.txt
                                                       >beloved classic</a>.
       </ul>
   </body>
</html>
Time Taken: 
0.018651962280273438

With google QUIC
Server returns 
09:37:04.575 [NOTICE] Document root is not set: start in Interop Mode
09:39:53.645 [WARN] mini-conn: enc hist IKObj; User-Agent: lsquic/2.26.1
09:39:53.645 [WARN] [QUIC:F1D4EB0795C58B95] mini-conn: destroyed.  Diagnostics: conn flags: 0x420008, mc flags: 0xD0, incoming-history (trunc: 0) ؊�grU, received: 1, sent: 0, lost: 0, deferred: 0, still-deferred: 0, dropped: 0, in-flight: FFFFFFFFFFFFFFFF, acked: 0, error_code: 0x0, ticks: 1, pack size: 1370, lifetime: 604 usec, version: Q050, mc hist: CSKHe

client 
Script: ./http_client -H www.example.com -s 0.0.0.0:4433 -p / -o version=Q050
returns 
Time Taken: 
10.005310535430908

Reason I am asking this is because I want to be able to measure time for the two different variants and the Google QUIC version is taking a lot longer than it should.

**Comment by dtikhonov** [comment]
Are you using Linux?  I wonder how you can specify `-s 0.0.0.0:4433` to the client -- I wouldn't expect it to work.

**Comment by prchander** [comment]
I am using Linux. It is not 0.0.0.0 it is an actual IP. Sorry, I know it is an internal IP I guess I am just paranoid.

**Comment by dtikhonov** [comment]
Well, I cannot reproduce what you are seeing.  Could you please specify exact steps?
