### ISSUE TITLE
How to use google chrome browser to access http_server?

### ISSUE THREAD

**Issue by lantiaoxian** [litespeedtech/lsquic#214]
My browser settings enable the quic protocol，andI set the example.org in the hosts file: 192.168.110.51, but https:example.org:443 cannot access http_server

**Comment by dtikhonov** [comment]
Chrome relies on web server's `Alt-Svc` header learn that there is HTTP/3 support before switching to it.  `http_server` is a standalone HTTP/3 server and it does not serve HTTP/1.x or HTTP/2, which the browser could use.

Nevertheless, there are command-line flags you could pass to Chrome to force it to use HTTP/3 for some origins.  IIRC, something like `--origin-to-force-quic-on=example.org` may work.

**Comment by lantiaoxian** [comment]
@dtikhonov thanks，and I would like to ask, what is this command if http_clietn is used to send data? ./http_client -H www.example.org -s 192.168.110.51:443 -p / -S sndbuf="123      This command ？

**Comment by dtikhonov** [comment]
See the `-P` option

**Comment by lantiaoxian** [comment]
thanks
