### ISSUE TITLE
Disable 1-RTT Encryption Transport Parameter

### ISSUE THREAD

**Issue by robmang** [litespeedtech/lsquic#215]
Will you support the disable_1rtt_encryption transport parameter, which can be used to negotiate the disablement of encryption on 1-RTT packets, allowing for reduced CPU load and improved performance, any time soon?

"Post-handshake, packet encryption can occupy a considerable percentage of CPU usage, depending on the scenario. Additionally, there are scenarios where the protections given by this encryption are either unnecessary or unwanted. For these scenarios, [this document](https://tools.ietf.org/id/draft-banks-quic-disable-encryption-00.html) defines an extension to the QUIC protocol to allow for mutually participating endpoints to negotiate the disablement of encryption for the 1-RTT packets sent after the handshake.

Thanks,
Roberto.

**Comment by dtikhonov** [comment]
Hi Roberto,

We have not had a need for this feature and so we do not plan to implement it.  We would, of course, consider a PR if one came along.

**Comment by robmang** [comment]
thanks for your quick reply as always
