### ISSUE TITLE
pfnWSASendMsg only send one iov buffer data（bug in send_packets_one_by_one function）.

### ISSUE THREAD

**Issue by wangweiwei1188** [litespeedtech/lsquic#218]
test_common.c line:1626  code: msg.dwBufferCount  = 1; is error when specs[n] has many iov other than 1.

**Comment by dtikhonov** [comment]
Thanks for reporting this.  We haven't been testing this extensively on Windows, obviously, other than the unit tests on AppVeyor.

Note that this issue is not in the library proper.  Nevertheless, PRs  -- or patches -- are welcome!

**Comment by wangweiwei1188** [comment]
> Thanks for reporting this. We haven't been testing this extensively on Windows, obviously, other than the unit tests on AppVeyor.
> 
> Note that this issue is not in the library proper. Nevertheless, PRs -- or patches -- are welcome!

Ok, I'll fix it.

**Comment by litespeedtech** [comment]
Thank you for the fix!
