### ISSUE TITLE
1-rtt and 0-rtt

### ISSUE THREAD

**Issue by prchander** [litespeedtech/lsquic#222]
This is just a question. I did not see in the documentation how to enable and disable 1-rtt and 0-rtt. I have been saving pcap files for 10 connections and the number of packets for every connection is the same. Is there a way to enable 0rtt?

**Comment by dtikhonov** [comment]
Check out the `-0` flag to `http_client`.  The callbacks and functions involved are described in the [API Reference](https://lsquic.readthedocs.io/en/latest/apiref.html).

**Comment by prchander** [comment]
Just a follow up question. with a -0 flag, what has to be included in the file? Is it the sessions id?
'{lsquic_dir}/build/./http_client -0 text.txt -H www.example.com -s {serverIP}:4433 -p /'

**Comment by dtikhonov** [comment]
You don't have to do anything.  If file does not exist, it's created -- an opaque blob is written to it (via [on_sess_resume_info()](https://lsquic.readthedocs.io/en/latest/apiref.html#c.lsquic_stream_if.on_sess_resume_info)).  If the file exists, the opaque blob is read from it, passed to [lsquic_engine_connect()](https://lsquic.readthedocs.io/en/latest/apiref.html#c.lsquic_engine_connect), and used to resume the session.

**Comment by wangfuyu** [comment]
> You don't have to do anything. If file does not exist, it's created -- an opaque blob is written to it (via [on_sess_resume_info()](https://lsquic.readthedocs.io/en/latest/apiref.html#c.lsquic_stream_if.on_sess_resume_info)). If the file exists, the opaque blob is read from it, passed to [lsquic_engine_connect()](https://lsquic.readthedocs.io/en/latest/apiref.html#c.lsquic_engine_connect), and used to resume the session.

I found -0 flag only work with gquic, can not work with iquic(h3-27 28 29 32), is there anythig I use wrong? Thanks~

**Comment by dtikhonov** [comment]
I see what's going on.  This functionality of `http_client` was broken in 6511378725038493b78762327b07a4890cf8abbc, as we plan to make `ea_get_ssl_ctx` a mandatory callback for the client as well.  We thus broke the `-0` functionality for IETF QUIC connection inadvertently.  We will fix it!

In the meantime, applying the following patch should get it working for you:

```patch
--- a/bin/prog.c
+++ b/bin/prog.c
@@ -82,7 +82,7 @@ prog_init (struct prog *prog, unsigned flags,
                                     = prog;
     prog->prog_api.ea_pmi           = &pmi;
     prog->prog_api.ea_pmi_ctx       = &prog->prog_pba;
-    prog->prog_api.ea_get_ssl_ctx   = get_ssl_ctx;
+    prog->prog_api.ea_get_ssl_ctx   = flags & LSENG_SERVER ? get_ssl_ctx : NULL;
 #if LSQUIC_PREFERRED_ADDR
     if (getenv("LSQUIC_PREFERRED_ADDR4") || getenv("LSQUIC_PREFERRED_ADDR6"))
         prog->prog_flags |= PROG_SEARCH_ADDRS;
```

**Comment by prchander** [comment]
Thank you for the clarification. Do I even need to give it a file after the -0 then?

**Comment by wangfuyu** [comment]
> Thank you for the clarification. Do I even need to give it a file after the -0 then?

Yes, like: -0 prog_0rtt.info

**Comment by litespeedtech** [comment]
The -0 functionality of the demo client has been restored in 2.28.0.  Closing bug.
