### ISSUE TITLE
LSQUIC send different errno to peer between gquic and iquic while IDLE timeout

### ISSUE THREAD

**Issue by wangfuyu** [litespeedtech/lsquic#224]
LSQUIC generate connection close packet fill errno with different value for gquic and iquic while IDLE(noprogress_timeout), is there any special reason?

1) GQUIC:  fill errno with fixed value 16(PEER_GOING_AWAY)
2) IQUIC: fill errno with fixed value 0(EC_NO_ERROR)

GQUIC:
![image](https://user-images.githubusercontent.com/12257285/106279055-cbcffa80-6276-11eb-9a22-13181f015a48.png)

IQUIC:
![image](https://user-images.githubusercontent.com/12257285/106280049-57965680-6278-11eb-9b94-b496aaffe4fc.png)

**Comment by dtikhonov** [comment]
gQUIC and IETF QUIC are different protocols.  As such, they have different error codes.

**Comment by wangfuyu** [comment]
I have another question:
QUIC connection idle timeout can be controled by es_idle_conn_to/es_idle_timeout. Why we need option noprogess_timeout? Could you tell me why we add noprogress_timeout to lsquic? Thanks. 

Reference commit: 
![image](https://user-images.githubusercontent.com/12257285/106358835-99db9880-6349-11eb-94f6-67cbfc54d828.png)

**Comment by dtikhonov** [comment]
This is a security measure to prevent Slowloris type of attacks.
