### ISSUE TITLE
STTL inconsistent with SCFG->EXPY

### ISSUE THREAD

**Issue by wangfuyu** [litespeedtech/lsquic#226]
In lsquic：
1. scfg->expy = t + settings->es_sttl;
![image](https://user-images.githubusercontent.com/12257285/106601472-a3a60b80-6596-11eb-9fc0-be4b28bfc7e4.png)

2. STTL == settings->es_sttl;
![image](https://user-images.githubusercontent.com/12257285/106601385-8a04c400-6596-11eb-9ce6-f3c9b49d63cd.png)

Now, we assume that SCFG is generated at time TA(0), and es_sttl TDiff(30), then EXPY is TA + TDiff == 30.
At TB(5), server receive a new connection, and it will send this SCFG with EXPY 30 and  STTL 30. 
At TC(33), client send a 0RTT connection to server with this SCFG, because it find that TB + STTL = 35 > 33, So it can use this SCFG. But server find that TC(33) > EXPY(30), reject client.

TAG EXPY: a 64-bit expiry time for the server config in UNIX epoch seconds.
TAG STTL: The duration, in seconds, that the server config is valid for.

Why not send a precise STTL to client? Thanks!

**Comment by dtikhonov** [comment]
Thank you for spotting this -- it is a bug!

**Comment by litespeedtech** [comment]
Fixed in release 2.29.0, closing.
