### ISSUE TITLE
Bandwidth Estimation - Congestion Control

### ISSUE THREAD

**Issue by vanvantong** [litespeedtech/lsquic#232]
Hi alls,

I want to compare the performance of Cubic and BBR related to bandwidth. When I run the experiment with BBR, bandwidth is logged in debug mode. However, it is not logged when I switch to Cubic. 
I want to log bandwidth with rtt and srtt, so I put the equation like below in take_rtt_sample() of lsquic_send_ctl file:

bandwidth = ctl->sc_ci->cci_get_cwnd(CGP(ctl))) / lsquic_rtt_stats_get_srtt(&ctl->sc_conn_pub->rtt_stats);

Is this equation correct? I am not sure that I need to use cwnd/rtt or cwnd/srtt.
Thank you in advance!

Best regards,
Van

**Comment by dtikhonov** [comment]
Look at the Cubic function `lsquic_cubic_pacing_rate()` where bandwidth is estimated.

**Comment by vanvantong** [comment]
Thank you very much!
