### ISSUE TITLE
Throughput of BBR is lower than Cubic with high loss

### ISSUE THREAD

**Issue by vanvantong** [litespeedtech/lsquic#233]
Hi alls,

I evaluate performance of BRR and Cubic in the context of video streaming with lsquic. I set rtt to 100ms. Then I change loss from 0 to 30%. Topo is client-switch-server.
With 0% loss, average throughput of BRR and Cubic are 6.494 and 6.412 mbps. 
When loss is set to 20%, average throughput of BRR and Cubic are 1.349 and 0.391.
When loss is increased to 30%, Cubic outperforms BBR related to average throughput.
When loss is less than 20%, BBR can effectively utilize available bandwidth.

Do anybody know why?
When I see in the source code of bbr, I found this one in _calculate_pacing_rate_() function:

    // Slow the pacing rate in STARTUP by the bytes_lost / CWND.
    if (startup_rate_reduction_multiplier_ != 0
            && has_ever_detected_loss
                && (bbr->bbr_flags & BBR_FLAG_HAS_NON_APP_LIMITED))
    {
        bbr->bbr_pacing_rate = BW_TIMES(&target_rate,
            (1 - (bbr->bbr_startup_bytes_lost
                    * startup_rate_reduction_multiplier_ * 1.0f
                        / bbr->bbr_cwnd_gain)));
        // Ensure the pacing rate doesn't drop below the startup growth target
        // times  the bandwidth estimate.
        if (BW_VALUE(&bbr->bbr_pacing_rate)
                                        < BW_VALUE(&bw) * kStartupGrowthTarget)
            bbr->bbr_pacing_rate = BW_TIMES(&bw, kStartupGrowthTarget);
        return;
    }

When there is loss, pacing rate is reduced by the bytes_lost / CWND. Is it the reason for the performance reduction of BBR?
Thank you in advance!

Best regards,
Van

**Comment by dtikhonov** [comment]
The cut-off at around 20% is an intentional BBR setting: it needs to stop blasting the packets away at some point.  I can't find a reference to where they talk about it in the docs, but the information is out there on the web/newsgropus/YouTube somewhere.

**Comment by vanvantong** [comment]
After I create this issue, I found [some documents](https://www.programmersought.com/article/5915755881/) explaining this. This is due to the pacing gain array [1.25, 0.75, 1, 1, 1, 1, 1, 1] and no consideration of loss signal.
Why don't they change the pacing gain adaptively corresponding to different network conditions?

**Comment by dtikhonov** [comment]
20% is a very high loss ratio.  You should adjust your expectations instead.

**Comment by vanvantong** [comment]
Thank you very much.
