### ISSUE TITLE
Server may send REJ with unexpected CRT to all client which means DOS

### ISSUE THREAD

**Issue by wangfuyu** [litespeedtech/lsquic#234]
#Steps to reproduce:
1) Start lsquic server
2) Send 0rtt request with http_client continually. Like: 
![image](https://user-images.githubusercontent.com/12257285/108596453-1e0cc300-73c0-11eb-8cdd-15a6c81d84c5.png)
3) Restart server(stop && start), but don't stop the script of 2)
4) Send Q043 1RTT request to lsquic server with http_client or quic_client
5) All requests cannot be processed correctly by server, client cannot verify server proof. Because server send a ENTRY_CACHED cert to client, but client cannot find it.

#Phenomenon:
1) http_client <---Q043---> lsquic server:  
http_client -H uu.cc -s 127.0.0.1:3333 -p / -o version=Q043 -L DEBUG
![image](https://user-images.githubusercontent.com/12257285/108596312-23b5d900-73bf-11eb-8ed8-5ab5b7d26c7e.png)

2) quic_client(chromium) <---Q043---> lsquic server
quic_client  --host=127.0.0.1  --port=3333  "https://uu.cc/1KB.txt"  --quic_version=Q043
Failed to connect to 127.0.0.1:3333. Error: QUIC_INVALID_CRYPTO_MESSAGE_PARAMETER

**Comment by wangfuyu** [comment]
I found that if I delete [use cached compressed cert] logic, anything will be OK. I think there are some bug in func lsquic_compress_certs.
![image](https://user-images.githubusercontent.com/12257285/108596662-6d072800-73c1-11eb-86c3-42d64d452025.png)

**Comment by wangfuyu** [comment]
TEMP SOLUTION：

Modify function generate_crt:

FROM: 
ccert = lsquic_compress_certs(crts, crt_num, &hs_ctx->ccs, &hs_ctx->ccrt);

TO:
lsquic_str_t tmp_string = { NULL, 0 };
ccert = lsquic_compress_certs(crts, crt_num, &tmp_string, &tmp_string);

**Comment by dtikhonov** [comment]
Thank you for the detailed report!  We will analyze it shortly.

**Comment by dtikhonov** [comment]
We were able to reproduce it: this is a regression introduced in fbc6cc041376e378e328b095679622e40c001178.  A fix is forthcoming.

**Comment by litespeedtech** [comment]
Fixed in release 2.29.2 -- closing.
