### ISSUE TITLE
Issue using server and client from different releases

### ISSUE THREAD

**Issue by robmang** [litespeedtech/lsquic#235]
Hi,

I've built lsquic for Ubuntu, Windows 64,  ios and android and different combinations of server/client on the different platforms work if I stick to the same release.

If I use a client built from release 2.24.4 and try to connect to a server built from release 2.29.0 (as seen in docs/conf.py) I can never get a successful connection with the server.

I can see the following error in the logs: 05:18:11.367 handshake: cannot open packet #8714: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT when using different versions of lsquic

Surely the release shouldn't matter though.

(I don't use the http mode).

**Comment by dtikhonov** [comment]
Different lsquic release use different _default_ QUIC versions by default.  You can use `-o version=h3-29` (for example) to specify the same version and inter-release and inter-platform operation will work.
