### ISSUE TITLE
What is the purpose of rh_masks used in lsquic_rechist?

### ISSUE THREAD

**Issue by byguess** [litespeedtech/lsquic#240]
Hello,

In `struct lsquic_rechist` , I don't understand the purpose of `rh_masks` . Would you like to tell me what the data structure used in `lsquic_rechist` is? Where can I find some material on this topic?

Thank you.

**Comment by dtikhonov** [comment]
`rh_masks` is an array of bitmasks.  Each bit corresponds to an element of the `rh_elems` array.  When a bit it set, the element is allocated.  When a bit is not the, the element is free.  For example, see how it's used in `rechist_alloc_elem()`.

**Comment by byguess** [comment]
Thank you for your reply. I admire the implementation of `lsquic_rechist` which records packet receiving history. Maybe I can help to add some development manual for this.

**Comment by dtikhonov** [comment]
Thank you for the compliment!  I am glad you like this code.

Documentation PRs are welcome.  I have long wanted to document some of the internals, but haven't gotten around to it.  You could add a section to `docs/devel.rst` and call it "Internal Data Structures" and start with "lsquic_rechist" description.
