### ISSUE TITLE
TLS keys exported using boringssl callback doesn't work in Wireshark

### ISSUE THREAD

**Issue by mickel8** [litespeedtech/lsquic#241]
Hi, exporting keys using `SSL_CTX_set_keylog_callback` works and keys are exported to file but Wireshark can't still decode packets. I am trying to run examples from `bin` directory with `-G .` option. In file I have something like this 
```
CLIENT_HANDSHAKE_TRAFFIC_SECRET a45d0061fb57fcd9dd9e1c6268735f088aa7c1e80a6a9603133a447f9b5be6ea b4a0f49faeeba33200c1a181c28ad9473b58b4ce94c652de9cfc541b9e6e6e92
SERVER_HANDSHAKE_TRAFFIC_SECRET a45d0061fb57fcd9dd9e1c6268735f088aa7c1e80a6a9603133a447f9b5be6ea bf7935441148bf35dd395dd825b122418ce23c9a7cc6d0660ce27545120c60ed
CLIENT_TRAFFIC_SECRET_0 a45d0061fb57fcd9dd9e1c6268735f088aa7c1e80a6a9603133a447f9b5be6ea e35774ab8886dccd1b190d21b4961860de754d5c14ff40dda56e359fd7ab5a91
SERVER_TRAFFIC_SECRET_0 a45d0061fb57fcd9dd9e1c6268735f088aa7c1e80a6a9603133a447f9b5be6ea b52c0cf77807f05bbd499d98da8f49309ac0b4888e7b0bed8e2bcf06bb95f813
EXPORTER_SECRET a45d0061fb57fcd9dd9e1c6268735f088aa7c1e80a6a9603133a447f9b5be6ea 8f06a0608767f65d2d2a1c6bb75015417e09aaac3f56d75c74c22d24641ea940
```
which looks fine but for some reasons Wireshark can't still decode packets.

**Comment by dtikhonov** [comment]
It can't decode _any_ packets?  Are you using the latest and greatest version of Wireshark?  What version of the IETF protocol is used?

**Comment by mickel8** [comment]
Version of Wireshark I use `Version 3.4.0rc1 (Git commit 31cae23f755a)` I can try to update.
Version of QUIC `N_LSQVER`.

After changing QUIC version to `LSQVER_ID29` it works
