### ISSUE TITLE
About genearte gquic sslkey

### ISSUE THREAD

**Issue by lsj9383** [litespeedtech/lsquic#243]
Excuse me, I set the version of connect to LSQVER_043, and specified the sslkey directory with the -G parameter.

In the end, it did not trigger the substitution of sslkey to write files, nor did it generate any sslkey.

Thanks your help.

**Comment by dtikhonov** [comment]
That functionality only exists in IETF QUIC, which uses TLS 1.3.

**Comment by lsj9383** [comment]
Thanks, and so I confuse how to capture GQUIC Datagram to analysis in wireshark.

**Comment by dtikhonov** [comment]
I don't think Wireshark can decrypt Google QUIC packets at all.
