### ISSUE TITLE
JQuic

### ISSUE THREAD

**Issue by LorenzHetterich** [litespeedtech/lsquic#246]
Hi,
We've implemented a Java Project using LSQuic that allows developing proxies, clients and servers.
For this, we provide a precompiled lsquic binary (shared library) directly in our repository ([>>here<<](https://github.com/LorenzHetterich/JQuic))
Is this ok?
Do we need to provide any additional credits?
Cheers,
Sophie & Lorenz

**Comment by dtikhonov** [comment]
This is great to hear -- we love it when people use lsquic and especially when the implement bindings for major programming languages!

The way to credit lsquic is described in the [license](https://github.com/litespeedtech/lsquic/blob/master/LICENSE).  I think placing this file (perhaps named `LICENCE.lsquic` or something like that) into the top level of your repository should suffice.
