### ISSUE TITLE
http_client verify server certificate 

### ISSUE THREAD

**Issue by prchander** [litespeedtech/lsquic#247]
Hello, this is a question. I have 2 vms and they are establishing a connection with http_server and http_server. 
Scripts:
./http_server -c www.example.com,key_crt.pem,key_srv.pem -s {server_ip}:4433 -p /'
./http_client  -H www.example.com -s {serverIP}:4433 -p /'

I realised that the client is not verifying the server certificate with CA certificate. So, I modified the client script to:
./http_client -C key_CA.pem -H www.example.com -s {serverIP}:4433 -p /'

Unfortunately, that did not work as I gave it an invalid CA cert to verify and that also established a connection. Is there another way to verify the server cert on the client side?

**Comment by dtikhonov** [comment]
`-C` takes directory name as argument; see output of `-h`.

**Comment by prchander** [comment]
Yes, so just provide the directory to the CA file?
example 
./http_client -C /path/to/dir key_CA.pem -H www.example.com -s {serverIP}:4433 -p /'    ?

**Comment by prchander** [comment]
Hello, sorry to bother you again. Could I please get an example of verify at client?
