### ISSUE TITLE
xlct tag must not be ignored

### ISSUE THREAD

**Issue by wangfuyu** [litespeedtech/lsquic#249]
Problem:
Client request with 0RTT paras may failed with timeout but not success with 1RTT.

Reproduce:
1) http_client launch 0rtt requests with -0 prog_0rtt.info, like
http_client -H test.com -s 127.0.0.1:3333 -p / -o version=Q043 -n 1 -r 10 -R 1 -0 ./prog_0rtt.info
2) server update CERT
3) http_client launch 0rtt again
4) http_client failed with timeout but not success with 1RTT.

Analysis:
 Lsquic ignore XLCT tag while parse_hs_data and not cmp XLCT with hash(enc_session->cert_ptr)

Fix: take xlct into account while determine_rtt
I have create a PR: https://github.com/litespeedtech/lsquic/pull/248

**Comment by litespeedtech** [comment]
The PR has been merged. Thanks for your contribution.
