### ISSUE TITLE
how to run the demo?

### ISSUE THREAD

**Issue by jialianchen** [litespeedtech/lsquic#250]
i have successfully build the lsquic statically and i have passed all the tests .
but when i followed the guide in https://github.com/litespeedtech/lsquic/blob/master/docs/gettingstarted.rst,
i use 
```
$./http_client -s www.google.com -p / -o version=Q050

bash: ./http_client: No such file or directory
```
so i wonder how to run the demo

**Comment by litespeedtech** [comment]
You need to locate the http_client binary and run that command from that directory.
