### ISSUE TITLE
msquic to conn lsquic

### ISSUE THREAD

**Issue by lantiaoxian** [litespeedtech/lsquic#251]
I want to use the quicsample.exe of msquic under windows as the client to test the lsquic server.

 .\quicsample.exe -client -target:192.168.110.51 4567 -unsecure 

The server has the following problems:
How to solve this problem? Thank you

./echo_server -c www.example.org,server.pem,server.key -s 192.168.110.55:4567 -o version=h3-29 -L Debug 2

Document root is not set: start in Interop Mode01:56:07.620 [DEBUG] tokgen: TOKGEN2 does not exist: generate
01:56:07.620 [INFO] tokgen: inserted TOKGEN2 of size 110
01:56:07.620 [DEBUG] tokgen: initialized
01:56:07.620 [DEBUG] handshake: generated QUIC server context of 56 bytes for version FF00001B
01:56:07.620 [DEBUG] handshake: max_idle_timeout: 30000; init_max_data: 1572864; init_max_stream_data_bidi_local: 0; init_max_stream_data_bidi_remote: 1048576; init_max_stream_data_uni: 12288; init_max_streams_bidi: 100; init_max_streams_uni: 3; active_connection_id_limit: 8; min_ack_delay: 10000; min_ack_delay_02: 10000; timestamps: 2
01:56:07.620 [DEBUG] handshake: generated QUIC server context of 56 bytes for version FF00001C
01:56:07.620 [DEBUG] handshake: max_idle_timeout: 30000; init_max_data: 1572864; init_max_stream_data_bidi_local: 0; init_max_stream_data_bidi_remote: 1048576; init_max_stream_data_uni: 12288; init_max_streams_bidi: 100; init_max_streams_uni: 3; active_connection_id_limit: 8; min_ack_delay: 10000; min_ack_delay_02: 10000; timestamps: 2
01:56:07.620 [INFO] prq: initialized queue of size 10000
01:56:07.620 [INFO] purga: create purgatory, min life 30000000 usec
01:56:07.620 [INFO] engine: instantiated engine
01:56:07.620 [INFO] socket buffer size: 212992 bytes; max # packets is set to 155
01:56:07.620 [DEBUG] local address: 192.168.110.51:4567
01:56:07.620 [DEBUG] entering event loop
entering event loop02:03:19.379 [DEBUG] purga: E0A8F56956DE1FF6 not found
02:03:19.379 [DEBUG] engine: grew heaps to 4 elements
02:03:19.379 [DEBUG] engine: client-supplied version FF00001D is supported
02:03:19.379 [DEBUG] [QUIC:E0A8F56956DE1FF6] mini-conn: recv SCID from client E0A8F56956DE1FF6
02:03:19.379 [DEBUG] [QUIC:E0A8F56956DE1FF6] mini-conn: recv DCID from client 
02:03:19.379 [DEBUG] [QUIC:E0A8F56956DE1FF6] mini-conn: generated SCID E19DBBB8228163F4 at index 1, switching to it
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: created mini connection object 0x563f13f76400; max packet size=1252
02:03:19.379 [DEBUG] engine: incref conn E19DBBB8228163F4, 'H' -> 'HT'
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: connection to 192.168.110.51:4567 from 192.168.120.121:54586
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: strip header protection using mask 7B58748034
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: first packet in Init PNS, packno: 0
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] event: decrypted packet 0
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] event: packet in: 0, type: Initial, size: 1252; ecn: 0, spin: 0; path: 0
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] event: CRYPTO frame in: level 0; offset 0; size 230
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: Got CRYPTO frame for enc level #0
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: for QUIC version FF00001D, ALPN is h3-29
02:03:19.379 [DEBUG] tokgen: generated stateless reset token CE8D957CD957CABA668A9FC6EC340A13 for CID E19DBBB8228163F4
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: generated transport parameters buffer of 98 bytes
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: max_idle_timeout: 30000; init_max_data: 1572864; init_max_stream_data_bidi_local: 0; init_max_stream_data_bidi_remote: 1048576; init_max_stream_data_uni: 12288; init_max_streams_bidi: 100; init_max_streams_uni: 3; ack_delay_exponent: 3; max_ack_delay: 25; active_connection_id_limit: 8; min_ack_delay: 10000; min_ack_delay_02: 10000; timestamps: 2; loss_bits: 1; stateless_reset_token: CE8D957CD957CABA668A9FC6EC340A13; original_destination_connection_id: E0A8F56956DE1FF6; initial_source_connection_id: E19DBBB8228163F4
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: initialized server enc session
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: creating stream on level #0
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: on_new_stream called on level 0
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: dispatch read events on level #0
02:03:19.379 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: provided 230 bytes of 0-level data to SSL
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: 
0000  01 00 00 E2 03 03 5D 31  FF 35 A3 0D FB 66 83 C4  |......]1.5...f..|
0010  01 A4 73 C2 A8 60 4F 14  CD 27 20 0B C0 4B 9D 1F  |..s..`O..' ..K..|
0020  B1 C4 82 CC 05 17 00 00  04 13 02 13 01 01 00 00  |................|
0030  B5 00 2B 00 03 02 03 04  00 0D 00 1A 00 18 08 04  |..+.............|
0040  08 05 08 06 04 01 05 01  02 01 04 03 05 03 02 03  |................|
0050  02 02 06 01 06 03 00 0A  00 08 00 06 00 1D 00 17  |................|
0060  00 18 00 10 00 09 00 07  06 73 61 6D 70 6C 65 00  |.........sample.|
0070  33 00 26 00 24 00 1D 00  20 89 8D 9B BD 7D D1 88  |3.&.$... ....}..|
0080  E5 1F E6 92 32 9C BC 14  B1 1F D5 91 7E 84 01 EF  |....2.......~...|
0090  E5 DF FF 9D BF BA EC 36  0E 00 31 00 00 00 17 00  |.......6..1.....|
00A0  00 FF 01 00 01 00 FF A5  00 36 01 02 43 E8 03 02  |.........6..C...|
00B0  45 C0 04 04 81 00 00 00  05 04 80 00 80 00 06 04  |E...............|
00C0  80 00 80 00 07 04 80 00  80 00 0A 01 08 0B 01 29  |...............)|
00D0  0E 01 04 0F 00 C0 00 00  00 FF 02 DE 1A 02 7E 80  |..............~.|
00E0  00 2D 00 02 01 01                                 |.-..............|

02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: read 230 bytes at offset 230 on enc level 0
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: SNI is not set, but is required in HTTP/3: fail certificate lookup
02:03:19.380 [INFO] [QUIC:E19DBBB8228163F4] handshake: got alert 80
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: got TLS alert 80
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: handshake: error:00000001:invalid library (0):OPENSSL_internal:unknown library
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: handshake failed
02:03:19.380 [INFO] [QUIC:E19DBBB8228163F4] mini-conn: handshake failed
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: enc level clear after on_read: stop
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: Exit shake_stream
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] event: PADDING frame in of 980 bytes
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: queued ACK in Init PNS
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] qlog: [14258152296013,"TRANSPORT","PACKET_RX","LINE",{"raw":"c8ff00001d08e0a8f56956de1ff6000044d25874803426c99d99220c63cea1...","header":{"type":"Initial","payload_length":"1236","packet_number":"0"},"frames":[{"frame_type":"PADDING"},{"frame_type":"CRYPTO"}]}]
02:03:19.380 [DEBUG] engine: decref conn E19DBBB8228163F4, 'HT' -> 'H'
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: imico_bitmask_rechist_next: return [0, 0]
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] event: generated ACK frame: [0-0]
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: wrote ACK frame of size 6 in Init PNS
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: sending CONNECTION_CLOSE, is_app: 0, error code: 336, reason: TLS alert 80
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: will generate 1 CONNECTION_CLOSE frame
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: generated CONNECTION_CLOSE frame
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: Return TICK 3
02:03:19.380 [DEBUG] engine: incref conn E19DBBB8228163F4, 'H' -> 'HO'
02:03:19.380 [DEBUG] engine: incref conn E19DBBB8228163F4, 'HO' -> 'CHO'
02:03:19.380 [DEBUG] engine: decref conn E19DBBB8228163F4, 'CHO' -> 'CO'
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: packet_to_send: 0
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: apply header protection using mask 0497460CE6
02:03:19.380 [DEBUG] engine: batched packet 0 for connection E19DBBB8228163F4
02:03:19.380 [DEBUG] engine: batched all outgoing packets for mini conn E19DBBB8228163F4
02:03:19.380 [DEBUG] engine: packets out returned 1 (out of 1)
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] event: sent packet 0, type Initial, crypto: clear, size 58, frame types: ACK CONNECTION_CLOSE, ecn: 0, spin: 0; kp: 0, path: 0, flags: 98829
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: ietf_mini_conn_ci_packet_sent: packet 0 sent
02:03:19.380 [DEBUG] engine: decref conn E19DBBB8228163F4, 'CO' -> 'C'
02:03:19.380 [DEBUG] engine: send_packets_out: sent 1 packet
02:03:19.380 [DEBUG] engine: decref conn E19DBBB8228163F4, 'C' -> ''
02:03:19.380 [DEBUG] purga: allocated new page
02:03:19.380 [DEBUG] purga: added E0A8F56956DE1FF6 to the set
02:03:19.380 [DEBUG] purga: added E19DBBB8228163F4 to the set
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] handshake: iquic_esfi_destroy
02:03:19.380 [DEBUG] [QUIC:E19DBBB8228163F4] mini-conn: ietf_mini_conn_ci_destroyed
02:03:19.380 [DEBUG] read 1 packet in 1 batch

**Comment by nibanks** [comment]
FYI, quicsample from MsQuic implements a custom protocol/alpn and won't interop with anything without explicit support on the lsquic side. I'd recommend quicinterop instead.
