### ISSUE TITLE
send_ctl_transfer_time may cause SIGFPE because pacing_rate equal zero

### ISSUE THREAD

**Issue by wangfuyu** [litespeedtech/lsquic#254]
If we set es_cc_algo = LSQUIC_DF_CC_ALGO, func send_ctl_transfer_time may happen SIGFPE.

![image](https://user-images.githubusercontent.com/12257285/114031529-0cb74180-98ae-11eb-8a37-6b785571173f.png)

![image](https://user-images.githubusercontent.com/12257285/114032249-b696ce00-98ae-11eb-8434-9e699e56f904.png)

![image](https://user-images.githubusercontent.com/12257285/114032456-e7770300-98ae-11eb-95c9-463e44794774.png)

![image](https://user-images.githubusercontent.com/12257285/114031724-38d2c280-98ae-11eb-86cb-282478548d96.png)

**Comment by wangfuyu** [comment]
I have write a simple program to check "if (acc->acc_flags & ACC_CUBIC)"

![image](https://user-images.githubusercontent.com/12257285/114034100-77697c80-98b0-11eb-9d84-9aa4933c502c.png)

Result:
![image](https://user-images.githubusercontent.com/12257285/114034163-85b79880-98b0-11eb-9608-f8453b3208de.png)

**Comment by litespeedtech** [comment]
How about change `ACC_CUBIC` to
```
    enum {
        ACC_CUBIC = 1,  /* If set, use Cubic; otherwise, use BBR */
    }                       acc_flags;
```
Will it fix the problem?

**Comment by litespeedtech** [comment]
Seems we never update `acc_flags` value, so always use BBR's CWND and pacing rate, regardless how `ACC_CUBIC` was defined.

**Comment by wangfuyu** [comment]
> How about changing `ACC_CUBIC` to
> 
> ```
>     enum {
>         ACC_CUBIC = 1,  /* If set, use Cubic; otherwise, use BBR */
>     }                       acc_flags;
> ```
> 
> Will it fix the problem?

Lsquic has a lot of magic number, I have think this point but I cannot sure it.  pacing_rate == 0 is difficult to be simulated.

**Comment by wangfuyu** [comment]
I think we need to add protect in func lsquic_bbr_pacing_rate

if bw < 8 then return 1 but not 0.

**Comment by litespeedtech** [comment]
Following patch should address that
```
diff --git a/src/liblsquic/lsquic_send_ctl.c b/src/liblsquic/lsquic_send_ctl.c
index ec7332d7..ebeb4914 100644
--- a/src/liblsquic/lsquic_send_ctl.c
+++ b/src/liblsquic/lsquic_send_ctl.c
@@ -545,6 +545,8 @@ send_ctl_transfer_time (void *ctx)
 
     in_recovery = send_ctl_in_recovery(ctl);
     pacing_rate = ctl->sc_ci->cci_pacing_rate(CGP(ctl), in_recovery);
+    if (!pacing_rate)
+        pacing_rate = 1;
     tx_time = (uint64_t) SC_PACK_SIZE(ctl) * 1000000 / pacing_rate;
     return tx_time;
 }
@@ -3814,6 +3816,8 @@ lsquic_send_ctl_can_send_probe (const struct lsquic_send_ctl *ctl,
         if (n_out + path->np_pack_size >= cwnd)
             return 0;
         pacing_rate = ctl->sc_ci->cci_pacing_rate(CGP(ctl), 0);
+        if (!pacing_rate)
+            pacing_rate = 1;
         tx_time = (uint64_t) path->np_pack_size * 1000000 / pacing_rate;
         return lsquic_pacer_can_schedule_probe(&ctl->sc_pacer,
                    ctl->sc_n_scheduled + ctl->sc_n_in_flight_all, tx_time);
```

**Comment by wangfuyu** [comment]
> Following patch should address that
> 
> ```
> diff --git a/src/liblsquic/lsquic_send_ctl.c b/src/liblsquic/lsquic_send_ctl.c
> index ec7332d7..ebeb4914 100644
> --- a/src/liblsquic/lsquic_send_ctl.c
> +++ b/src/liblsquic/lsquic_send_ctl.c
> @@ -545,6 +545,8 @@ send_ctl_transfer_time (void *ctx)
>  
>      in_recovery = send_ctl_in_recovery(ctl);
>      pacing_rate = ctl->sc_ci->cci_pacing_rate(CGP(ctl), in_recovery);
> +    if (!pacing_rate)
> +        pacing_rate = 1;
>      tx_time = (uint64_t) SC_PACK_SIZE(ctl) * 1000000 / pacing_rate;
>      return tx_time;
>  }
> @@ -3814,6 +3816,8 @@ lsquic_send_ctl_can_send_probe (const struct lsquic_send_ctl *ctl,
>          if (n_out + path->np_pack_size >= cwnd)
>              return 0;
>          pacing_rate = ctl->sc_ci->cci_pacing_rate(CGP(ctl), 0);
> +        if (!pacing_rate)
> +            pacing_rate = 1;
>          tx_time = (uint64_t) path->np_pack_size * 1000000 / pacing_rate;
>          return lsquic_pacer_can_schedule_probe(&ctl->sc_pacer,
>                     ctl->sc_n_scheduled + ctl->sc_n_in_flight_all, tx_time);
> ```

I think this patch not the best resolution, it look not graceful enough.

**Comment by litespeedtech** [comment]
While, it is a corner case that we are not likely to see in the real world environment. 
It probably only happens when you pause the application in debugger, which artificially lowered the result of estimated bandwidth. 
And if the real available bandwidth is close to anywhere less than 8 bits per second, the connection is likely dead anyway. 
Our main goal here is to avoid a SIGFPE, anything more than that is just a beat on dead horse to me.

**Comment by litespeedtech** [comment]
And the fix will cover all congestion controls.

**Comment by wangfuyu** [comment]
> While, it is a corner case that we are not likely to see in the real world environment.
> It probably only happens when you pause the application in debugger, which artificially lowered the result of estimated bandwidth.
> And if the real available bandwidth is close to anywhere less than 8 bits per second, the connection is likely dead anyway.
> Our main goal here is to avoid a SIGFPE, anything more than that is just a beat on dead horse to me.

Here bw == 2,  maynot be the real value, we can calculate the true bw == 58400.

cubic->cu_cwnd = 2920;
bandwidth = 2920 * 1000000 / 50000 = 58400;

then 

pacing_rate = 58400 + 58400 / 4 = 73000

**Comment by wangfuyu** [comment]
And this is a real case in Cloud Service.

**Comment by litespeedtech** [comment]
Does it mean that BBR bandwidth estimation is way off to the one from CUBIC? 
We probably need to look into why BBR get bw == 2, while, the real bandwidth is actually much higher?

**Comment by wangfuyu** [comment]
> Does it mean that BBR bandwidth estimation is way off to the one from CUBIC?
> We probably need to look into why BBR get bw == 2, while, the real bandwidth is actually much higher?

Maybe here bbr->bbr_pacing_rate is a random number? 

In this case, es_cc_algo = LSQUIC_DF_CC_ALGO, and it choose CUBIC, but the logic "if (acc->acc_flags & ACC_CUBIC)" cause a wrong condition branch.

**Comment by litespeedtech** [comment]
bbr->bbr_pacing_rate starts from zero, and goes up and down based on probe results. 
adaptive_cc starts with both BBR and CUBIC running, uses BBR result to drive the pacer as default, if TTL is too short (BBR has difficulty to get accurate bandwidth estimation in that case), switch to cubic only.
