### ISSUE TITLE
Func process_streams_read_events may access 0x0 and then SIGSEGV

### ISSUE THREAD

**Issue by wangfuyu** [litespeedtech/lsquic#255]
![image](https://user-images.githubusercontent.com/12257285/114050989-4fcde080-98bf-11eb-8a63-c75a9142fa3d.png)

![image](https://user-images.githubusercontent.com/12257285/114050934-42b0f180-98bf-11eb-9912-79f17b4656ca.png)

I think here need to add NULL check.

**Comment by wangfuyu** [comment]
I cannot understand why here:

#define	TAILQ_LAST(head, headname) \
	(*(((struct headname *)((head)->tqh_last))->tqh_last))

but not

#define	TAILQ_LAST(head, headname)   ((head)->tqh_last))

**Comment by litespeedtech** [comment]
I would not question the correctness of that code, it is in `/usr/include/sys/queue.h` .  :-)
It got to be the way TAILQ is used, causes queue corruption or something.

**Comment by wangfuyu** [comment]
> I would not question the correctness of that code, it is in `/usr/include/sys/queue.h` . :-)
> It got to be the way TAILQ is used, causes queue corruption or something.

Agree.

This problem's backtrace: lsquic_engine_process_conns--->process_connections--->full_conn_ci_tick--->process_streams_read_events and then coredump while TAILQ_LAST(&conn->fc_pub.read_streams, lsquic_streams_tailq), because ((struct lsquic_streams_tailq *)((&conn->fc_pub.read_streams)->tqh_last)) == 0x0

I think lsquic may something wrong in read_streams manager, but I cannot find it out.

**Comment by litespeedtech** [comment]
The queue has corrupted before calling `process_streams_read_events()`.
A non-empty queue, should not have `tqh_last` pointing to a NULL object. 
If this happen frequently, you can add some validation code right after each TAILQ modification to find out when the TAILQ get corrupted.
