### ISSUE TITLE
how to make client to aware the error "client does not support any of the server-specified versions" and whether it is needed?

### ISSUE THREAD

**Issue by initlifeinc** [litespeedtech/lsquic#258]
if client try to connect an old version QUIC server (for example:  only support iQUIC 17), then client QUIC connection will connect failed.  when i try to get close information by invoke   

status = lsquic_conn_status(conn, errmsg, sizeof(errmsg));

Then client only known the status LSCONN_ST_ERROR(many error will be finally treated as LSCONN_ST_ERROR) , even the errmsg has already show the error reason "client does not support any of the server-specified versions", but it seems too ugly by compare error msg to identify this kind of error.

So question is do you think it is needed to distinguish these two errors (normal connection failed error and version negotiation failed error)? 

Because i think this error seems a special error code. 
For example, if an old client try to connect an updated QUIC server, if it found server will never to support old QUIC version which client is supported, then client should not be connect to these QUIC server again in a short time or forever, so that all clients cloud only use the same domain to communicate with QUIC server.
(of cause there maybe have another solution to dispatch packets to different supported servers.)

**Comment by litespeedtech** [comment]
That makes sense. 
Please check the follow patch see if it does what you want or not? 
```
diff --git a/include/lsquic.h b/include/lsquic.h
index ac9cf1a0..8983ac98 100644
--- a/include/lsquic.h
+++ b/include/lsquic.h
@@ -2219,6 +2219,7 @@ enum LSQUIC_CONN_STATUS
     LSCONN_ST_ERROR,
     LSCONN_ST_CLOSED,
     LSCONN_ST_PEER_GOING_AWAY,
+    LSCONN_ST_VERNEG_FAILURE,
 };
 
 enum LSQUIC_CONN_STATUS
diff --git a/src/liblsquic/lsquic_full_conn.c b/src/liblsquic/lsquic_full_conn.c
index c00249c3..e961d9df 100644
--- a/src/liblsquic/lsquic_full_conn.c
+++ b/src/liblsquic/lsquic_full_conn.c
@@ -2285,6 +2285,7 @@ process_ver_neg_packet (struct full_conn *conn, lsquic_packet_in_t *packet_in)
     versions &= conn->fc_ver_neg.vn_supp;
     if (0 == versions)
     {
+        conn->fc_flags |= FC_HSK_FAILED;
         ABORT_ERROR("client does not support any of the server-specified "
                     "versions");
         return;
@@ -4233,7 +4234,12 @@ full_conn_ci_status (struct lsquic_conn *lconn, char *errbuf, size_t bufsz)
     }
 
     if (conn->fc_flags & FC_ERROR)
-        return LSCONN_ST_ERROR;
+    {
+        if (conn->fc_flags & FC_HSK_FAILED)
+            return LSCONN_ST_VERNEG_FAILURE;
+        else
+            return LSCONN_ST_ERROR;
+    }
     if (conn->fc_flags & FC_TIMED_OUT)
         return LSCONN_ST_TIMED_OUT;
     if (conn->fc_flags & FC_ABORTED)
diff --git a/src/liblsquic/lsquic_full_conn_ietf.c b/src/liblsquic/lsquic_full_conn_ietf.c
index ee84ff22..c7008bd4 100644
--- a/src/liblsquic/lsquic_full_conn_ietf.c
+++ b/src/liblsquic/lsquic_full_conn_ietf.c
@@ -7678,7 +7678,7 @@ process_incoming_packet_verneg (struct ietf_full_conn *conn,
          */
         if (!verneg_ok(conn))
         {
-            ABORT_WITH_FLAG(conn, LSQ_LOG_NOTICE, IFC_ERROR,
+            ABORT_WITH_FLAG(conn, LSQ_LOG_NOTICE, IFC_ERROR|IFC_HSK_FAILED,
                 "version negotiation not permitted in this version of QUIC");
             return -1;
         }
@@ -7686,7 +7686,7 @@ process_incoming_packet_verneg (struct ietf_full_conn *conn,
         versions &= conn->ifc_u.cli.ifcli_ver_neg.vn_supp;
         if (0 == versions)
         {
-            ABORT_WITH_FLAG(conn, LSQ_LOG_NOTICE, IFC_ERROR,
+            ABORT_WITH_FLAG(conn, LSQ_LOG_NOTICE, IFC_ERROR|IFC_HSK_FAILED,
                 "client does not support any of the server-specified versions");
             return -1;
         }
@@ -8600,7 +8600,12 @@ ietf_full_conn_ci_status (struct lsquic_conn *lconn, char *errbuf, size_t bufsz)
     }
 
     if (conn->ifc_flags & IFC_ERROR)
-        return LSCONN_ST_ERROR;
+    {
+        if (conn->ifc_flags & IFC_HSK_FAILED)
+            return LSCONN_ST_VERNEG_FAILURE;
+        else
+            return LSCONN_ST_ERROR;
+    }
     if (conn->ifc_flags & IFC_TIMED_OUT)
         return LSCONN_ST_TIMED_OUT;
     if (conn->ifc_flags & IFC_ABORTED)
```

**Comment by initlifeinc** [comment]
I'm a little confused about use IFC_HSK_FAILED error code to identify the  version negotiation error. (it seems this code will appear in some other logic paths)

Of cause if version negotiation is failed, the connection handshake must be failed, but on the other hand，if a connection connect failed, some unexpected error will also make it into IFC_HSK_FAILED status.

and here we first judge whether it is a IFC_ERROR( i am not sure what the definition of IFC_ERROR? it is means all unexpected error?) , then to find whether it is also a ifc_hsk_failed error.

if (conn->ifc_flags & IFC_ERROR)
{
      if (conn->ifc_flags & IFC_HSK_FAILED)
         return LSCONN_ST_VERNEG_FAILURE;
      else
        return LSCONN_ST_ERROR;
}

But it seems still cannot distinguish LSCONN_ST_VERNEG_FAILURE very clearly. In my option, LSCONN_ST_VERNEG_FAILURE is a special error code, the other handshake error should not be treat as LSCONN_ST_VERNEG_FAILURE

 if LSCONN_ST_VERNEG_FAILURE is appeared, client should known it is not client or server fault, both are ok, but these two ends should not work together now. but for other hsk_failed, maybe you try again and it will connect successfully.

I suggest to use  a very clear error code，what do you think?

**Comment by litespeedtech** [comment]
I just use the existing flag bits to archive this. 
If both `IFC_ERROR` and `IFC_HSK_FAILED` bits are set, it is a version negotiation failure. we already running out of those bits. 
before, there will be only one bit set for generic error or real handshake failure. 
It is in 2.30.1 already.

**Comment by initlifeinc** [comment]
OK, got it
