### ISSUE TITLE
lshpack_dec_push_entry MUST remove overflow entries

### ISSUE THREAD

**Issue by wangfuyu** [litespeedtech/lsquic#260]
#Problem
   http_server's hpack decode dynamic table may different with http_client's hpack encode dynamic table.

#Reproduce:
1. http_client send a lots request on one connection with different headers, like:
http_client -H uu.cc -s 127.0.0.1:3333 -p / -o version=Q043 -n 1 -r 100 -R 100 -K
Note: I have changed http_client.c, send request with different header value, like:
![image](https://user-images.githubusercontent.com/12257285/115374999-f12e2e00-a1ff-11eb-844c-5d164b325b7a.png)

2. gdb breakpoint in lshpack_dec_cleanup, we can see like this:
![image](https://user-images.githubusercontent.com/12257285/115375370-4ff3a780-a200-11eb-81a1-eafc917d4968.png)

In lsquic:
1. dec->hpd_max_capacity is 4096(RFC 7540 default value)
2. dec->hpd_cur_max_capacity is 4096

#Resolution:
lshpack_dec_push_entry remove overflow entries.

**Comment by litespeedtech** [comment]
Thanks. It looks like a bug in ls-hpack, missed the logic to maintain the size of dynamic table. will have it fixed in the ls-hpack repo.

**Comment by litespeedtech** [comment]
Can you please try this patch see if it helps or not?
https://github.com/litespeedtech/ls-hpack/commit/1b7a5c30a91a6d90dba9e78cb448065c332c541e

**Comment by wangfuyu** [comment]
> Can you please try this patch see if it helps or not?
> [litespeedtech/ls-hpack@1b7a5c3](https://github.com/litespeedtech/ls-hpack/commit/1b7a5c30a91a6d90dba9e78cb448065c332c541e)

This patch can resolve this defect. But I think there are some other logic need to be optimized.

1) If lsquic receive a big indexed header, then it should check and adjust the dec dynamic table first.
2) If new header size is larger than capacity, then it should not to lshpack_arr_push.

**Comment by litespeedtech** [comment]
It is not the decision of the decoder to put an entry in the dynamic table or not. 
it must exactly matches the encoder's table, otherwise, there will be a decoding failure.

**Comment by wangfuyu** [comment]
> It is not the decision of the decoder to put an entry in the dynamic table or not.
> it must exactly matches the encoder's table, otherwise, there will be a decoding failure.

I understand this point, and I means that:
1) dec dynamic table can be cleanup before  lshpack_arr_push
2) if client send a LSHPACK_ADD_INDEX header, but its size is larger than  dec->hpd_cur_max_capacity, then we should consider it as PROTOCOL_ERROR.

**Comment by wangfuyu** [comment]
> Can you please try this patch see if it helps or not?
> [litespeedtech/ls-hpack@1b7a5c3](https://github.com/litespeedtech/ls-hpack/commit/1b7a5c30a91a6d90dba9e78cb448065c332c541e)

This patch have another bug, can not be released.


./http_client -H uu.cc -s 9.134.118.64:3333 -p / -o version=Q043 -n 1 -r 2 -R 2
![image](https://user-images.githubusercontent.com/12257285/115729692-35fcc500-a3b8-11eb-80c7-3f52b6db49d7.png)

**Comment by wangfuyu** [comment]
> > Can you please try this patch see if it helps or not?
> > [litespeedtech/ls-hpack@1b7a5c3](https://github.com/litespeedtech/ls-hpack/commit/1b7a5c30a91a6d90dba9e78cb448065c332c541e)
> 
> Does following message normal?
> 
> ./http_client -H uu.cc -s 9.134.118.64:3333 -p / -o version=Q043 -n 1 -r 2 -R 2
> ![image](https://user-images.githubusercontent.com/12257285/115729692-35fcc500-a3b8-11eb-80c7-3f52b6db49d7.png)

Ignore this. Effective elements is [off, off+nelem]

**Comment by litespeedtech** [comment]
> 1. dec dynamic table can be cleanup before  lshpack_arr_push
It has minimum impact.
> 2. if client send a LSHPACK_ADD_INDEX header, but its size is larger than  dec->hpd_cur_max_capacity, then we should consider it as PROTOCOL_ERROR.
This is a rare case, and the encoder should avoid doing that.
