### ISSUE TITLE
assert(lsquic_packet_out_pns(packet_out) == pns) crashed

### ISSUE THREAD

**Issue by jazune** [litespeedtech/lsquic#261]
Hi, I got a crash in pns assert below. (lsquic_mini_conn_ietf.c  imico_process_ack_frame  version:2.27.3)

![image](https://user-images.githubusercontent.com/9442957/115985197-4a6dd700-a5dd-11eb-9386-6394b3f97b87.png)

here is stack value
![image](https://user-images.githubusercontent.com/9442957/115985183-417d0580-a5dd-11eb-912a-845bd72508e5.png)

why there is a assert here? client can send any packet if it want. 
It's going to be attacked here..

**Comment by jazune** [comment]
@litespeedtech  Is it a bug ?

**Comment by litespeedtech** [comment]
assert() is used throughout the code to guard against things should not happened. 
You need a better understanding of the code before making protocol level modifications.
