### ISSUE TITLE
md5_client -b mode error?

### ISSUE THREAD

**Issue by muyiwq** [litespeedtech/lsquic#264]
./md5_client -s 127.1:12345 -f echo_client -f echo_server -b. In parameter -b mode, no matter you specify 1 or more files, the first file always reports an error, lsquic_stream_read: Connection reset by peer, I should How to solve this problem, thank you in advance

**Comment by litespeedtech** [comment]
It is not a very important example application. 
I guess you need to run it in a debugger and figure it out if you have to make it work.
