### ISSUE TITLE
multithread and makefile？ Thanks in advance 。。

### ISSUE THREAD

**Issue by muyiwq** [litespeedtech/lsquic#265]
Can lsquic multithreading operate multiple streams of the same connection? How do I compile the examples with the makefile I wrote, and there are always problems with my own link library and header files? Can you give a makefile that is not generated by cmake? It is not compiled with the makefile generated by cmake. How to introduce this code into c++? Can extern "C" only include the header file? Looking forward to your reply

**Comment by litespeedtech** [comment]
lsquic thread safety is at engine level. if you want to do multithreading at stream level, you need to add your own thread safety layer for that. 
Sorry, we only no comment on your makefile, you are on your own.
