### ISSUE TITLE
BUG: Incorrect buffer size is specified in function qeh_write_headers

### ISSUE THREAD

**Issue by StarOceanR** [litespeedtech/lsquic#266]
File: lsquic/src/liblsquic/lsquic_qenc_hdl.c, ln.423
The size should be set "qeh->qeh_encoder.qpe_cur_max_capacity * 2". This bug is performed in Windows branch.

**Comment by litespeedtech** [comment]
Has it been fixed in the master branch? Please try the master branch, that's the branch being actively maintained.

**Comment by StarOceanR** [comment]
The bug seems still stand now.
