### ISSUE TITLE
still not thread-safe~~

### ISSUE THREAD

**Issue by jazune** [litespeedtech/lsquic#267]
Last Oct, I use the commit https://github.com/litespeedtech/lsquic/commit/2f4629f27dc51dddee699fef2bfcc0c33e60ccb2 to solve the thread-safe problem and it works fine.
But In Release 2.22.0, lsquic did not use that thread-safe commit, instread, it used ssl_ctx ext_data to save compressed cert.
If ssl_ctx is the same one in different thread, it wll cause thread not safe, and this will cause assert(ccert->refcnt > 0) failed in put_compressed_cert.

![image](https://user-images.githubusercontent.com/9442957/116399693-c6755280-a85b-11eb-8192-a4d26db6ebd3.png)

**Comment by litespeedtech** [comment]
That patch is on the master branch. 
Our usage does not require strict thread-safety. 
Quality pull request is welcome to make the library more MT friendly. :-)
