### ISSUE TITLE
Endless loop?

### ISSUE THREAD

**Issue by cang-mang** [litespeedtech/lsquic#268]
In file `lsquic_engine.c`.
In function `static lsquic_conn_t *coi_next(struct conns_out_iter *)`.
In condition `!TAILQ_EMPTY(&iter->coi_active_list)`.
The code is:
```
conn = iter->coi_next;
if (!conn) conn = TAILQ_FIRST(&iter->coi_active_list);
if (conn) iter->coi_next = TAILQ_NEXT(conn, cn_next_out);
return conn;
```

For example, the `iter->coi_active_list` has one node. For the 1st time we call `coi_next`, the `iter->coi_next` is NULL, so `conn` will point to the only node, and the `iter->coi_next` will still point to NULL. For the 2nd time we call `coi_next`, the same result. For the 3rd time, still. And the 4th ...

So, if the `iter->coi_active_list` has some node, the function `coi_next` will not return NULL to tell us it finishes traveling the `iter->coi_active_list`.

**Comment by litespeedtech** [comment]
That's true. 
But the caller is removing connections from `iter->coi_active_list` and break out of the loop if certain conditions meet.
Please read the related code in `send_packet_out()`.
