### ISSUE TITLE
cannot have more than one connection on the same port

### ISSUE THREAD

**Issue by zhaowq32** [litespeedtech/lsquic#269]
When multiple local socket ports are 0, engine will report an error when creating a new connection with same local sockaddr.For udp connection, port 0 means random port.

**Comment by litespeedtech** [comment]
Hope you had figured out the root cause. 
It is just simple `bind()` syscall, not really related to our library. For client, we always use port 0 with INADDR_ANY, kernel will pick an unused port automatically. If you set a specific IP, you may need to set a port. Not sure.

**Comment by zhaowq32** [comment]
If i have multi client,each client's addr is INADDR_ANY and port is 0.When call lsquic_engine_connect,the lsquic whill through an error 'cannot have more than one connection on the same port'.
