### ISSUE TITLE
Questions about writing data to the stream

### ISSUE THREAD

**Issue by zhaowq32** [litespeedtech/lsquic#272]
Should I call the lsquic_stream_write function to write data or cache the data in the buffer, and then write through the on_write callback？

**Comment by wangfuyu** [comment]
> Should I call the lsquic_stream_write function to write data or cache the data in the buffer, and then write through the on_write callback？

on_write is an event which tell you that you can write data to lsquic stack by lsquic_stream_write.

**Comment by zhaowq32** [comment]
How to ensure that all data has been sent out when the stream is closed？

**Comment by zhaowq32** [comment]
I want to write 62696 bytes of data to the stream, the on_write event is only called once, and lsquic_stream_write returns 46382. Calling lsquic_stream_wantwrite and lsquic_engine_process_conns again will not work.

**Comment by litespeedtech** [comment]
It is event driven, call lsquic_engine_process_conns immediately wont make it happen. you have to register the event and wait for the event in a event loop. on_write event will happen once those buffered data has been flushed out,

**Comment by zhaowq32** [comment]
The return value of lsquic_stream_write represents the actual data sent. Does the remaining data need to be sent in the next on_write callback?

**Comment by litespeedtech** [comment]
yes.
