### ISSUE TITLE
When multiple connections are created in the same program, the stream creation fails, will cause ifc_n_delayed_streams to increase, and then trigger the connection to close? How to solve it?

### ISSUE THREAD

**Issue by muyiwq** [litespeedtech/lsquic#274]
Dear Sir, when I try to create multiple connections on the same engine, or when I directly reuse the entire client code to create a connection in the same program. When creating a stream ietf_full_conn_ci_make_stream (struct lsquic_conn *lconn)
Will trigger ifc_n_delayed_streams++, I checked the client and server initialization es_init_max_stream_data is not up to the upper limit, why does this happen? How can I solve it? Could you please give some suggestions?

**Comment by muyiwq** [comment]
Dear Mr
How to realize multiple connections for the same engine in client mode? The stream cannot be created normally, and then I assign a prog_add_sport() to each connection. The engine will first create all the connections on_new_conn. When there are more connections, it will report the assert(!(conn->cn_flags & flag)) in engine_incref_conn(). Sigabort signal, can you give me some suggestions? What should I pay attention to to keep the client alive and establish multiple connections?

**Comment by litespeedtech** [comment]
If you need to connect to the same server from the same client, and the protocol requires unique 4-tuples socket, you have to create different client socket for each connection, and pass the correct socket source port to the client engine. there is no way around it. 
However, you need to ask why you need multiple connections, as QUIC is intended to use multiple streams over the same connection. In general, you do not need multiple connections to the same server.

**Comment by muyiwq** [comment]
Dear sir, I have the need to send short connections to different machines and start the client in multiple threads. If these four places are not locked
1.prog_cleanup()
2.prog_connect()
3.prog_add_sport()
4.prog_init();
All segfaults, the following one corresponds to the crash code
1.lsquic_global_init() lsquic_str.c 75 line: free(lstr->str);
2.sport_destroy() test_common.c 220 line: event_free(sport->ev);
3.sport_new() test_common.c 268 line: re_code = regcomp()
4.lsquic_global_cleanup() lsquic_str.c 59 line: newstr = realloc(lstr->str, newlen + 1);
Even if 4 places are locked, it will appear
[warn] Added a signal to event base 0x7fdee4003340 with signals already added to event_base 0x7fded8003180. Only one can have signals at a time with the epoll backend. The base with the most recently added signal or the most recent event_base_loop() call gets preference; do not rely on this behavior in future Libevent versions.

Many messages fail to be sent. Only when the entire client is locked can it be sent normally. Is there any way I can make the lock granularity smaller? Isn't the engine level thread-safe?

![lsquic_crt_cleanup()](https://user-images.githubusercontent.com/34933482/120135631-4a2bb180-c203-11eb-82a4-dcee9c53ccd3.jpg)
![lsquic_global_init](https://user-images.githubusercontent.com/34933482/120135639-4dbf3880-c203-11eb-8ad1-2ef2bc508bbc.jpg)
![prog_connect()](https://user-images.githubusercontent.com/34933482/120135645-4ef06580-c203-11eb-91f5-857598eccc08.jpg)
![sport_new()](https://user-images.githubusercontent.com/34933482/120135647-4f88fc00-c203-11eb-88a0-8964bd6fcf9d.jpg)

**Comment by muyiwq** [comment]
I have a doubt, where can the client get the connection failure or success status? The success of the client on_new_conn() callback does not mean that the client is successfully connected.
The lsquic manual says that In client mode, on the other hand, this callback is called as soon as connection object is created inside the engine, but before the handshake is done.
Is it necessary to add an optional callback to the on_hsk_done() judgment? What should I do?

**Comment by muyiwq** [comment]
When the client cannot connect to the correct server, the client only calls on_new_conn(), on_new_stream() is not called and blocked, and the return value of prog_connect() returns to normal. I cannot judge the status of the client connection failure.
I added an optional callback on_hsk_done(), but this callback is only called after on_new_stream() is called successfully, and there is no way to go back to the failed connection state. Where can I get it?

**Comment by muyiwq** [comment]
When the client cannot connect to the correct server, the client only calls on_new_conn(), on_new_stream() is not called and blocked, and the return value of prog_connect() return to normal. I cannot judge the status of the client connection failure.


lsquic_conn_status() is in LSCONN_ST_HSK_IN_PROGRESS status in on_new_conn() regardless of whether the connection to the server is successful or not. When the server cannot be connected, on_new_stream() cannot be entered, and the connection failure status cannot be obtained.

I added an optional callback on_hsk_done(), but this callback is only called after on_new_stream() is called successfully, and there is no way to go back to the failed connection state. Where can I get it?

**Comment by litespeedtech** [comment]
You need watch for LSCONN_ST_TIMED_OUT for the connection.

**Comment by muyiwq** [comment]
lsquic_conn_status() is in LSCONN_ST_HSK_IN_PROGRESS status in on_new_conn() regardless of whether the connection to the server is successful or not.
&nbsp;When the server cannot be connected, on_new_stream() cannot be entered,&nbsp; Normal connection status on_new_stream() returns the connection status LSCONN_ST_CONNECTED
Where to get the connection failure status&nbsp; watch for LSCONN_ST_TIMED_OUT ?



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "litespeedtech/lsquic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月31日(星期一) 晚上9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [litespeedtech/lsquic] When multiple connections are created in the same program, the stream creation fails, will cause ifc_n_delayed_streams to increase, and then trigger the connection to close? How to solve it? (#274)





 
You need watch for LSCONN_ST_TIMED_OUT for the connection.

**Comment by muyiwq** [comment]
Multithreading  client Only when the entire client is locked can it be sent normally. Is there any way I can make the lock granularity smaller? Isn't the engine level thread-safe? Any suggestions for me？

Thank you for your hard work and selfless dedication。。

**Comment by litespeedtech** [comment]
you need to hook all connection level callback. I think `on_conn_closed()` should tell you why connection closed. 

lsquic is not intended for stream/connection level MT client. It is for event driven, engine level MT client. each thread has its own engine, handle all connections associated with the engine.

**Comment by muyiwq** [comment]
Thank you for your reply！！！
	I always thought that the engine and the connection are thread-safe, and the stream needs to control the security by itself, and many unnecessary problems are caused by this.
	My error was that one thread went to prog_run to listen to all events, and one thread went to add client connections, which caused many unknown problems.
      This problem has troubled me for a long  time........ Then everything is normal for multiple connections under the same engine in a single thread.
      Thank you again
