### ISSUE TITLE
Can I request the HTTP service developed by lsquic directly through Google browser?

### ISSUE THREAD

**Issue by blind-drunk** [litespeedtech/lsquic#276]
Hello, the author, hard work. Excuse me, can I access quic HTTP service developed by lsquic through browser? I don't understand. Now some services can directly request quic's HTTP service through the browser. Why does lsquic still need the corresponding HTTP client. What can be modified to achieve this?

**Comment by litespeedtech** [comment]
You can use OpenLiteSpeed, LiteSpeed Enterprise, or our ADC (Load Balancer), all with QUIC/HTTP3 enabled.
