### ISSUE TITLE
How to identify server offline?

### ISSUE THREAD

**Issue by zhaowq32** [litespeedtech/lsquic#277]
I need to perform failover on the server, how can I identify the server is offline?

**Comment by litespeedtech** [comment]
Same way as with TCP.

**Comment by zhaowq32** [comment]
I am trying to connect to a host port that does not exist. After lsquic executes the new_conn callback function, new_stream is no longer called

**Comment by litespeedtech** [comment]
Failed to establish a connection is one signal for that.
