### ISSUE TITLE
Why is there such a big difference in the maximum transmission bit rate between windows server and Linux server

### ISSUE THREAD

**Issue by blind-drunk** [litespeedtech/lsquic#278]
Hello, the author. I'm sorry to interrupt. I've been testing the bit rate of lsquic recently.

I started the server and client on a Windows machine, and the server kept sending data to the client. After 10 minutes of testing, the maximum transmission bit rate was 30mbps, and the average transmission bit rate was close to 30mbps

I started the server and client on an Ubuntu machine, and the server side kept sending data to the client. After 10 minutes of testing, the maximum transmission bit rate was 600 Mbps, and the average transmission bit rate was about 580 Mbps

What are the reasons for such a big difference in lsquic transmission rates between windows and Linux? Or do I need special settings?

**Comment by litespeedtech** [comment]
We are a linux shop. Cannot help you much on tuning on Windows port. 
You need to check what the bottle neck and find a way to improve it. CPU/Network or something else.  
You can use a Linux client talk to Windows server, or vice versa to find out which component slows it down.

**Comment by blind-drunk** [comment]
Thank you for your explanation.

In the demo of lsquic, echo_server and echo_client for example, is there any parameter that can set the window size of quic flow control?





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LiteSpeed ***@***.***&gt;; 
发送时间: 2021年5月22日(星期六) 凌晨5:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [litespeedtech/lsquic] Why is there such a big difference in the maximum transmission bit rate between windows server and Linux server (#278)





 
We are a linux shop. Cannot help you much on tuning on Windows port.
 You need to check what the bottle neck and find a way to improve it. CPU/Network or something else.
 You can use a Linux client talk to Windows server, or vice versa to find out which component slows it down.
