### ISSUE TITLE
Delayed delivery

### ISSUE THREAD

**Issue by zhaowq32** [litespeedtech/lsquic#279]
I use msquic as the communication protocol between the socks client and server, and I find that the delay is very large during use.Looking at the log, it is found that when the tcp on the server side receives the data, the data will accumulate in the cache waiting to be sent, and the sending callback of lsquic seems to be delayed.

**Comment by litespeedtech** [comment]
Sorry, I cannot help much on this for you. 
This is event driven programming, and the event need to be triggered in timely manner, and the events need to be properly handled. we do not any problem using our library to handle that, the library provide necessary interface to make it work.
