### ISSUE TITLE
How can lsquic improve the transmission rate

### ISSUE THREAD

**Issue by blind-drunk** [litespeedtech/lsquic#280]
Hello, I would like to ask lsquic source code, where can be set to improve the transmission rate ah. Now I found lsquic_ send_ctl.c  source file, but I still can not find which parameters can improve the transfer rate. Now I start the server and client of lsquic on the same machine, and the maximum transmission rate is about 30 Mbps. Under the same conditions, the transmission rate of TCP can reach 3000 Mbps or even higher. Now I really want to know where the size of the transmission window or the transmission frequency is limited in lsquic. I'm looking forward to your reply. Thank you.

**Comment by blind-drunk** [comment]
I would like to add that I start server and client on the same machine. Basically, the impact of congestion window on the transmission of lsquic will be very limited. However, the transmission rate of lsquic is only about 30mbps, while TCP can easily exceed 3000mbps, which must be affected by the sending window or receiving window or the sending or receiving frequency of lsquic. I'd like to know where these control parameters are?

**Comment by litespeedtech** [comment]
You should not compare TCP to HTTP/3 (any implementation) over loopback. 
QUIC wont be as fast as TCP for fast reliable network, do not attempt to replace TCP for that use case. 
QUIC/HTTP3 is for less optimum network environment with slight packet loss, that's the sweat spot. 
And for high throughput test case, QUIC cannot match TCP.

Have fun playing with the code. :-)

**Comment by blind-drunk** [comment]
Thank you for your hard work. I asked a question before. The transmission rate of lsquic on Windows platform is much lower than that on Linux platform. Now I guess it should be the performance difference of libevent between the two platforms. What do you think

**Comment by litespeedtech** [comment]
I have no idea. :-) It needs platform specific optimizations for sure. 
For Windows, msquic could perform better.

**Comment by blind-drunk** [comment]
OK, can msquic and lsquic communicate with each other? For example, lsquic deploys the server in Linux and msquic deploys the client in windows. Can they communicate?
