### ISSUE TITLE
How to use IETF transport mode of lsquic

### ISSUE THREAD

**Issue by shuangxi-zheng** [litespeedtech/lsquic#283]
1. Now,  I want use transport mode of IETF (iquic). Am I input flag 0 as the second arg of '' lsquic_engine_init_settings" method and the first arg of "lsquic_engine_new" method ?

2. If the flag 0 is sure, what the other configurations or settings are needed ? Now, I input flag 0 and connect quic-go server, but handshake timeout.

3. In the demo of echo_client ,  the flag 0 is set and the "ea_alpn" is set to "echo", but it CAN NOT connect quic-go server successfully. What can I do?  And the field "on_hsk_done" of struct "lsquic_stream_if" is not setted, why?

**Comment by litespeedtech** [comment]
Please play with the sample application, read the sample code. 
For client side, the protocol selection is done via option `-o version=xxxx` .
You need a better understanding before starting to write your own code.
