### ISSUE TITLE
IETF Client If multiple connections are established under the same engine,  Are there any suggestions?

### ISSUE THREAD

**Issue by muyiwq** [litespeedtech/lsquic#286]
sometimes different segfaults will be reported, and sometimes it is normal.

1. My main code for establishing multiple connections under the same engine:
     for(int i=0;i<clientCount;++i)
     {
         prog_add_sport(client_ctx->prog, "127.0.0.1:9999");
         s = prog_init_client(client_ctx->prog);
         if (0 != prog_connect(client_ctx->prog, NULL, 0))
     }

2. Sometimes it will report segmentation error 1: lsquic_engine_process_conns().
lsquic_engine 2036 line: ENGINE_IN(engine); with gdb screenshot engine.jpg
3. Sometimes it will report ssl segmentation errors 2,3,4: iquic_esfi_handshake() 1905 line SSL_do_handshake().
4. 
![engine](https://user-images.githubusercontent.com/34933482/120150343-879d3880-c21d-11eb-85fd-d26e410f1777.jpg)
![ssl1](https://user-images.githubusercontent.com/34933482/120150353-8bc95600-c21d-11eb-92a8-b02df8b6a28d.jpg)
![ssl2](https://user-images.githubusercontent.com/34933482/120150360-8cfa8300-c21d-11eb-8730-d0c7d001cb56.jpg)
![ssl3](https://user-images.githubusercontent.com/34933482/120150365-8e2bb000-c21d-11eb-93de-bead25d17f5b.jpg)
![ssl4](https://user-images.githubusercontent.com/34933482/120150368-8f5cdd00-c21d-11eb-8ae0-947c90525625.jpg)

 Attached gdb screenshots.     ssl1.jpg,ssl2.jpg,ssl3.jpg,ssl4.jpg

How about establishing multiple connections under the same engine? The 4-tuples I created share a prog, what should I do? Looking forward to your suggestions?

**Comment by litespeedtech** [comment]
Sorry, there is not much we can do about your customized code. 
Our http_client example can create multiple connections without problem. please read the code and figure out how it should be done.
