### ISSUE TITLE
each thread has its own engine, handle all connections associated with the engine？

### ISSUE THREAD

**Issue by muyiwq** [litespeedtech/lsquic#287]
You guided me each thread has its own engine, handle all connections associated with the engine.

I check that the server handles multiple connections in a single thread. Does this mean that the server and client under the same engine do not support multiple threads? Does multithreading have to be under different engines?

My simple multiple clients under the same engine was that one thread went to prog_run to listen to all events, and one thread went to add client connections, add evthread_use_pthreads() was invalid, which caused many unknown problems.

It is normal for a single-threaded engine to process multiple connections at the same time. In the single-threaded state, I didn't think of a way to add connections when I need to add connections. Any suggestions for me?

Must lsquic client and server each thread has its own engine, handle all connections associated with the engine?
Does lsquic support multi-threaded server and client under the same engine?

**Comment by muyiwq** [comment]
My simple multiple clients under the same engine was that one thread went to prog_run to listen to all events, and one thread went to add client connections was locked,

Basic errors are reported inside event_base_loop(), how can I lock it?
Is it necessary to lock the place where the source code corresponds to the non-reentrant function that reports the error?
![Uploading 111622605700_.pic_hd.jpg…]()

**Comment by muyiwq** [comment]
My simple multiple clients under the same engine was that one thread went to prog_run to listen to all events, and one thread went to add client connections was locked,

Basic errors are reported inside event_base_loop(), how can I lock it?
Is it necessary to lock the place where the source code corresponds to the non-reentrant function that reports the error?
![111622605700_ pic_hd](https://user-images.githubusercontent.com/34933482/120429262-aa5b5880-c3a7-11eb-857a-fc878a86ff09.jpg)

**Comment by muyiwq** [comment]
Multi-threads start at the same time (engine: connection, 1:1 or 1:n) multi-engine multi-connection client,
The entire client must be locked before the next engine can be established. Multiple engines cannot exist at the same time. Is the method I used wrong? Any suggestions?

**Comment by litespeedtech** [comment]
lsquic is for event driven application, not for multi-thread application. 
It allows use multi-thread to take advantage SMP, but each thread still need to run in event driven mode with its own engine.
lsquic internally does not use mutex or lock. it is your responsibility to make sure only one thread is accessing one engine at any given time, otherwise, there will be race. 

There is not much we can help with using lsquic in a true MT application, I would say, it will not work and does not scale.
