### ISSUE TITLE
Is key update initiation implemented?

### ISSUE THREAD

**Issue by maruibin** [litespeedtech/lsquic#290]
Hi,

I was playing with the example http3 client and server, and transferring some data between them. According to the log, interestingly I found that the key phase didn't change during the connection and hence no key update happened. Then I checked the lsquic_enc_sess_ietf.c and found that there seems to be no key update initiated there (looks like it's able to respond to a key update initiated by the peer, but just won't initiate one by itself). Just wanted to confirm, is the key update implemented in the current version? If not may I get any brief advice on how to initiate a key update?

Any advice and thoughts will be appreciated,

Thanks

**Comment by maruibin** [comment]
It looks like the key udpate would be triggered if the packet number reaches the threshold set by IQUIC_INVALID_PACKNO (lsquic_packet_common.h:190) which seems to be consistent with the usage limit of `AEAD_CHACHA20_POLY1305` defined by [rfc9001](https://datatracker.ietf.org/doc/html/rfc9001#section-6.6). One question here is why use limit of chacha20 rather than other ciphers? (some other ciphers have smaller usage limit)

Another question I had here is, it looks like the key update won't be initiated even if the packet number reaches that secure limit, please refer to this code block taken from `lsquic_enc_sess_ietf.c:2226`:

```c
  key_phase = (dst[0] & 0x04) > 0;
  pair = &enc_sess->esi_pairs[ key_phase ];
  if (key_phase == enc_sess->esi_key_phase)
  {
      crypto_ctx = &pair->ykp_ctx[ 0 ];
      /* Checked by header_prot_inited() above */
      assert(crypto_ctx->yk_flags & YK_INITED);
  }
  else if (!is_valid_packno(
                  enc_sess->esi_pairs[enc_sess->esi_key_phase].ykp_thresh)
          || packet_in->pi_packno
              > enc_sess->esi_pairs[enc_sess->esi_key_phase].ykp_thresh)
  {
      const struct ku_label kl = select_ku_label(enc_sess);
      lsquic_qhkdf_expand(enc_sess->esi_md,
          enc_sess->esi_traffic_secrets[0], enc_sess->esi_trasec_sz,
          kl.str, kl.len, new_secret, enc_sess->esi_trasec_sz);
      if (enc_sess->esi_flags & ESI_LOG_SECRETS)
          LSQ_DEBUG("key phase changed to %u, will try decrypting using "
              "new secret %s", key_phase, HEXSTR(new_secret,
              enc_sess->esi_trasec_sz, secret_str));
      else
          LSQ_DEBUG("key phase changed to %u, will try decrypting using "
              "new secret", key_phase);
      crypto_ctx = &crypto_ctx_buf;
      crypto_ctx->yk_flags = 0;
      s = init_crypto_ctx(crypto_ctx, enc_sess->esi_md,
                  enc_sess->esi_aead, new_secret, enc_sess->esi_trasec_sz,
                  evp_aead_open);
      if (s != 0)
      {
          LSQ_ERROR("could not init open crypto ctx (key phase)");
          dec_packin = DECPI_BADCRYPT;
          goto err;
      }
  }
  else
  {
      crypto_ctx = &pair->ykp_ctx[ 0 ];
      if (UNLIKELY(0 == (crypto_ctx->yk_flags & YK_INITED)))
      {
          LSQ_DEBUG("supposedly older context is not initialized (key "
              "phase: %u)", key_phase);
          dec_packin = DECPI_BADCRYPT;
          goto err;
      }
  }
```

It seems that, the second branch ("else if") will never be reached as long as the peer doesn't change the key phase, even if the packet number exceeds the threshold (when a key update is needed). Although the threshold is too large to be exceeded often, but is it a potential bug or is there a reason to do so? Any explanation would be appreciated.

**Comment by litespeedtech** [comment]
You are right, lsquic does not implement initiating key rotation, just follow peer's key rotation.

**Comment by maruibin** [comment]
That explains a lot - thank you very much!
