### ISSUE TITLE
Help with datagram interface

### ISSUE THREAD

**Issue by samhurst** [litespeedtech/lsquic#291]
Hi,

I'm interested in experimenting with the datagram interface in lsquic, but I'm having some issues. I've adapted the [lsquic-tutorial](https://github.com/dtikhonov/lsquic-tutorial) to [add support for the datagram interface](https://github.com/samhurst/lsquic-tutorial/commit/77dbf169c889d778826be729a4f12a57b7145bdd) as a first start, but I'm currently stuck.

The [documentation](https://lsquic.readthedocs.io/en/latest/apiref.html#datagrams) suggests that I need to set lsquic_engine_settings.es_datagrams to 1 and add the on_dg_write and on_datagram callbacks, which I've done (for both client and server). However, when I run the code, after raising the lsquic_conn_want_datagram_write() call and then calling lsquic_engine_process_conns(), I don't ever actually get my on_dg_write() callback that I'm expecting from calling [...]_process_conns() and the whole thing stalls.

Going through the code, I never see it enter the while loop in process_connections() in lsquic_engine.c and process the tick. Calling lsquic_engine_earliest_adv_tick doesn't seem to help. I've tried to understand how the duck_client/duck_server examples work, but haven't managed to spot any major differences so far. Any pointers to what I'm doing wrong are appreciated.

Thanks in advance,
-Sam

**Comment by litespeedtech** [comment]
If duck_client and duck_server work as expected with datagram interface, you can try make changes on top of that. 
If it stop working, revert and try making change in smaller steps.
Read the code, make sense of it, have fun.
