### ISSUE TITLE
closing connection does not send CONNECTION_CLOSE frame

### ISSUE THREAD

**Issue by YashaCLabs** [litespeedtech/lsquic#292]
Hi

We are having issues with some connections that do not close properly.
in `ietf_full_conn_ci_tick` at closing connection, it does not send pckt with `CONNECTION_CLOSE` frame (added some prints):
`conn: connection is OK to close`
`conn: generate conn close packet` (this print is just before the `RETURN_IF_OUT_OF_PACKETS();`)
`sendctl: send_ctl_can_send: n_out: 2544 (unacked_all: 2501); cwnd: 277536`
`sendctl: ctl->sc_flags & SC_PACE | send_ctl_can_send -> 0` (this one is the reason for not sending a pckt)
`conn: used up packet allowance, sending now (line 8405)`
`sendctl: packet 7437 has been sent (frame types: ACK)`
`sendctl: stats: n_total_sent: 7402; n_resent: 0; n_delayed: 0`
`conn: # ticks: 19482`
`conn: sent 7402 packets`
`conn: received 21949 packets, of which 0 were not decryptable, 0 were dups and 0 were errors; sent 7402 packets, avg stream` `data per outgoing packet is 0 bytes`
`conn: delayed ACKs settings: (3/1.000/0.800/0.350/0.050/0.050); packet tolerances sent: count: 0, min: 0, max: 0`
`conn: ACKs: delayed acks on: yes; in: 517; processed: 517; merged: 0`
my guess is that pacer do not allow the new pckt. 
Quic fix is to disable the `RETURN_IF_OUT_OF_PACKETS` check in case of closing connection, not sure if this is a good one. pls advise.

**Comment by litespeedtech** [comment]
This probably related to #281 , maybe need more tweaks handling CONNECTION_CLOSE.

**Comment by litespeedtech** [comment]
Please check commit (https://github.com/litespeedtech/lsquic/commit/47440e4eaf376676ac658a2b7cfb9470f350e385) .

**Comment by litespeedtech** [comment]
No comment == No problem. issue closed.
