### ISSUE TITLE
http_server on chrome 

### ISSUE THREAD

**Issue by w753621** [litespeedtech/lsquic#293]
http_server:  
`./http_server -c example.com,fullchain.pem,privkey.pem -s 192.168.136.129:1234 -L debug`
google-chrome:  
`google-chrome --new-window -incognito --allow-file-access-from-files --no-sandbox --no-proxy-server --enable-quic --quic-version=h3-29 --origin-to-force-quic-on=example.com:443 --host-resolver-rules='MAP example.com 192.168.136.129:1234' https://example.com:443`

google-chrome appears error: "ERR_QUIC_PROTOCOL_ERROR", it seems that handshake got wrong. Could google-chrome connect to lsquic-http-server?
Thanks

**Comment by litespeedtech** [comment]
google-chrome requires a valid SSL certificate. self signed cert wont work.

**Comment by w753621** [comment]
Thanks, it works.
