### ISSUE TITLE
echo_client multiple connections

### ISSUE THREAD

**Issue by alexhultman** [litespeedtech/lsquic#294]
Hello and sorry for misusing the issue tracker,

I've been trying to get two or more connections going with the echo_client example and I do get two _connections_ but one connection does not open a stream properly, so only one connection is working.

What I do is I put a loop around prog_prep and prog_connect:

https://github.com/litespeedtech/lsquic/blob/master/bin/echo_client.c#:~:text=%23endif-,if%20(0%20!%3D%20prog_prep(%26prog)),%7D,-LSQ_DEBUG(%22entering%20event

This opens two connections but like said, I'm somewhat stuck trying to get two streams. Any quick pointers to where I am missing something?

**Comment by litespeedtech** [comment]
You should not put `prog_prep()` in the loop, call it one time only.

**Comment by alexhultman** [comment]
Yeah I can see that now, prep creates a new engine. But the client examples still seem very bound to only one connection. For instance, prog_connect only reads the head of sport queue and seems to overall assume only one connection. If you try to call prog_connect twice, it will fail with "cannot use the same port"-esque error. I guess it will be easier to just start from scratch without the prog helper.

**Comment by litespeedtech** [comment]
For more complete example, you can check http_client .

**Comment by alexhultman** [comment]
Thanks for the hints. http_client does create multiple connections but it is quite a big example. I'm going to make my own minimal example using lsquic because I only need "raw" QUIC. Thanks

**Comment by alexhultman** [comment]
I'm testing the http_client example now and I can't get it to use multiple connections. It works if -R and -r are the same, but then it only uses 1 connection.

> ./http_client -n 10 -r 100000 -R 10000 -H www.example
.com -t -s 127.0.0.1:9004 -K -p /

Just prints this (note that -R is 10 times lower than -r):

> 01:41:17.563 [ERROR] engine: cannot have more than one connection on the same port
01:41:17.563 [ERROR] connection failed
