### ISSUE TITLE
Does lsquic server already support iquic early-data?

### ISSUE THREAD

**Issue by wangfuyu** [litespeedtech/lsquic#296]
Does lsquic server support IQUIC early-data?  I found that SSL_CTX_set_early_data_enabled only be called in init_client.

If support, could you tell me how to make it work?  Just call SSL_CTX_set_early_data_enabled(ssl_ctx, 1) while creating ssl_ctx? Thanks!

**Comment by litespeedtech** [comment]
Early-data is used for 0-RTT, you can try 0-RTT see if it works. 
It early-data is completely handled by BoringSSL internally.
