### ISSUE TITLE
Preferred Address Compile/Runtime Error

### ISSUE THREAD

**Issue by yurigbur** [litespeedtech/lsquic#302]
Hi,

if I compile lsquic with the `-DLSQUIC_PREFERRED_ADDR=1` flag, I encounter some issues

First, it seems in the `lsquic_enc_sess_ietf.c` there is a context missing for the function call of `enp_generate_scid(...)`. Currently the function that generates the SCIDs requires one argument more. 
![image](https://user-images.githubusercontent.com/55692565/125667197-12458a20-4d0f-40c2-b6d2-a58c1c00a9db.png)

Second, it seems during runtime (if I fix the first issue manually), if a connection is incoming, the example echo server crashes. I start the server with 
```bash
env LSQUIC_PREFERRED_ADDR4=192.168.123.123:9001 ./echo_server -c www.example.com,ca.pem,ca.key
```
The following error is thrown.
```bash
echo_server: /lsquic/bin/test_common.c:1533: find_sport: Assertion `0' failed.
Aborted (core dumped)
```

Would love some input about how to temporarily fix the second error until the code gets fixed/updated.
Thx!

**Comment by litespeedtech** [comment]
Once you set LSQUIC_PREFERRED_ADDR4, all clients must connect to that address, using other server address will cause the assert failure.
