### ISSUE TITLE
Peer Context life cycle.

### ISSUE THREAD

**Issue by user72345** [litespeedtech/lsquic#304]
Hi, thank you for this great library!

I'm building a server which is running  on lsquic. There is **_lsquic_engine_packet_in_** function which has **_peer_ctx_** parameter. I don't see how to use it as peer context, because I need to know when I can release it.

Thanks!

**Comment by litespeedtech** [comment]
In our application  it is used for storing UDP transport context. basically, use it send packets back to peer. Never need to release it.
If want to use it for other purpose, it is really up to your application to manage its life cycle.

**Comment by user72345** [comment]
> In our application it is used for storing UDP transport context. basically, use it send packets back to peer. Never need to release it.
> If want to use it for other purpose, it is really up to your application to manage its life cycle.

Thanks your response. I seen that in examples and in OpenLiteSpeed it is used as interface context. But the naming across a library is very confusing :)
Maybe as a quick fix it will be good to explain this moment in the documentation.
