### ISSUE TITLE
run duck_server/duck_client,  performance is too slow

### ISSUE THREAD

**Issue by wangweiwei1188** [litespeedtech/lsquic#308]
I want to test the datagram performance, and modify the duck_server.c/duck_client .c for testing.But the performance is too slow. The call routine is prog_timer_handler-->..... ->duck_client_on_dg_write.

**Comment by litespeedtech** [comment]
The duck_server and duck_client is just a example to show how to use the library, API, etc.
If outgoing traffic is generated in a timer, you need to increase the time frequency, or send out more packets in each timer tick.
Or, to generate traffic in other ways, with different event.

**Comment by wangweiwei1188** [comment]
> The duck_server and duck_client is just a example to show how to use the library, API, etc.
> If outgoing traffic is generated in a timer, you need to increase the time frequency, or send out more packets in each timer tick.
> Or, to generate traffic in other ways, with different event.

Yeah, I modify the duck_server.c and duck_client.c. 
duck_server.c：
-------------------------------------------begin-------------------------------------
char REQUEST[1000];
static ssize_t
duck_on_dg_write (lsquic_conn_t *conn, void *buf, size_t sz)
{
    int s;

    /* We only write one response */
    s = lsquic_conn_want_datagram_write(conn, 0);
    assert(s == 1);     /* Old value was "yes" */

    if (sz >= sizeof(RESPONSE) - 1)
    {
        LSQ_INFO("wrote `%s' in response", RESPONSE);
        memcpy(buf, RESPONSE, sizeof(RESPONSE) - 1);
        lsquic_conn_close(conn);    /* Close connection right away */
        return sizeof(RESPONSE) - 1;
    }
    else
        return -1;
}


static void
duck_on_datagram (lsquic_conn_t *conn, const void *buf, size_t bufsz)
{
    lsquic_conn_want_datagram_write(conn, 0);
}
-------------------------------------------end-------------------------------------

duck_client.c：
-------------------------------------------begin-------------------------------------
1) socketpair make two fd(fd[0] and fd[1])
2) make a thread, code like:
       while(1) {
            write(fd[0], xxx, xx);
       }
3) fd[1]'s read event add libevent, which do the things like:
     lsquic_conn_want_datagram_write(conn, 1);
     lsquic_engine_process_conns(&engine);


char REQUEST[1000];
static ssize_t
duck_client_on_dg_write (lsquic_conn_t *conn, void *buf, size_t sz)
{

    if (sz >= sizeof(REQUEST) - 1)
    {
        LSQ_INFO("wrote `%s' in request", REQUEST);
        memcpy(buf, REQUEST, sizeof(REQUEST) - 1);
        return sizeof(REQUEST) - 1;
    }
    else
        return -1;
}


static void
duck_client_on_datagram (lsquic_conn_t *conn, const void *buf, size_t bufsz)
{

}

-------------------------------------------end-------------------------------------

But the performance is also too slow, and the sending stops in a few seconds.

**Comment by wangweiwei1188** [comment]
It's fixed  by https://github.com/litespeedtech/lsquic/pull/315
