### ISSUE TITLE
Datagram Frame cant generate ack frame

### ISSUE THREAD

**Issue by JohnnanWang** [litespeedtech/lsquic#312]
Hi, when I use datagram through iquic, I find lsquic cant generate ack frame when the receiver receives datagram frame. It would cause the sender's unacked data increases without reset to zero. There's one way to solve this, add QUIC_FTBIT_DATAGRAM into the ALL_IQUIC_FRAMES macro.

**Comment by litespeedtech** [comment]
Yes, it can be done in that way. The RFC draft recommends to use together with delaying ACK frames. lsquic also support that.

**Comment by wangweiwei1188** [comment]
> Yes, it can be done in that way. The RFC draft recommends to use together with delaying ACK frames. lsquic also support that.

How can use it.

**Comment by wangweiwei1188** [comment]
It's fixed by https://github.com/litespeedtech/lsquic/pull/315

**Comment by litespeedtech** [comment]
```
    /**
     * Enable delayed ACKs extension.  Allowed values are 0 and 1.
     *
     * Default value is @ref LSQUIC_DF_DELAYED_ACKS
     */
    int             es_delayed_acks;
```
It is enabled by default. So, nothing to change.
