### ISSUE TITLE
http_server stream on_read should not be called again after connection error

### ISSUE THREAD

**Issue by wangfuyu** [litespeedtech/lsquic#316]
https://github.com/litespeedtech/lsquic/blob/ff412f2f22c7486c86e97e9bf30a36de5f4504c1/src/liblsquic/lsquic_stream.c#L2170

After stream->stream_if->on_read, connection may happen some unexpected ERROR, like INVALID settings frame, but ( (stream->sm_qflags & SMQF_WANT_READ && lsquic_stream_readable(stream)) == TRUE, then on_read will be called again, which will lead to read_payload-->assert(READER_SKIP == fr->fr_state.reader_type).

**Comment by litespeedtech** [comment]
What is the value for `fr->fr_state.reader_type` when it happens? 
the on_read() callback may needed as it is the way to tell application there is an error with the stream.  need to avoid the assert() in this situation.

**Comment by wangfuyu** [comment]
> What is the value for `fr->fr_state.reader_type` when it happens?
> the on_read() callback may needed as it is the way to tell application there is an error with the stream. need to avoid the assert() in this situation.

As I have found, fr->fr_state.reader_type is a random, like 725118769, 1513706607, 1226859884, etc.

**Comment by litespeedtech** [comment]
Probably need to check why it is not initialized.

**Comment by wangfuyu** [comment]
> Probably need to check why it is not initialized.

fr was malloced without set to zero, all elements in fr->fr_state are random value.

![image](https://user-images.githubusercontent.com/12257285/133363077-703d8713-9231-4f55-856d-8197ed8583af.png)

**Comment by litespeedtech** [comment]
Does the patch fix the assert failure?

**Comment by wangfuyu** [comment]
> Does the patch fix the assert failure?

I have create invalid SETTINGS frame request to test this patch,  it can fix the assert failure when invalid SETTINGS frame in.
There may have other scenes, but I cannot confirm them as so far.

**Comment by litespeedtech** [comment]
thanks. merged.
