### ISSUE TITLE
question about retransmission

### ISSUE THREAD

**Issue by wangweiwei1188** [litespeedtech/lsquic#318]
rfc9000 13.3. Retransmission of Information have the following words:

QUIC packets that are determined to be lost are not retransmitted whole. The same applies to the frames that are contained within lost packets. Instead, the information that might be carried in frames is sent again in new frames as needed.

New frames and packets are used to carry information that is determined to have been lost. In general, information is sent again when a packet containing that information is determined to be lost, and sending ceases when a packet containing that information is acknowledged

But I have not found the according code for processing it.When packet was lost, the lsquic_packet_out contain all the FRAME   will be retransmisson.

**Comment by wangweiwei1188** [comment]
When the DATAGRAM FRAME is lost, but it's retransmitted.

**Comment by litespeedtech** [comment]
No. Retransmitting DATAGRAM FRAME is not required. It is an unreliable stream by design.

**Comment by wangweiwei1188** [comment]
Yeah, Retransmitting DATAGRAM FRAME is not required.According to the https://quicwg.org/datagram/draft-ietf-quic-datagram.html, DATAGRAM FRAME should not retransmited, when it's lost.But when I test the it, lsquic  retransmit the DATAGRAM FRAME.

**Comment by litespeedtech** [comment]
It is the side effect of https://github.com/litespeedtech/lsquic/commit/ff412f2f22c7486c86e97e9bf30a36de5f4504c1
Made DATAFRAM FRAME into IQUIC_FRAME_RETX_MASK. 
Fix pushed to https://github.com/litespeedtech/lsquic/commit/01c36b79dffb2edc574253e93c6ada631c417b5e

**Comment by wangweiwei1188** [comment]
The implementation may have bugs. For example, if the QUIC packet containing STREAM and DATAGRAM frame is lost, according to the process logic, the QUIC packet will never be retransmitted.

**Comment by litespeedtech** [comment]
Any debug log for analysis?

**Comment by wangweiwei1188** [comment]
17:00:03.584 [DEBUG] [QUIC:C3DBC10233F0FC2C] event: sent packet 21, type Short, crypto: forw-secure, size 51, frame types: STREAM ACK DATAGRAM, ecn: 0, spin: 1; kp: 0, path: 0, flags: 1082163768; Q: 0; L: 0
17:00:03.584 [DEBUG] [QUIC:C3DBC10233F0FC2C] sendctl: packet 21 has been sent (frame types: STREAM ACK DATAGRAM)
17:00:03.584 [DEBUG] [QUIC:C3DBC10233F0FC2C] sendctl: set retx alarm to 1064664519486, which is 25309 usec from now, mode RETX_MODE_TLP


7:00:03.610 [DEBUG] [QUIC:C3DBC10233F0FC2C] sendctl: lost ACK in packet 21
17:00:03.610 [DEBUG] [QUIC:C3DBC10233F0FC2C] sendctl: lost retransmittable packet 21
17:00:03.610 [DEBUG] [QUIC:C3DBC10233F0FC2C] sendctl: consider last packets lost: 1 resubmitted
17:00:03.610 [DEBUG] [QUIC:C3DBC10233F0FC2C] hpi: read-0: lsquic_hpi_next: return stream 0, incr: 0, priority 8
17:00:03.610 [DEBUG] [QUIC:C3DBC10233F0FC2C] pacer: lsquic_pacer_can_schedule: 1

**Comment by wangweiwei1188** [comment]
There are two methods to resolve it:
1)  STREAM and DATAGRAM can't be contained in one QUIC packet(lsquic_send_ctl_get_writeable_packet).
2)  drop DATAGRAM frame when send_ctl_next_lost-->split_lost_packet

**Comment by litespeedtech** [comment]
Sounds like the third option is the easiest way to address this. 
Have you tested it?

**Comment by wangweiwei1188** [comment]
yes, but should remove assert in lsquic_packet_out_chop_regen.

**Comment by litespeedtech** [comment]
You mean this one?
```
            assert(frec->fe_off == 0);  /* This checks that all the regen
            frames are at the beginning of the packet.  It can be removed
            when this is no longer the case. */
```
Yes, it can be removed.

**Comment by wangweiwei1188** [comment]
and remove assert(packet_out->po_regen_sz == adj); 
patch:https://github.com/litespeedtech/lsquic/pull/325

**Comment by wangweiwei1188** [comment]
https://github.com/litespeedtech/lsquic/pull/325

**Comment by xuananwhu** [comment]
Does not the ACK frame will be retransmitted if its lost in handshake?
