### ISSUE TITLE
how do i automatic letsencrypt with lsquic?

### ISSUE THREAD

**Issue by superdolt** [litespeedtech/lsquic#329]
1. how to do automatic letsencrypt for domain names?
2. as reverse proxy to a web server nginx etc? <- show the reverse proxy part will do.

thx in advance. great software

**Comment by litespeedtech** [comment]
If you want to use it for WEB applications, you should try https://github.com/litespeedtech/openlitespeed , HTTP/3 is already integrated. Proxy should work as well, however, you may not need Nginx at once switch to openlitespeed. ;-)

**Comment by superdolt** [comment]
how to do automatic letsencrypt?

**Comment by litespeedtech** [comment]
You'd better trying https://github.com/usmannasir/cyberpanel , it will mange letsencrypt certs and a lot of other things for you.
