### ISSUE TITLE
memory leak: iquic_esfi_reset_dcid

### ISSUE THREAD

**Issue by yiguo-bj** [litespeedtech/lsquic#333]
Should call 

` cleanup_hp(&enc_sess->esi_hsk_hps[ENC_LEV_CLEAR]);`

before:

`setup_handshake_keys`

**Comment by litespeedtech** [comment]
in `iquic_esfi_reset_dcid()`?

**Comment by yiguo-bj** [comment]
> in `iquic_esfi_reset_dcid()`?
yes

`static int
iquic_esfi_reset_dcid (enc_session_t *enc_session_p,
        const lsquic_cid_t *old_dcid, const lsquic_cid_t *new_dcid)
{
    struct enc_sess_iquic *const enc_sess = enc_session_p;
    struct crypto_ctx_pair *pair;

    enc_sess->esi_odcid = *old_dcid;
    enc_sess->esi_rscid = *new_dcid;
    enc_sess->esi_flags |= ESI_ODCID|ESI_RSCID|ESI_RETRY;

    /* Free previous handshake keys */
    assert(enc_sess->esi_hsk_pairs);
    pair = &enc_sess->esi_hsk_pairs[ENC_LEV_CLEAR];
    cleanup_crypto_ctx(&pair->ykp_ctx[0]);
    cleanup_crypto_ctx(&pair->ykp_ctx[1]);
    cleanup_hp(&enc_sess->esi_hsk_hps[ENC_LEV_CLEAR]);  /*  should cleanup?? */

    if (0 == setup_handshake_keys(enc_sess, new_dcid))
    {
        LSQ_INFOC("reset DCID to %"CID_FMT, CID_BITS(new_dcid));
        return 0;
    }
    else
        return -1;
}`

**Comment by yiguo-bj** [comment]
@litespeedtech

**Comment by litespeedtech** [comment]
It is in the latest 3.0.3 release already. Thanks.

**Comment by yiguo-bj** [comment]
> It is in the latest 3.0.3 release already. Thanks.
Good job!
