### ISSUE TITLE
ifc_active_cids_count minus twice for some retire_connection_id frame

### ISSUE THREAD

**Issue by kertL** [litespeedtech/lsquic#334]
It's detected when using quic-go client to repeatly download a 13 MB file served by lsquic demo server. The detail process to reproduce is described in https://github.com/lucas-clemente/quic-go/issues/3282#issue-1011025446
and marten-seemann pointed it out that it looks like a lsquic issue.

I added some log in lsquic code, and found the ifc_active_cids_count will minus twice when a retire frame with non-zero seqno is received. The minus occurs in line 6357 and line 6303.
 
https://github.com/litespeedtech/lsquic/blob/fb96e96193dba2c46c2f04fcf1e5ad5f81497a96/src/liblsquic/lsquic_full_conn_ietf.c#L6357-L6370

https://github.com/litespeedtech/lsquic/blob/fb96e96193dba2c46c2f04fcf1e5ad5f81497a96/src/liblsquic/lsquic_full_conn_ietf.c#L6291-L6309

**Comment by litespeedtech** [comment]
Looks like it is indeed a bug. 
After code review, I think line 6357 can be commented out, and let retire_cid() to manage `ifc_active_cids_count` . 
Can you please give it a try? 
If the simple fix cannot cover all the corner cases, may have to add another flag.

**Comment by litespeedtech** [comment]
It is included in the latest 3.0.3 release.

**Comment by kertL** [comment]
> Looks like it is indeed a bug. After code review, I think line 6357 can be commented out, and let retire_cid() to manage `ifc_active_cids_count` . Can you please give it a try? If the simple fix cannot cover all the corner cases, may have to add another flag.
works fine now after pulling the latest code. Thanks!
