### ISSUE TITLE
boringssl compile error

### ISSUE THREAD

**Issue by SUOMALILI** [litespeedtech/lsquic#339]
![Screenshot_20211018_205605](https://user-images.githubusercontent.com/47624845/137735129-884b3d9f-acc0-4ae6-a5be-5bfb7148e642.png)
![Screenshot_20211018_205635](https://user-images.githubusercontent.com/47624845/137735148-d36ee703-f79c-4f46-b2be-0370f76bee28.png)

I compiled the specific version of boringssl and i got this problem.I guess it's from the c compiler.
But i don't know which version i should switch to...
When i use the newest version of boringssl,the problem gone,but different version of boring ssl may cause other problems.
Plz help

**Comment by wangweiwei1188** [comment]
The newest version of boringssl is ok.
