### ISSUE TITLE
BoringSSL error during handshake (unknown library)

### ISSUE THREAD

**Issue by mwalker2299** [litespeedtech/lsquic#341]
Hi LSQUIC team. I have recently began learning to use lsquic. I thought a good place to start would be creating my own echo client and server based on the tutorial code: https://github.com/dtikhonov/lsquic-tutorial.

However when I start the client and it begins the handshake process, it fails with the error: 
```
handshake: error:00000001:invalid library (0):OPENSSL_internal:unknown library
```
This seems to be independent of the server, as this error will occur even if there is no server running. 

The error occurrs when I use the latest version of lsquic (3.0.3) and the BoringSSL version specified in the README. If I build with the BoringSSL version used by the tutorial code this issue goes away. Similarly, if I build the tutorial code with BoringSSL version specified in the lsquic README, the error occurs when starting `tut` in client mode.

Does anyone know what causes the above error?

**Comment by litespeedtech** [comment]
Need to update boringSSL to newer version. 
https://github.com/litespeedtech/lsquic/issues/345
