### ISSUE TITLE
Do we have a plan to support webTransport?

### ISSUE THREAD

**Issue by xujiasci** [litespeedtech/lsquic#344]
https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3-02.txt

**Comment by litespeedtech** [comment]
No plan yet, but pull requests are welcome.

**Comment by alexhultman** [comment]
So whenever this spec releases, we want to support it? It looks very slim over HTTP3, so the interfaces shouldn't change that much or at all.
