### ISSUE TITLE
Identifying  new streams

### ISSUE THREAD

**Issue by BruceDLong** [litespeedtech/lsquic#349]
When we get a call to on_new_stream(), is there a way to find out which stream is being created? For example, suppose a connection calls lsquic_conn_make_stream() several times, how can we tell which call caused the stream now being processed?  

If it were not for the fact that stream creation can be delayed, a solution would be to have lsquic_conn_make_stream() return  the StreamID. Another solution would be the ability to pass something into lsquic_conn_make_stream() that will be relayed to the new stream or to on_new_stream().

Is there an existing solution that I have not seen?

**Comment by litespeedtech** [comment]
Why you need to identify a new stream?
All new streams from the same connection are pretty much identical, other than the stream ID.

**Comment by BruceDLong** [comment]
OK, Got it. So my solution will be to give connections a queue of pending sessions and have new streams just pop a task off of that queue. Thanks!
