### ISSUE TITLE
Why shared memory used when worker dealing with alien packets?

### ISSUE THREAD

**Issue by Lingtaonju** [litespeedtech/lsquic#351]
Dear sir, 
I wander why litespeed use shared memory to deal with alien packets but not unix domain socket ? What's the main concern?
For us, the memory used can't be avoided.

Best regards！

![image](https://user-images.githubusercontent.com/19946268/148366865-6eba423c-5308-47aa-9ad1-b6a951ca9446.png)

**Comment by litespeedtech** [comment]
This is for historic reason, when SO_REUSEPORT has not been implemented in our products. 
When multiple processes read packets from the same UDP socket, packets belong to one QUIC connection received by different worker processes.  
It is still useful during graceful restart, which need to pass packets from one process to another. 
For simple single worker process implementation that do not need graceful restart, it is not required.

**Comment by Lingtaonju** [comment]
> This is for historic reason, when SO_REUSEPORT has not been implemented in our products. When multiple processes read packets from the same UDP socket, packets belong to one QUIC connection received by different worker processes. It is still useful during graceful restart, which need to pass packets from one process to another. For simple single worker process implementation that do not need graceful restart, it is not required.

Thanks for your reply.
I have already known the problem as you described. However, my question is why Share Memory Used but not UDS, as packets stored in SHM will cost the memory and  scalability is not so good.

**Comment by litespeedtech** [comment]
SHM is zero-copy, UDS is slower.

**Comment by Lingtaonju** [comment]
Ok, thx, I  got that, but UDS is more flexible. 
I will do some performance test.  
Close at this time.
