### ISSUE TITLE
UDT Integration

### ISSUE THREAD

**Issue by ariarasooly** [litespeedtech/lsquic#356]
Hey,
Do you think we can integrate UDT with quic so data transfer would be faster and some congestion control problems would be solved?

**Comment by ariarasooly** [comment]
> Hey, Do you think we can integrate UDT with quic so data transfer would be faster and some congestion control problems would be solved?

The Library is already available

**Comment by litespeedtech** [comment]
those are two protocols do the similar things, I do not think they can play together.
