### ISSUE TITLE
Q: How to get the four tuple at the congestion control init

### ISSUE THREAD

**Issue by YashaCLabs** [litespeedtech/lsquic#360]
Hi,

For our purposes we want to know the four tuple (src ip, src port, dst ip, dst port) of each connection at its congestion control init - the `cci_init` callback.
How can we get them (if it is possible) from the parameters we got in the init
`    void
    (*cci_init) (void *cong_ctl, const struct lsquic_conn_public *,
                                                            enum quic_ft_bit);
`
If it is not possible to get them from current prms, what and from where should be passed to the `cci_init` callback.

Thanks
Yasha

**Comment by wangfuyu** [comment]
> Hi,
> 
> For our purposes we want to know the four tuple (src ip, src port, dst ip, dst port) of each connection at its congestion control init - the `cci_init` callback. How can we get them (if it is possible) from the parameters we got in the init ` void (*cci_init) (void *cong_ctl, const struct lsquic_conn_public *, enum quic_ft_bit);` If it is not possible to get them from current prms, what and from where should be passed to the `cci_init` callback.
> 
> Thanks Yasha

1)  conn_pub->lconn
2) lsquic_conn_get_sockaddr

**Comment by YashaCLabs** [comment]
Hi,

Thanks for the `QUIC` reply.

Followup question: 
Now printing the addresses at the connection init:
`2022-03-08 11:53:47.886712 [INFO] [QUIC:C5FC1ED59830C9E9] pcc: s_add 0 s_port 0 d_addr 0 d_port 0`
the address values are still zeros. printing them at the end:
`2022-03-08 11:54:18.039069 [INFO] [QUIC:C5FC1ED59830C9E9] pcc: s_add 335653056 s_port 47873 d_addr 167880896 d_port 3499`
they have the expected values.

we work with openlitespeed server.
is this an expected behavior - the congestion control init is called before this values are set? if so, how can i know during the connection life that this values are correct? after getting the first ACK?

**Comment by wangfuyu** [comment]
> Hi,
> 
> Thanks for the `QUIC` :) reply.
> 
> Followup question: Now printing the addresses at the connection init: `2022-03-08 11:53:47.886712 [INFO] [QUIC:C5FC1ED59830C9E9] pcc: s_add 0 s_port 0 d_addr 0 d_port 0` the address values are still zeros. printing them at the end of the connection (at cleanup): `2022-03-08 11:54:18.039069 [INFO] [QUIC:C5FC1ED59830C9E9] pcc: s_add 335653056 s_port 47873 d_addr 167880896 d_port 3499` they have the expected values.
> 
> we work with openlitespeed server. is this an expected behavior - the congestion control init is called before this values are set? if so, how can i know during the connection life that this values are correct? after getting the first ACK?

Yes, it is an expected behavior.

Func exec logic:

lsquic_gquic_full_conn_server_new: 1) -> new_conn_common -> lconn = calloc -> lsquic_send_ctl_init -> cci_init
                                                               2) -> conn->fc_path = mc->mc_path;

fc_path/mc_pat was assigned in ci_record_addrs.

**Comment by wangfuyu** [comment]
Why you want to know the four tuple while cci_init?
