### ISSUE TITLE
'es_honor_prst' didn't work when restart server?

### ISSUE THREAD

**Issue by emailsters** [litespeedtech/lsquic#379]
Hello, i was testing the scenario of restarting the server, `es_send_prst` and `es_honor_prst` is set to 1.

Client keep sending data to server, and then, restart the server, it seems the server response RST packet to client correctly.
```
19:21:52.649 [DEBUG] purga: C15FFE8A22BB902D not found
19:21:52.649 [DEBUG] prq: selected 30-byte reset size for CID C15FFE8A22BB902D (range is [21, 34])
19:21:52.649 [DEBUG] prq: scheduled stateless reset packet for connection C15FFE8A22BB902D
19:21:52.649 [DEBUG] engine: scheduled stateless reset packet for cid C15FFE8A22BB902D
19:21:52.649 [DEBUG] purga: C15FFE8A22BB902D not found
19:21:52.649 [DEBUG] prq: selected 30-byte reset size for CID C15FFE8A22BB902D (range is [21, 37])
19:21:52.649 [DEBUG] prq: request for this DCID and type already exists
19:21:52.649 [DEBUG] engine: cannot schedule stateless reset packet
19:21:52.650 [DEBUG] tokgen: generated stateless reset token C7F1CF9846FB867DFA4922934E68B498 for CID C15FFE8A22BB902D
19:21:52.650 [DEBUG] engine: batched packet 0 for connection C15FFE8A22BB902D
19:21:52.650 [DEBUG] engine: packets out returned 1 (out of 1)
19:21:52.650 [DEBUG] [QUIC:C15FFE8A22BB902D] event: sent public reset packet, size 30
19:21:52.650 [DEBUG] prq: sent stateless reset packet for connection C15FFE8A22BB902D; free resources
```

But the client seems to drop the RST packet? The expectation is that the client can receive RST packet and close the connection or stream?

```
19:21:52.037 [DEBUG] engine: DCID matches no SCID in connection B8AE0E86E336BD8D: drop it
```

**Comment by emailsters** [comment]
when receive RST packet from server, need to find connection from `enp_srst_hash`
![image](https://user-images.githubusercontent.com/1570006/169816288-024f03c4-59a3-46bb-ab44-4b575c040865.png)

but the `enp_srst_hash` insert connections only server when handshake done?
![image](https://user-images.githubusercontent.com/1570006/169816728-1fd3b941-b3d7-4f10-ad3a-c7f87c91191e.png)
![image](https://user-images.githubusercontent.com/1570006/169816832-e0de667a-a9b3-4522-872b-818eed2aa4f3.png)


As a result, the client cannot process the RST packet correctly?

**Comment by litespeedtech** [comment]
I think you have find the answer.
It is the way it works. 
Since the stateless reset token is saved in memory, not in a persistent storage, restart server will lose that token.
To make it survive server restarts, need to save it in a persistent storage, and then there are a lot more to consider if do that.  :-)
