### ISSUE TITLE
lsquic server 100% assert failed with special http_client

### ISSUE THREAD

**Issue by wangfuyu** [litespeedtech/lsquic#402]
I can make a special http_client, and make http_server 100% assert failed. (just need add 3 line code to http_client)
http_server failed in stream_readf, I am trying to fix it.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/12257285/182395744-133a42f5-4fef-4966-bc62-0d1c9fcab7ee.png">

**Comment by litespeedtech** [comment]
thanks for the fix.
