### ISSUE TITLE
Slow data transfer

### ISSUE THREAD

**Issue by scopedog** [litespeedtech/lsquic#404]
First, thanks for developing a nice library.

I created very basic data transfer programs based on md5_{server,client}.c and tested on localhost.
However, sending 10GB data takes 40 sec which is 2Gbps and is much slower than TCP + OpenSSL + TLSv1.3's 12Gbps with the most secure encryption.

As long as I see the CPU usages with top, both the server and client use almost 100% and I have no idea why they consume much more CPU power than regular OpenSSL + TLSv1.3.
There may be something wrong with my programs but it's very weird.

Does anybody have an idea? Is AES-NI turned off for lsquic?

**Comment by litespeedtech** [comment]
That's as expected. Packet level handling is expensive. QUIC performs better when used in less than perfect network condition, with higher CPU cost.
