### ISSUE TITLE
lsquic rechist rh_n_used field inconsistent with rechist contents

### ISSUE THREAD

**Issue by pjakma** [litespeedtech/lsquic#408]
The rechist rh_n_used field does not stay consistent with the contents of the rechist. This can be seen by modifying the code to call the internal sanity check from a number of points, and running lsquic. It will fail quickly. See diff here for an example test case:

https://github.com/pjakma/lsquic/commit/cbf35ca469bf36733326859a5e386ca468bd3fb8

The problem seems to occur in the insert_before: case of lsquic_rechist_received.

**Comment by pjakma** [comment]
Ok, that patch is failing on inconsistencies immediately after rechist_{alloc,free}_elem - but that's just cause those functions bump the n_used field, but do not adjust the other list state. So that's a red herring - the list will not be consistent at that point.

**Comment by pjakma** [comment]
See this test case, which produces a malformed list in the rechist: https://github.com/pjakma/lsquic/commit/76dd711679ef7e781be042d1d1f0236848e2a8fc

It produces this:

lsquic_rechist_received: el idx 0 [6 3] packno 9
lsquic_rechist_received: insert_before, prev 18446738196589648039 next 0 idx 0 head idx 0
0x7ffe65ce75a0: cutoff 9 l. acked 12087061905995 masks 1 alloced 4 used 1 max ranges 0 head 0
  (0)[6-3]
lsquic_rechist_received: insert before done
0x7ffe65ce75a0: cutoff 9 l. acked 12087061905995 masks 1 alloced 4 used 1 max ranges 0 head 0
  (0)[9-9] (0)[9-9] (0)[9-9] (0)[9-9] (0)[9-9] (0)[9-9] (0)[9-9]
test_rechist: /tmp/lsquic/src/liblsquic/lsquic_rechist.c:272: rechist_test_sanity: Assertion `rechist->rh_n_used == n_elems' failed.

From [6-3] at idx 0 with a null next field, it then goes to [9-9] at index 0 with next set to 0 - a circular list. It only stops iterating over it because I added a check in the code that iterates over the rechist list.

**Comment by pjakma** [comment]
Fix should be in this: https://github.com/litespeedtech/lsquic/pull/410

**Comment by litespeedtech** [comment]
Fix accepted. Thanks.
