### ISSUE TITLE
http_client: workspace/lsquic_tools/lsquic/src/liblsquic/lsquic_full_conn_ietf.c:3133: ietf_full_conn_ci_destroy: Assertion `conn->ifc_conn.cn_conn_ctx == NULL' failed.

### ISSUE THREAD

**Issue by vranem1** [litespeedtech/lsquic#411]
With the new version: Release 3.1.2

Command:
 ./bin/http_client -t -H devqa.akaquic.com -p /100KB.bin -o version=h3-29

starts to generate dumped core on the following failed assertion:
http_client: workspace/lsquic_tools/lsquic/src/liblsquic/lsquic_full_conn_ietf.c:3133: ietf_full_conn_ci_destroy: Assertion `conn->ifc_conn.cn_conn_ctx == NULL' failed.

From the inspection of the code it seems to me that the pointer is not reset to NULL when the assigned memory is dealocated.

**Comment by litespeedtech** [comment]
Please try release 3.1.3 .

**Comment by vranem1** [comment]
The issue seem to be gone in the newer version. Closing.
