### ISSUE TITLE
Memory leak in iquic_esf_decrypt_packet？

### ISSUE THREAD

**Issue by emailsters** [litespeedtech/lsquic#415]
hello
I start my program with 100 connections, with self-buffer of each connection, the memoy usage is about 1.9GB at the begining.
![image](https://user-images.githubusercontent.com/1570006/187908877-292558e7-7041-4a28-8504-0c4641fbbb08.png)

after running about 1 hour, the memory usage is up to about 3.9GB
![image](https://user-images.githubusercontent.com/1570006/187909111-de475d35-cfb6-4c5e-a1f7-1bdff35a484b.png)

after close the all 100 connections, the memory is still 3.9GB.
![image](https://user-images.githubusercontent.com/1570006/187909297-594413d5-03be-41eb-b81c-f42e27ab3ec8.png)

when recvmsg from socket, and call `lsquic_engine_packet_in`，sometimes alloc memoy in heap。

after using gdb break in `mmap`, i found that, after malloc by new_heap in `iquic_esf_decrypt_packet`，the memory increase about 64MB(64MB may be releated to my testing data?), and didn't decrease any more
![image](https://user-images.githubusercontent.com/1570006/187909505-10eb911a-4e22-4f9c-beee-815c68613ce9.png)

**Comment by litespeedtech** [comment]
Please check https://github.com/litespeedtech/lsquic/issues/409
