### ISSUE TITLE
Use of specific boringSSL version in build 

### ISSUE THREAD

**Issue by tzvikatz** [litespeedtech/lsquic#432]
Hi, 

From the how to build documentation it seems that the used boringSSL version that should be used during lsquic build was created about a year ago and since then over 340 additions to the boringSSL main branch were added including numerous CVE fixes of openSSL. 

Can this limitation of specific branch of boringSSL be removed or could it explained how the use of lsquic is not vulnerable to openSSL/boringSSL vulnerabilities? 

Kind regards, 
Tzvi Katz

**Comment by litespeedtech** [comment]
Feel free to try another version of boringSSL, including the latest version.
