### ISSUE TITLE
No ALPN is selected

### ISSUE THREAD

**Issue by TomerSchDev** [litespeedtech/lsquic#439]
When trying to make a connection using curl the connection  failed and I got this error message in debug:
**andshake::set_secret: No ALPN is selected: send fatal alert;**
so I did some digging into the code and found this line:
![image](https://user-images.githubusercontent.com/40770296/204130676-f4bd7fb3-e29c-4836-87a0-e686effff6b2.png)
here we comparing to different ALPNs and see if it the same...
the first one is ALPN selected between the server and the client have and the second one is based on the quic version of the connection...
why are we doing this check? if we selected protocol that the server and the client support why we need to see if the same protocol of the version?

**Comment by litespeedtech** [comment]
If you set ALPN when creating the server, it will be matched. It is part of handshake negotiation.

**Comment by jbl19860422** [comment]
i also meet this problem
