### ISSUE TITLE
Verifying clients with retry packets

### ISSUE THREAD

**Issue by mrmbernardi** [litespeedtech/lsquic#448]
https://www.litespeedtech.com/docs/litespeed-web-adc/config/tuning#quicDosMitigationDuration

The above feature seems to be supported in LSWS. Is it possible to enable it in lsquic with http mode?

**Comment by litespeedtech** [comment]
It is a feature in our commercial product, not available in the open source code. Sorry.

**Comment by mrmbernardi** [comment]
@litespeedtech Can the open source server generate tokens with the NEW_TOKEN frame at all? I see some references to a token generator in the source.
