### ISSUE TITLE
Followed official Demo example, but geting http/1.1 in response instead of http/3

### ISSUE THREAD

**Issue by anuragvohraec** [litespeedtech/lsquic#476]
Hi All,

I followed the official [demo example](https://lsquic.readthedocs.io/en/latest/gettingstarted.html#demo-examples), but getting http/1.1 in response by the client rather than http/3

Steps followed: 
1. Created localhost cert and key, in PEM format.
2. Than ran the demo `http_server`:  `./http_server -c localhost,public.pem,privatekey.pem  -s 0.0.0.0:4433`
3. Then ran the client to fetch the page : `./http_client -H localhost -s 127.0.0.1:4433 -p /`
Getting this in reponse: 
```
HTTP/1.1 200 OK
server: lsquic/4.0.1
content-type: text/html
content-length: 940

<html>
   <head>
       <title>LiteSpeed IETF QUIC Server Index Page</title>
   </head>
   <body>
       <h1>LiteSpeed IETF QUIC Server Index Page</h1>
       <p>Hello!  Welcome to the interop.  Available services:
       <ul>
           <li><b>POST to /cgi-bin/md5sum.cgi</b>.  This will return
                   MD5 checksum of the request body.
           <li><b>GET /123K</b> or <b>GET /file-123K</b>.  This will return
                   requested number of payload in the form of repeating text
                   by Jerome K. Jerome.  The size specification must match
                   (\d+)[KMG]? and the total size request must not exceed
                   2 gigabytes.  Then, you will get back that many bytes
                   of the <a
                       href=http://www.gutenberg.org/cache/epub/849/pg849.txt
                                                       >beloved classic</a>.
       </ul>
   </body>
</html>
```

Alos I did tried checking with google.com domain, its too is responding in http/1.1:  `./http_client -s www.google.com -p / -o version=h3-29`

Am I doing/assuming something wrong ?

**Comment by litespeedtech** [comment]
the `http_client` only speak HTTP/3 (QUIC), the response has been translated to HTTP/1.1 for upper layer to process.
