### ISSUE TITLE
How to resolve error in v2.8.9 ?

### ISSUE THREAD

**Issue by arpan-vs** [litespeedtech/lsquic#483]
Hello,
I have been trying to build lsquic-v2.8.9. However, I am getting the following errors, and I am unable to solve it.
![image](https://github.com/litespeedtech/lsquic/assets/77320691/d4ede673-e3ef-4f32-9e25-065a10493a2f)
Can you guide me how to resolve it?

**Comment by litespeedtech** [comment]
v2.8.9 is too old, you cannot use the latest boringSSL. you can try the older version listed in the README by that time.
should upgrade to the latest lsquic.
