### ISSUE TITLE
Support for Wordpress.com

### ISSUE THREAD

**Issue by ARHAEEM** [litespeedtech/lsquic#490]
I'm using WordPress.com with Quic cloud. Unfortunately, I am unable to integrate the CDN for my main use case, which is to optimize images. This is because it requires modifying the .htaccess file, but WordPress.com hosting uses the Nginx web server. I have access to SSH and WP Cli on my plan. How can I configure the .htaccess settings for Nginx? The plugin keeps prompting me to add data to the .htaccess file.

![image](https://github.com/litespeedtech/lsquic/assets/63544079/af09a750-7382-428a-a4f0-f30ba25f5250)

**Comment by litespeedtech** [comment]
wrong project.
