### ISSUE TITLE
consider building and pushing interop runner image in CI

### ISSUE THREAD

**Issue by marten-seemann** [litespeedtech/lsquic#492]
I noticed that the lsquic interop runner image is now almost 1 year (!) old: https://hub.docker.com/r/litespeedtech/lsquic-qir/tags

May I suggest to push a new interop runner on every push to master, or on a daily (?) cron job? GitHub Actions has some predefined workflows that should make building and pushing Docker images pretty straightforward. For inspiration, [here](https://github.com/quic-go/quic-go/blob/master/.github/workflows/build-interop-docker.yml) is quic-go's workflow, and Quinn has [one](https://github.com/quinn-rs/quinn-interop/blob/main/.github/workflows/dockerhub.yml) as well.

**Comment by litespeedtech** [comment]
We will look into that. Thanks!
