### ISSUE TITLE
how to close http mode

### ISSUE THREAD

**Issue by LinCan168** [litespeedtech/lsquic#500]
Hello! I want to pass the raw data between the two peer end.  Now I only get the connection of the http3 mode.

**Comment by LinCan168** [comment]
When I send the raw data, I got the error:"Attempt to write to stream before sending HTTP headers"
My question is: How to close the http mode. I didn't find flags or some api to reach this goal.
Thanks!

**Comment by litespeedtech** [comment]
just remove `LSENG_HTTP` flag.
