### ISSUE TITLE
Connection timeout (AL_HANDSHAKE) on loss of first packet.

### ISSUE THREAD

**Issue by psheer-spirent** [litespeedtech/lsquic#502]
Dear Sir/Ma'am,

Our use of liblsquic integrated into our application suite is successful, and is working well. However we are experiencing the following problem.

Our code uses the sequence,

  lsquic_engine_connect(...)
  ....
  lsquic_engine_process_conns(...)

thus lsquic_engine_process_conns() sends out the first packet to the physical layer. If this first packet is lost then no retry ensues and the handshake times out. We are correctly calling lsquic_engine_process_conns() at appropriate intervals as is required for application housekeeping. Packet loss is gracefully handled by liblsquic in all other scenarios. It is only if the first packet of the connection is lost that the connection times out.

I tried to find where in the lsquic source is specified the number of retries for the initial packet. I assume this is equivalent to the "syn retry count" of TCP. However I am not well versed in the lsquic internals. Can you point me in the right direction?

Is this a known issue?

We are using lsquic 3.0.3. (It is not trivial for us to upgrade right now.)

Kind regards

Paul

**Comment by litespeedtech** [comment]
3.0.3 is too old. you need to either upgrade, or back port related code. 
https://github.com/litespeedtech/lsquic/releases/tag/v4.0.0 
has major improvements for the case of high packet losses in handshake phase.

**Comment by psheer-spirent** [comment]
I understand.

Thank you.


> 3.0.3 is too old. you need to either upgrade, or back port related code. https://github.com/litespeedtech/lsquic/releases/tag/v4.0.0 has major improvements for the case of high packet losses in handshake phase.
