### ISSUE TITLE
[BUG] 'bpq_count' mismatch actual number of packets in 'bpq_packets'.

### ISSUE THREAD

**Issue by lxqwh** [litespeedtech/lsquic#504]
![image](https://github.com/litespeedtech/lsquic/assets/13362505/b1d80b51-4be8-4864-9a4d-30f2134eb656)
After removing a packet from 'bpq_packets', incrementing 'bpq_count' causes a mismatch between the 'bpq_count' and the actual number of packets in 'bpq_packets'.

**Comment by litespeedtech** [comment]
Thanks for the bug report. It should be fixed in 4.0.9 release.
