### ISSUE TITLE
Readme lsquic instructions need updating ?

### ISSUE THREAD

**Issue by centminmod** [litespeedtech/lsquic#78]
does this lsquic readme need and update on cmake with your instructions i get BORINGSSL_DIR is not used by this project error

```
CMake Warning:
  Manually-specified variables were not used by the project:

    BORINGSSL_DIR
```

without BORINGSSL_DIR i get

```
cmake -DBORINGSSL_INCLUDE=$BORINGSSL_SOURCE/include -DBORINGSSL_LIB=$BORINGSSL_SOURCE/lib .
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type: Debug
-- Performing Test HAS_NO_IMPLICIT_FALLTHROUGH
-- Performing Test HAS_NO_IMPLICIT_FALLTHROUGH - Success
-- AddressSanitizer is OFF
-- Compiler flags: -Wimplicit-fallthrough=0 -Wno-implicit-function-declaration   -Wall -Wextra -Wno-unused-parameter -fno-omit-frame-pointer -Wno-implicit-fallthrough -Wno-missing-field-initializers -O0 -g3 -Werror 
-- BoringSSL include directory /src/boringssl/include
-- Found /src/boringssl/lib library: /src/boringssl/lib/libssl.a
-- Found /src/boringssl/lib library: /src/boringssl/lib/libcrypto.a
-- /src/boringssl/lib library not found
-- Found zlib: /usr/lib/x86_64-linux-gnu/libz.a
-- Found event: /usr/lib/x86_64-linux-gnu/libevent.a
-- Looking for sendmmsg
-- Looking for sendmmsg - found
-- Looking for recvmmsg
-- Looking for recvmmsg - found
-- Looking for open_memstream
-- Looking for open_memstream - found
-- Looking for IP_MTU_DISCOVER
-- Looking for IP_MTU_DISCOVER - found
-- Looking for IP_DONTFRAG
-- Looking for IP_DONTFRAG - not found
-- Looking for include file regex.h
-- Looking for include file regex.h - found
-- Configuring done
-- Generating done
-- Build files have been written to: /src/lsquic
```

but error on make
```
[ 39%] Built target lsquic
[ 40%] Building C object CMakeFiles/http_client.dir/test/http_client.c.o
[ 40%] Building C object CMakeFiles/http_client.dir/test/prog.c.o
[ 41%] Building C object CMakeFiles/http_client.dir/test/test_common.c.o
[ 41%] Building C object CMakeFiles/http_client.dir/test/test_cert.c.o
[ 42%] Linking C executable http_client
/usr/bin/ld: src/liblsquic/liblsquic.a(lsquic_enc_sess_ietf.c.o): in function `iquic_new_session_cb':
/src/lsquic/src/liblsquic/lsquic_enc_sess_ietf.c:1134: undefined reference to `SSL_SESSION_get_max_early_data_size'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/http_client.dir/build.make:134: http_client] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/http_client.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```

**Comment by dtikhonov** [comment]
Yes, they do: thanks for reporting it.

For now, you can follow directions in `.travis.yml`.

**Comment by dtikhonov** [comment]
Fixed build instructions in c38e7df733073d90ece8afb00d9201a42f3e5568.  Please give it another shot.

**Comment by litespeedtech** [comment]
Fixed -- closing.

**Comment by centminmod** [comment]
i still get an different error on boringssl make run

```
Scanning dependencies of target boringssl_gtest_main
[ 63%] Building CXX object crypto/test/CMakeFiles/boringssl_gtest_main.dir/gtest_main.cc.o
[ 63%] Built target boringssl_gtest_main
Scanning dependencies of target test_support_lib
[ 63%] Building CXX object crypto/test/CMakeFiles/test_support_lib.dir/abi_test.cc.o
/src/boringssl/crypto/test/abi_test.cc: In function 'void abi_test::internal::FatalError(Args ...) [with Args = {const char*}]':
/src/boringssl/crypto/test/abi_test.cc:334:8: error: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
   write(STDERR_FILENO, buf, strlen(buf));
   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/src/boringssl/crypto/test/abi_test.cc: In function 'void abi_test::internal::FatalError(Args ...) [with Args = {const char*, char*}]':
/src/boringssl/crypto/test/abi_test.cc:334:8: error: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
/src/boringssl/crypto/test/abi_test.cc: In function 'void abi_test::internal::FatalError(Args ...) [with Args = {const char*, const char*}]':
/src/boringssl/crypto/test/abi_test.cc:334:8: error: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
cc1plus: all warnings being treated as errors
make[2]: *** [crypto/test/CMakeFiles/test_support_lib.dir/build.make:63: crypto/test/CMakeFiles/test_support_lib.dir/abi_test.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:427: crypto/test/CMakeFiles/test_support_lib.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by centminmod** [comment]
also seems boringssl build in https://github.com/litespeedtech/lsquic/blob/master/.travis.yml differs from readme boringssl build as there's missing/different from readme following steps

```
    - cmake .
    - make
    - cd -
    - git submodule init
    - git submodule update
    - cmake -DBORINGSSL_DIR=$PWD/boringssl .
```

**Comment by centminmod** [comment]
seems with boringssl build error only happens if you try to do

```
cmake -DCMAKE_BUILD_TYPE=Release . && make
```

**Comment by dtikhonov** [comment]
```
    - cd -
    - git submodule init
    - git submodule update
    - cmake -DBORINGSSL_DIR=$PWD/boringssl .
```

These are lsquic steps, not BoringSSL steps.

**Comment by alexj0l** [comment]
> i still get an different error on boringssl make run
> 
> ```
> Scanning dependencies of target boringssl_gtest_main
> [ 63%] Building CXX object crypto/test/CMakeFiles/boringssl_gtest_main.dir/gtest_main.cc.o
> [ 63%] Built target boringssl_gtest_main
> Scanning dependencies of target test_support_lib
> [ 63%] Building CXX object crypto/test/CMakeFiles/test_support_lib.dir/abi_test.cc.o
> /src/boringssl/crypto/test/abi_test.cc: In function 'void abi_test::internal::FatalError(Args ...) [with Args = {const char*}]':
> /src/boringssl/crypto/test/abi_test.cc:334:8: error: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
>    write(STDERR_FILENO, buf, strlen(buf));
>    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /src/boringssl/crypto/test/abi_test.cc: In function 'void abi_test::internal::FatalError(Args ...) [with Args = {const char*, char*}]':
> /src/boringssl/crypto/test/abi_test.cc:334:8: error: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
> /src/boringssl/crypto/test/abi_test.cc: In function 'void abi_test::internal::FatalError(Args ...) [with Args = {const char*, const char*}]':
> /src/boringssl/crypto/test/abi_test.cc:334:8: error: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
> cc1plus: all warnings being treated as errors
> make[2]: *** [crypto/test/CMakeFiles/test_support_lib.dir/build.make:63: crypto/test/CMakeFiles/test_support_lib.dir/abi_test.cc.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:427: crypto/test/CMakeFiles/test_support_lib.dir/all] Error 2
> make: *** [Makefile:84: all] Error 2
> ```

I'm getting the same error now, is there any update on that?

**Comment by litespeedtech** [comment]
You can try the latest BoringSSL see if it gets better. 
I think BoringSSL cmake need to be updated to avoid generating warnings about unused results. 
It is from BoringSSL, so you should contact BoringSSL developer (Google) on this.
