### ISSUE TITLE
Running Http3 server

### ISSUE THREAD

**Issue by h0ax-ki1l3r** [litespeedtech/lsquic#81]
I see a some documentation available for http3 client, but I couldn't find any for the server.

- Are there any documentation available on how to start the http3-supported web server?
- Another noobish q, will this package need Lite Speed to be built before using lsquick? Essentially I want to setup a machine as a http3 supported web-server to conduct some academic experiments. 

Thanks

**Comment by dtikhonov** [comment]
> Are there any documentation available on how to start the http3-supported web server?

**Comment by litespeedtech** [comment]
Question answered -- closing.
