### ISSUE TITLE
Error compiling lsquic

### ISSUE THREAD

**Issue by eman-ramadan** [litespeedtech/lsquic#82]
I followed the installation instructions as mentioned here:
https://github.com/litespeedtech/lsquic/blob/master/README.md

while building BoringSSL module, I got this error when I was executing:
`patch -p1 -i ../patches/boringssl-meds.patch `
which says file not found
Later I found that it is in lsquic, so I think in the instructions lsquic needs to be downloaded first, and then the previous line needs to be changed to:
`patch -p1 -i ../lsquic/patches/boringssl-meds.patch `

**Comment by dtikhonov** [comment]
You're right: the build instructions could stand some improvement.  Thanks for the report!
