### ISSUE TITLE
[Question]using only QUIC without HTTP?

### ISSUE THREAD

**Issue by linxiaocong** [litespeedtech/lsquic#83]
Hi, can this lib be used as a pure QUIC library? For example, implementing an echo server and client, communicating using QUIC protocol?

Looking forward for your reply. Thx!

**Comment by dtikhonov** [comment]
Yes, it can.  As a matter of fact, we have a couple of non-HTTP client and server programs we can share.  They may need to be revived, though, as we haven't maintained them.

**Comment by litespeedtech** [comment]
See echo and MD5 client/server pairs in release 2.4.7.

Closing.

**Comment by linxiaocong** [comment]
wow, this is very helpful. thx!
