### ISSUE TITLE
HTTP3 faster than HTTPS1.1  or HTTP 2 for blob download.. reasons?

### ISSUE THREAD

**Issue by h0ax-ki1l3r** [litespeedtech/lsquic#84]
Hi, 
I have used your platform to do large blob downloads (e.g. 1G) files and force the browser to not exceed more than 1 parallel connection for download.

I see that HTTP 3 is much faster than HTTP 2 and 1.1. 
For instance, 
HTTPS 1.1 took 55 seconds
HTTP 2 took 50 seconds
HTTP 3 took 35 seconds.

Can anyone explain:
- Why HTTP 2 is faster than HTTP 1.1?
- Why is HTTP 3 faster than HTTP 1.1 and HTTP 2?

I know the overheads, but such high difference is what I am not sure.

Any thoughts?

Arvind

**Comment by dtikhonov** [comment]
Which server was serving HTTP/1.1 and HTTP/2 -- LiteSpeed Web Server or something else? As for HTTP/3, did you use LSWS as well?

lsquic uses BBR by default, so that may explain the difference in throughput.  Try changing it to Cubic to see how well it does.

**Comment by h0ax-ki1l3r** [comment]
I used OpenLiteSpeed to see perf. across all versions 1.1, 2 and 3. 

I read about the BBR, I plan to get some results with cubic today. Sure, BBR is aggressive. 
But why would HTTP 2 be faster than 1.1?
I am not sure if overheads will have that much of an impact.

**Comment by dtikhonov** [comment]
The HTTP/1.1 vs HTTP/2 question is better asked in [openlitespeed](https://github.com/litespeedtech/openlitespeed).

**Comment by h0ax-ki1l3r** [comment]
Sure, if I get a response, will post it here.
