### ISSUE TITLE
Some few possible spelling errors

### ISSUE THREAD

**Issue by jschleus** [litespeedtech/lsquic#87]
On the FOSS server fossies.org I have used a new functionality and have done as a trial a "codespell" run for the "lsquic" project. Here the version independent URL of the resulting report:

https://fossies.org/linux/www/lsquic/codespell.html

That URL redirects always to the URL of the report for the last "lsquic" release supported on Fossies (in case such a report was requested respectively is existing). Currently that is

https://fossies.org/linux/www/lsquic-2.5.1.tar.gz/codespell.html

Although I have already prefiltered some obviously wrong matches (false positives) please inform me if you find more of them so that I can force a new improved check.

I know it's not an important issue and naturally you can ignore it.

**Comment by dtikhonov** [comment]
Thank you for looking into this.  You're right: we usually have higher priority items.  Nevertheless, we'll gladly take a PR.

**Comment by jschleus** [comment]
Ok, understandable. But for different reasons I myself am unable to create a PR. If nobody else will create a PR the issue can be closed.

**Comment by dtikhonov** [comment]
Thank you.  We closed the issue because no one volunteered to fix it in about a year and it's not really a "bug" bug.  Maybe we'll spend some time and fix spelling error one day.
