### ISSUE TITLE
quic proxy?

### ISSUE THREAD

**Issue by pfeatherstone** [litespeedtech/lsquic#88]
Is it possible to have a quic server and a quic client in the same process? I noticed "lsquic_global_init" requires a flag that specifies whether the library is used in server mode or client mode globally. Does that mean you cannot have a connection accepted from a server creating a separate client connection, because of the global initialization?

**Comment by dtikhonov** [comment]
This is an excellent question.  You are correct: an instance of an lsquic engine cannot be used as both client and server.  To make a QUIC proxy, you need two lsquic engine instances.  This is doable, of course (we do it).

Now, it should possible to modify lsquic to support both modes at the same time.  We haven't looked into this deeply.  I wonder whether it can be done without changing the APIs.

As always, PRs are welcome!
