### ISSUE TITLE
Example server does not set cert lookup callback resulting in a crash

### ISSUE THREAD

**Issue by scguoi** [litespeedtech/lsquic#90]

**Comment by scguoi** [comment]
./http_server -s 127.0.0.1:8443
17:56:51.360 [NOTICE] Document root is not set: start in Interop Mode
33374 segmentation fault  ./http_server -s 127.0.0.1:8443

[curl http3 document](https://github.com/curl/curl/blob/master/docs/HTTP3.md)

**Comment by dtikhonov** [comment]
I reproduced it.  The problem is indeed in the driver: it expects there to be `-c` options.  Fix is coming.

In the meantime, use `-c` option.  The server won't do anything useful without it, anyway.

**Comment by litespeedtech** [comment]
Fixed in release 2.7.1.
