### ISSUE TITLE
try to access index 10 while array has only 10 elements

### ISSUE THREAD

**Issue by initlifeinc** [litespeedtech/lsquic#94]
hello, i am very confuse about these two lines codes

https://github.com/litespeedtech/lsquic/blob/a137764bf2616c04b189ec6f5f642b3c7ca17132/src/liblsquic/lsquic_trans_params.h#L82

here the size of array a 10. but when run to the next line code, it will calc a index 10 to access a[10].

https://github.com/litespeedtech/lsquic/blob/a137764bf2616c04b189ec6f5f642b3c7ca17132/src/liblsquic/lsquic_trans_params.c#L354

and please check this code.

TP_OFF(active_connection_id_limit)
 it seems value can be 10, and there is 11 elements in struct s.

(I run the http_client demo to upload a file, draft 24, and find tpi2idx[param_id] really will return value 10.)

I think there is some issues here, please help to confirm. Thanks.

**Comment by dtikhonov** [comment]
Thank you very much -- this is indeed a bug, it should be `a[11]`.

**Comment by dtikhonov** [comment]
Looking at this again, I've realized that the bug is benign: since the array `a` is inside a `union`, accessing its 11th element (calculated by the offset) won't corrupt adjacent struct elements.

The code is safe to use.

**Comment by initlifeinc** [comment]
yes, i understand why it will not raise a crash now. even the size of array a is 1, it also can run well.

**Comment by litespeedtech** [comment]
Fixed in release 2.7.3 -- closing.
