### ISSUE TITLE
where can i get lsquic architecture design? 

### ISSUE THREAD

**Issue by initlifeinc** [litespeedtech/lsquic#95]
I am not very sure the lsquic architecture design，so where can i get some informations about it? and the way to known what is the work flow that the lsquic hope developer to do. 

for example, a graph or some other informations about the work flow or design

init engine setting
init engine api
global init
setup logger 
setup lsquic_stream_if(set the callback of some events)
engine check setting
new engine
setup udp service(address..,setup packet out function)
engine connect to somewhere
alloc conn ctx when on_new_conn(manager conn ctx by developer)
create stream if needs
alloc stream ctx when on_new_stream(manager stream ctx by developer)
do write buf when on_write( can be invoke by some write api)
...

**Comment by dtikhonov** [comment]
The closest we have to the architecture document is [APIs.txt](../blob/master/APIs.txt).

Then, of course, there are sample programs: HTTP, MD5, and echo client and server programs.  Those are a good starting point to try things out.
