### ISSUE TITLE
When the environment variable " LSQUIC_DISABLE_HANDSHAKE "  is set, the code does not compile successfully.

### ISSUE THREAD

**Issue by rashiqaj** [litespeedtech/lsquic#97]
Enabled " LSQUIC_DISABLE_HANDSHAKE " environment variable and also set the #define LSQUIC_DISABLE_HANDSHAKE to one.   Getting build errors. This needs fixing.

**Comment by dtikhonov** [comment]
Thank you for the report.

This compilation mode will be removed in the future as it only works (or, rather, worked) for gQUIC and not IETF QUIC.

**Comment by rashiqaj** [comment]
Will it possible to implement this functionality for ietf quic? Is it a lot of change?

**Comment by dtikhonov** [comment]
It's certainly possible -- after all, it's just software -- but we have not considered it.  If I had to guess, I'd say that it would not be too hard, perhaps just a little more involved than for gQUIC.  You can see all the places that have special code for this now -- about a dozen spots.

If the goal is to debug encryption and decryption, I suggest using the logging mechanism, especially in conjunction with the `LSQUIC_LOG_SECRETS` environment variable.

**Comment by rashiqaj** [comment]
The intent is to be able to use the application in the environment where I dont care for TLS security and want to run without.

**Comment by dtikhonov** [comment]
We'd consider a PR that does this for IETF QUIC.

Since Google QUIC is going away, there are no plans to resuscitate this compilation mode.
