### ISSUE TITLE
Is it a correct way to calc next process time interval after call lsquic_engine_process_conns?

### ISSUE THREAD

**Issue by initlifeinc** [litespeedtech/lsquic#99]
If write to lsquic n bytes but only m (m<n) bytes are accepted. Is that means lsquic think only m  bytes should send and engine should wait for a while? maybe because of the limit calculated by bbr or cubic? 

if so, at that time, how long should engine need to wait?
use lsquic_engine_earliest_adv_tick to calculate the max time interval to wait unless read some packets to change the bandwidth or final timeout?

because sometimes i find the result of lsquic_engine_earliest_adv_tick is large than 10 seconds, is it normal to use this value to set the timeout of select/poll?

**Comment by dtikhonov** [comment]
There are different limits depending on whether you are writing to the stream from inside `on_write()` callback or outside of it (both are supported). In both cases, if you can write no more, you should wait for the next `on_write()` event.

You should follow the time suggested by the `lsquic_engine_earliest_adv_tick()` -- here is [how it is used](https://github.com/litespeedtech/lsquic/blob/022d9812f39321d09c3a19090b9288af19877774/test/prog.c#L446) in the standalone programs.  You can call `lsquic_engine_process_conns()` regularly (like every 100 ms) if you'd like, but you should not see a performance difference.

10 seconds is a normal value.  If you turn on debugging (`-l engine=debug`), you will [see what the next event](https://github.com/litespeedtech/lsquic/blob/022d9812f39321d09c3a19090b9288af19877774/src/liblsquic/lsquic_engine.c#L2798) is.
